import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const loads=await readFile(new URL('../src/modules/cargas/cargas.js',import.meta.url),'utf8');
const receiving=await readFile(new URL('../src/modules/recepcion-traspasos/recepcion-traspasos.js',import.meta.url),'utf8');
const orders=await readFile(new URL('../src/modules/ordenes/ordenes.js',import.meta.url),'utf8');
const tasks=await readFile(new URL('../src/modules/tareas-ubicacion/tareas-ubicacion.js',import.meta.url),'utf8');
const pallets=await readFile(new URL('../src/modules/palets/palets.js',import.meta.url),'utf8');
const silent=await readFile(new URL('../src/services/silent-refresh.js',import.meta.url),'utf8');

assert.ok(loads.includes("canConfirmExternalDelivery(s)?"),'la confirmación final debe limitarse a entregas externas');
assert.equal(loads.includes("s.destinationType==='EXTERNAL'?'Confirmar entrega':'Confirmar llegada'"),false,'no debe renderizarse Confirmar llegada para un traspaso interno');
assert.ok(loads.includes('shipment-details'),'las cargas deben tener información plegable');
assert.ok(receiving.includes('shipmentMatches(source,query)'),'la recepción debe filtrar mientras se escribe');
assert.ok(receiving.includes('await store.reload({emit:false})'),'la asignación debe verificarse contra el servidor');
assert.ok(tasks.includes("t.siteId===site||t.assignedTo===userId"),'el operario debe ver tareas asignadas aunque el centro activo sea distinto');
assert.ok(orders.includes("apiRequest('/orders')"),'el progreso debe consultarse con una petición pequeña de órdenes');
assert.ok(orders.includes('setInterval(()=>{refreshOrdersSilently(root);refreshAssignedPutawaySilently(root);},5000)'),'órdenes y tareas de ubicación deben refrescarse automáticamente');
assert.ok(orders.includes("t.type==='UBICAR_CARGA'&&t.assignedTo===me()?.id"),'Mis tareas debe incluir la ubicación asignada al operario');
assert.ok(pallets.includes('Registrar pallet físico'),'debe existir el registro de pallets físicos permanentes');
assert.ok(pallets.includes('Agregar al pallet'),'debe ser posible incorporar productos al pallet seleccionado');
assert.ok(pallets.includes('scan-register-pallet'),'el identificador numérico o alfanumérico del pallet debe poder escanearse');
assert.ok(pallets.includes('pallet-operation-dialog'),'mover y cargar pallets debe abrirse en ventanas compactas');
assert.ok(pallets.includes("operations:['palletsOperate']"),'las operaciones de pallet deben validarse también en el backend');
assert.equal(pallets.includes('Sacar productos a picking'),false,'Organizar pallets no debe iniciar el picking de pedidos');
assert.equal(pallets.includes('activar-modo-rapido'),false,'el acceso rápido de picking no debe existir dentro del detalle del pallet');
assert.ok(orders.includes('PICKING GUIADO'),'el picking debe seguir disponible exclusivamente desde Órdenes / Mis tareas');
assert.ok(pallets.includes('códigos incorporados viajarán juntos'),'la interfaz debe explicar que la posición pertenece al pallet completo');
assert.ok(silent.includes("collections.map(name=>apiRequest(`/${name}`))"),'los demás módulos deben actualizar solo sus colecciones');
console.log('OK · contratos de vista compacta, actualización silenciosa y flujo intercentro verificados');
