import { store } from '../../services/store.js';
import { shell,wireShell,toast,notice } from '../../layout/layout.js';
import { esc,badge,empty } from '../../components/ui.js';
import { parseXlsx,normalizeHeader } from '../../services/xlsx-reader.js';
import { activeSiteId,stockBySite } from '../../services/stock.js';
import { activeCompanyId,siteCompanyId } from '../../services/company.js';

let preview=null;
function siteName(id){return store.data.sites.find(s=>s.id===id)?.name||id;}
function parseRows(rows){if(!rows.length)return {errors:['El Excel está vacío.'],items:[]};const h=rows[0].map(normalizeHeader),ci=h.findIndex(x=>['CODIGO','SKU','CODIGO_PRODUCTO'].includes(x)),si=h.findIndex(x=>['STOCK','CANTIDAD','EXISTENCIA','EXISTENCIAS'].includes(x));if(ci<0||si<0)return {errors:['El Excel debe incluir CODIGO (o SKU) y STOCK (o CANTIDAD).'],items:[]};const errors=[],map=new Map();rows.slice(1).forEach((r,n)=>{const code=String(r[ci]??'').trim(),qty=Number(r[si]);if(!code&&!r[si])return;if(!store.data.products.some(p=>p.code===code)){errors.push(`Fila ${n+2}: código ${code||'(vacío)'} no existe en el catálogo.`);return;}if(!Number.isFinite(qty)||qty<0){errors.push(`Fila ${n+2}: stock inválido para ${code}.`);return;}map.set(code,qty);});return {errors,items:[...map].map(([code,qty])=>({code,qty}))};}
function rowsFor(siteId){const erp=store.data.settings?.erpStockBySite?.[siteId]||{};const codes=new Set([...Object.keys(erp),...(store.data.inventory||[]).map(i=>i.productCode)]);return [...codes].map(code=>{const wms=Number(stockBySite(code)[siteId]||0),kame=Object.hasOwn(erp,code)?Number(erp[code]):null,diff=kame===null?null:wms-kame,p=store.data.products.find(x=>x.code===code);return {code,name:p?.name||p?.description||'Producto',wms,kame,diff};}).filter(x=>x.kame!==null||x.wms>0).sort((a,b)=>Math.abs(Number(b.diff||0))-Math.abs(Number(a.diff||0))||a.code.localeCompare(b.code));}
function previewHtml(){if(!preview)return '<div class="import-empty">Selecciona un Excel con CODIGO y STOCK para este centro.</div>';return `${preview.errors.length?`<div class="import-errors"><b>Corrige antes de cargar:</b>${preview.errors.slice(0,30).map(e=>`<p>${esc(e)}</p>`).join('')}</div>`:`<div class="callout"><b>Referencia lista</b><span>${preview.items.length} productos reconocidos.</span></div>`}`;}
export function renderReconciliation(root){const company=activeCompanyId(),sites=(store.data.sites||[]).filter(s=>siteCompanyId(s)===company&&s.active!==false),siteId=activeSiteId(),rows=rowsFor(siteId),diffs=rows.filter(r=>r.diff!==null&&r.diff!==0),matched=rows.filter(r=>r.diff===0);const body=`<div class="page-intro"><div><span class="eyebrow">SANIDAD DE INVENTARIO</span><h2>Conciliación WMS ↔ Kame</h2><p>Compara el stock físico calculado por el WMS con una referencia de stock exportada desde Kame. La API real se conectará cuando exista documentación.</p></div></div><section class="panel"><div class="form-grid"><label>Centro<select id="recon-site">${sites.map(s=>`<option value="${esc(s.id)}" ${s.id===siteId?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>Excel de referencia<input id="recon-file" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"></label></div><div id="recon-preview">${previewHtml()}</div><div class="dialog-actions"><button id="save-recon" class="primary" type="button" ${preview?.items?.length&&!preview.errors.length?'':'disabled'}>Guardar referencia Kame</button></div></section><section class="panel"><div class="center-summary"><div><small>Comparados</small><b>${rows.filter(r=>r.kame!==null).length}</b></div><div><small>Cuadrados</small><b>${matched.length}</b></div><div><small>Con diferencia</small><b>${diffs.length}</b></div><div><small>Centro</small><b>${esc(siteName(siteId))}</b></div></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>Producto</th><th>WMS físico</th><th>Kame ref.</th><th>Diferencia</th><th>Estado</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.code)}</b></td><td>${esc(r.name)}</td><td>${r.wms}</td><td>${r.kame===null?'—':r.kame}</td><td><b>${r.diff===null?'—':r.diff>0?`+${r.diff}`:r.diff}</b></td><td>${r.diff===null?badge('Sin referencia','neutral'):r.diff===0?badge('CUADRADO','ok'):badge('REVISAR','warn')}</td></tr>`).join('')||`<tr><td colspan="6">${empty('Sin referencia de Kame','Carga un Excel CODIGO + STOCK para comenzar la conciliación.')}</td></tr>`}</tbody></table></div></section>`;root.innerHTML=shell('Conciliación WMS ↔ Kame',body,'conciliacion');wireShell();
 document.querySelector('#recon-site').onchange=e=>{const id=e.target.value,site=store.data.sites.find(s=>s.id===id);localStorage.setItem('serco_wms_active_site',id);localStorage.setItem('serco_wms_active_company',siteCompanyId(site,store.data));preview=null;renderReconciliation(root);};
 document.querySelector('#recon-file').onchange=async e=>{try{preview=parseRows(await parseXlsx(e.target.files?.[0]));document.querySelector('#recon-preview').innerHTML=previewHtml();document.querySelector('#save-recon').disabled=preview.errors.length>0||!preview.items.length;}catch(err){preview={errors:[err.message],items:[]};document.querySelector('#recon-preview').innerHTML=previewHtml();document.querySelector('#save-recon').disabled=true;}};
 document.querySelector('#save-recon').onclick=async()=>{if(!preview||preview.errors.length||!preview.items.length)return;await store.commit(d=>{d.settings.erpStockBySite=d.settings.erpStockBySite||{};d.settings.erpStockBySite[siteId]=Object.fromEntries(preview.items.map(x=>[x.code,x.qty]));d.settings.erpStockUpdatedAt=d.settings.erpStockUpdatedAt||{};d.settings.erpStockUpdatedAt[siteId]=new Date().toISOString();},`Referencia Kame actualizada para ${siteName(siteId)}`);preview=null;renderReconciliation(root);await notice('Conciliación actualizada','La referencia de Kame quedó guardada y las diferencias fueron recalculadas.','success');};
}
