import { instalarPWA, estadoPWA } from '../../services/pwa.js';
import { store } from '../../services/store.js';
import { esc, badge, empty } from '../../components/ui.js';
import { crearEscaner } from '../../services/escaner.js';
import { openProductEditor } from '../../services/product-editor.js';

const rutas={inicio:'movil',buscar:'movil?seccion=buscar',recibir:'movil?seccion=recibir',despachar:'movil?seccion=despachar',mas:'movil?seccion=mas'};
function consulta(){return new URLSearchParams(location.hash.split('?')[1]||'');}
function seccion(){return consulta().get('seccion')||'inicio';}
function ir(sec){location.hash=`#/movil${sec==='inicio'?'':`?seccion=${sec}`}`;}
function producto(c){return store.data.products.find(p=>p.code===c);}
function nombre(c){return producto(c)?.name||`Producto ${c}`;}
function normalizar(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function inventarioProducto(code){return store.data.inventory.filter(i=>i.productCode===code&&i.qty>0);}
function opcionesUsuarios(){return store.data.users.filter(u=>u.active).map(u=>`<option value="${esc(u.id)}">${esc(u.name)}</option>`).join('');}
function operadorActual(){return store.data.users.find(u=>u.id===store.data.session.userId);}
function resultados(q){
  const raw=normalizar(q); if(!raw)return '';
  const tokens=raw.split(/\s+/).filter(Boolean);
  const lista=store.data.products.map(p=>{
    const c=normalizar(p.code),n=normalizar(p.name),d=normalizar(p.description),f=normalizar(p.type||p.family),a=normalizar((p.previousCodes||[]).join(' '));let score=0;
    if(c===raw)score+=100;if(c.startsWith(raw))score+=45;if(n.startsWith(raw))score+=35;
    tokens.forEach(t=>{if(c.includes(t))score+=25;if(n.includes(t))score+=18;if(d.includes(t))score+=18;if(a.includes(t))score+=15;if(f.includes(t))score+=8;});
    return {p,score};
  }).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,12).map(x=>x.p);
  if(!lista.length)return empty('Sin resultados','Prueba con otra palabra, descripción o código.');
  return lista.map(p=>{
    const inv=inventarioProducto(p.code),total=inv.reduce((a,b)=>a+b.qty,0);
    return `<article class="movil-producto"><button class="movil-producto-resumen desplegar" data-id="detalle-${esc(p.code)}"><div class="movil-producto-datos"><span class="sku">CÓDIGO ${esc(p.code)}</span><b>${esc(p.name)}</b><small><b>Descripción:</b> ${esc(p.description||'No registrada')}</small></div><div class="movil-cantidad"><small>Cantidad</small>${badge(`${total} un.`,total?'ok':'warn')}<span class="chevron">⌄</span></div></button><div id="detalle-${esc(p.code)}" class="movil-detalle oculto"><div class="movil-detalle-resumen"><span><b>Descripción</b><small>${esc(p.description||'No registrada')}</small></span><span><b>Cantidad total</b><small>${total} unidades</small></span></div>${inv.length?inv.map(i=>`<div class="movil-ubicacion"><span><b>${esc(i.locationId)}</b><small>${i.palletId?`Palet ${esc(i.palletId)}`:'Ubicación directa'}</small></span><strong>${i.qty} un.</strong></div>`).join(''):'<p class="muted">Aún sin ubicación registrada.</p>'}<div class="movil-acciones"><a class="secondary" href="#/movimientos?code=${encodeURIComponent(p.code)}">Mover</a><a class="ghost" href="#/transferencias?code=${encodeURIComponent(p.code)}">Despachar</a><button class="ghost movil-edit-product" data-code="${esc(p.code)}" type="button">Editar / Inventario</button></div></div></article>`;
  }).join('');
}

function envoltorio(titulo,contenido,activo='inicio'){
  const nav=[['inicio','⌂','Inicio'],['buscar','⌕','Buscar'],['recibir','⇩','Recibir'],['despachar','⇄','Despachar'],['mas','⋯','Más']];
  const op=operadorActual(); return `<div class="movil-app"><header class="movil-cabecera"><div><small>REC · Bodega Recoleta · ${esc(op?.name||'Sin operador')}</small><h1>${esc(titulo)}</h1></div><a href="#/dashboard" class="movil-admin" title="Abrir panel administrativo"><span>⚙</span><small>Admin</small></a></header><main class="movil-contenido">${contenido}</main><nav class="movil-nav">${nav.map(([id,ico,txt])=>`<a href="#/${rutas[id]}" class="${activo===id?'activo':''}"><span>${ico}</span><small>${txt}</small></a>`).join('')}</nav><div id="toast" class="toast"></div></div>`;
}
function aviso(msg){const el=document.querySelector('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400);}
function cablearDesplegables(){document.querySelectorAll('.desplegar').forEach(b=>b.onclick=()=>document.querySelector(`#${CSS.escape(b.dataset.id)}`)?.classList.toggle('oculto'));}

function inicio(){
 const d=store.data;const porUbicar=d.receipts.filter(r=>r.status==='POR_UBICAR').length;const transito=d.transfers.filter(t=>t.status==='EN_TRANSITO').length;
 return envoltorio('Operación móvil',`<section class="movil-bienvenida"><span class="eyebrow">OPERACIÓN RÁPIDA</span><h2>¿Qué necesitas hacer?</h2><p>Acciones principales al alcance de una mano.</p></section><div class="movil-atajos"><button data-ir="buscar"><span>⌕</span><b>Buscar</b><small>Código o descripción</small></button><button data-ir="recibir"><span>⇩</span><b>Recibir</b><small>Escanear mercadería</small></button><button data-ir="despachar"><span>⇄</span><b>Despachar</b><small>Preparar una salida</small></button><a href="#/palets"><span>▣</span><b>Organizar palet</b><small>Ubicar lo recibido</small></a><a href="#/movimientos"><span>↔</span><b>Mover</b><small>Reubicar producto</small></a></div><section class="movil-resumen"><button class="desplegar" data-id="estado-operacion"><span><b>Estado de operación</b><small>Información resumida</small></span><span class="chevron">⌄</span></button><div id="estado-operacion" class="oculto"><div class="mini-metricas"><div><b>${porUbicar}</b><small>Recepciones por ubicar</small></div><div><b>${transito}</b><small>Salidas en tránsito</small></div><div><b>${d.locations.filter(l=>l.active).length}</b><small>Ubicaciones activas</small></div></div></div></section>`, 'inicio');
}

function buscador(){
 return envoltorio('Buscar producto',`<section class="movil-buscar"><div class="movil-input-grande"><span>⌕</span><input id="movil-q" autofocus autocomplete="off" placeholder="Código o descripción…"><button id="camara-buscar" type="button" aria-label="Escanear con cámara">▣</button></div><p class="ayuda">Escribe “codo”, “Orbit”, parte del código o usa la cámara.</p><div id="movil-resultados"></div></section>${modalCamara()}`,'buscar');
}

function recepcionActiva(){return store.data.receipts.find(r=>r.status==='RECIBIENDO');}
function opcionesTemporales(){return store.data.locations.filter(l=>l.active&&l.kind==='POR_UBICAR').map(l=>`<option value="${esc(l.id)}">${esc(l.id)}</option>`).join('');}
function recibir(){
 const r=recepcionActiva();
 const cuerpo=r?`<section class="movil-flujo"><div class="movil-estado"><div><span class="eyebrow">RECEPCIÓN ABIERTA</span><h2>${esc(r.id)}</h2><small>${esc(r.palletId)} · ${esc(r.origin)}</small></div>${badge('RECIBIENDO','warn')}</div><form id="movil-rec-form" class="movil-form-escaneo"><label>Código<div class="entrada-con-camara"><input id="movil-rec-code" required inputmode="numeric" placeholder="Escanea o escribe"><button id="camara-recibir" type="button">▣</button></div></label><label>Cantidad<input id="movil-rec-qty" type="number" min="1" value="1" required></label><button class="primary" type="submit">Agregar</button></form><button class="fila-desplegable desplegar" data-id="lista-recepcion"><span><b>Productos agregados</b><small>${(r.items||[]).length} líneas</small></span><span>⌄</span></button><div id="lista-recepcion" class="oculto lista-compacta">${(r.items||[]).length?r.items.map((x,i)=>`<div><span><b>${esc(x.code)}</b><small>${esc(nombre(x.code))}</small></span><strong>${x.qty}</strong><button class="ghost quitar-rec" data-i="${i}">×</button></div>`).join(''):empty('Sin productos','Escanea el primer código.')}</div><div class="movil-cerrar"><label>Ubicación temporal<select id="movil-rec-temp"><option value="">Seleccionar…</option>${opcionesTemporales()}</select></label><button class="fila-desplegable desplegar" data-id="responsable-recepcion" type="button"><span><b>Responsables</b><small>Quién recibe y quién revisa</small></span><span>⌄</span></button><div id="responsable-recepcion" class="oculto panel-responsables"><small>Recibe automáticamente: <b>${esc(store.data.users.find(u=>u.id===r.receivedBy)?.name||r.receivedBy)}</b></small><label>Supervisado / revisado por<select id="movil-rec-supervisor"><option value="">Seleccionar…</option>${opcionesUsuarios()}</select></label></div><button id="movil-cerrar-rec" class="primary">Cerrar → POR UBICAR</button></div></section>`:`<section class="movil-bienvenida"><span class="eyebrow">RECEPCIÓN RÁPIDA</span><h2>Recibe ahora. Ordena después.</h2><p>Crea un palet temporal y comienza a escanear sin decidir todavía la posición final.</p><button id="movil-nueva-rec" class="primary ancho">+ Nueva recepción</button></section><div id="form-nueva-rec" class="panel-movil oculto"><label>Origen<select id="movil-origen"><option>Importación</option><option>Proveedor</option><option>Tienda / devolución</option><option>Cliente / devolución</option><option>Otro</option></select></label><label>Quién trae<input id="movil-trae" placeholder="Nombre"></label><button id="movil-crear-rec" class="primary ancho">Comenzar recepción</button></div>`;
 return envoltorio('Recepción',cuerpo+modalCamara(),'recibir');
}

function transferenciaActiva(){return store.data.transfers.find(t=>['PREPARANDO','LISTO'].includes(t.status));}
function disponible(c){return store.data.inventory.filter(i=>i.productCode===c&&i.qty>0).reduce((a,b)=>a+b.qty,0);}
function despachar(){
 const t=transferenciaActiva();
 const cuerpo=t?`<section class="movil-flujo"><div class="movil-estado"><div><span class="eyebrow">SALIDA ABIERTA</span><h2>${esc(t.id)}</h2><small>${esc(t.destinationName)} · ${esc(t.driver||'Sin conductor')}</small></div>${badge('PREPARANDO','warn')}</div><form id="movil-tr-form" class="movil-form-escaneo"><label>Código<div class="entrada-con-camara"><input id="movil-tr-code" required placeholder="Escanea o escribe"><button id="camara-despachar" type="button">▣</button></div></label><label>Cantidad<input id="movil-tr-qty" type="number" min="1" value="1"></label><button class="primary">Agregar</button></form><button class="fila-desplegable desplegar" data-id="lista-salida"><span><b>Productos preparados</b><small>${(t.items||[]).length} líneas</small></span><span>⌄</span></button><div id="lista-salida" class="oculto lista-compacta">${(t.items||[]).length?t.items.map((x,i)=>`<div><span><b>${esc(x.code)}</b><small>${esc(nombre(x.code))}</small></span><strong>${x.qty}</strong><button class="ghost quitar-tr" data-i="${i}">×</button></div>`).join(''):empty('Salida vacía','Escanea los productos que se llevará el conductor.')}</div><div class="movil-cerrar"><button class="fila-desplegable desplegar" data-id="responsable-despacho" type="button"><span><b>Responsables</b><small>Quién despacha y quién revisa</small></span><span>⌄</span></button><div id="responsable-despacho" class="oculto panel-responsables"><small>Despacha automáticamente: <b>${esc(store.data.users.find(u=>u.id===store.data.session.userId)?.name||store.data.session.userId)}</b></small><label>Supervisado / revisado por<select id="movil-tr-supervisor"><option value="">Seleccionar…</option>${opcionesUsuarios()}</select></label></div><button id="movil-en-transito" class="primary ancho espacio-superior">Confirmar salida → EN TRÁNSITO</button></div></section>`:`<section class="movil-bienvenida"><span class="eyebrow">DESPACHO CONTROLADO</span><h2>Escanea lo que realmente sale.</h2><p>El conductor quedará asociado a los productos que se lleva.</p><button id="movil-nueva-tr" class="primary ancho">+ Nueva salida</button></section><div id="form-nueva-tr" class="panel-movil oculto"><label>Destino<select id="movil-destino"><option value="TIENDA">Bodega tienda de ventas</option><option value="OTRO">Otro / pendiente</option></select></label><label>Conductor / quien retira<input id="movil-conductor" placeholder="Nombre"></label><button id="movil-crear-tr" class="primary ancho">Comenzar preparación</button></div>`;
 return envoltorio('Despacho',cuerpo+modalCamara(),'despachar');
}

function mas(){
 const d=store.data;
 return envoltorio('Más opciones',`<div class="movil-lista-menu"><button id="movil-instalar-pwa" class="movil-menu-button" type="button"><span>▣</span><div><b>Instalar aplicación</b><small>Agregar SercoRiego WMS al dispositivo</small></div><i>›</i></button><a href="#/palets"><span>▣</span><div><b>Organizar palets</b><small>Buscar, escanear y ubicar productos</small></div><i>›</i></a><a href="#/racks"><span>▦</span><div><b>Racks</b><small>Consultar estructura</small></div><i>›</i></a><a href="#/productos"><span>◫</span><div><b>Productos</b><small>Catálogo registrado</small></div><i>›</i></a><a href="#/historial"><span>◷</span><div><b>Historial</b><small>Trazabilidad completa</small></div><i>›</i></a><a href="#/usuarios"><span>♙</span><div><b>Operador / usuarios</b><small>Cambiar responsable o administrar personas</small></div><i>›</i></a><a href="#/dashboard"><span>⚙</span><div><b>Panel administrativo</b><small>Configuración y control completo</small></div><i>›</i></a></div><section class="panel-movil"><small>Ubicaciones activas: <b>${d.locations.filter(l=>l.active).length}</b></small><small>Versión demostración · Desarrollado por Vexhora Group · CEO Ing. Carlin Arenas</small></section>`,'mas');
}

function modalCamara(){return `<dialog id="dialogo-camara" class="dialogo-camara"><div class="camara-cabecera"><div><b>Escanear código</b><small>Apunta al código de barras</small></div><button id="cerrar-camara" class="ghost">×</button></div><video id="video-camara" autoplay playsinline muted></video><div id="estado-camara" class="estado-camara">Solicitando cámara…</div></dialog>`;}

async function abrirCamara(inputId){
 const dlg=document.querySelector('#dialogo-camara'),video=document.querySelector('#video-camara'),estado=document.querySelector('#estado-camara');if(!dlg||!video)return;
 const escaner=crearEscaner();dlg.showModal();estado.textContent='Abriendo cámara…';
 const cerrar=()=>{escaner.detener();dlg.close();};document.querySelector('#cerrar-camara').onclick=cerrar;dlg.oncancel=e=>{e.preventDefault();cerrar();};
 await escaner.iniciar(video,(valor)=>{const input=document.querySelector(`#${inputId}`);if(input){input.value=valor;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();}dlg.close();aviso(`Código detectado: ${valor}`);},msg=>{estado.textContent=msg;});
}

function cablearInicio(){document.querySelectorAll('[data-ir]').forEach(b=>b.onclick=()=>ir(b.dataset.ir));cablearDesplegables();}
function cablearBuscar(){const q=document.querySelector('#movil-q'),out=document.querySelector('#movil-resultados');const pintar=()=>{out.innerHTML=resultados(q.value);cablearDesplegables();document.querySelectorAll('.movil-edit-product').forEach(b=>b.onclick=()=>openProductEditor(b.dataset.code,{onSaved:(newCode)=>{if(q.value.trim()===b.dataset.code)q.value=newCode;pintar();}}));};q.oninput=pintar;document.querySelector('#camara-buscar').onclick=()=>abrirCamara('movil-q');}
function cablearRecibir(root){cablearDesplegables();const r=recepcionActiva();if(!r){document.querySelector('#movil-nueva-rec').onclick=()=>document.querySelector('#form-nueva-rec').classList.toggle('oculto');document.querySelector('#movil-crear-rec').onclick=async()=>{const idx=store.data.receipts.length+1,id=`REC-${String(idx).padStart(6,'0')}`,pid=`PAL-${String(100+idx).padStart(4,'0')}`,now=new Date().toISOString(),origin=document.querySelector('#movil-origen').value,broughtBy=document.querySelector('#movil-trae').value.trim();await store.commit(s=>{s.receipts.unshift({id,palletId:pid,status:'RECIBIENDO',origin,broughtBy,note:'',arrivedAt:now,receivedBy:s.session.userId,supervisedBy:null,tempLocationId:null,items:[]});s.pallets.push({id:pid,siteId:'REC',status:'RECIBIENDO',locationId:null,origin,createdAt:now});},`Recepción ${id} iniciada desde móvil`);renderMovil(root);};return;}
 const sel=document.querySelector('#movil-rec-temp');if(r.tempLocationId)sel.value=r.tempLocationId;document.querySelector('#camara-recibir').onclick=()=>abrirCamara('movil-rec-code');document.querySelector('#movil-rec-form').onsubmit=async e=>{e.preventDefault();const code=document.querySelector('#movil-rec-code').value.replace(/\D/g,''),qty=Number(document.querySelector('#movil-rec-qty').value);if(!code||qty<1)return;await store.commit(s=>{let p=s.products.find(x=>x.code===code);if(!p){p={id:`SKU-${Date.now()}`,code,name:`Producto ${code}`,description:'',previousCodes:[],family:'Por clasificar',rotation:'MEDIA',pickingLocationId:null,createdAt:new Date().toISOString()};s.products.push(p);}const rr=s.receipts.find(x=>x.id===r.id),it=rr.items.find(x=>x.code===code);if(it)it.qty+=qty;else rr.items.push({code,qty});},`Producto ${code} agregado a ${r.id} desde móvil`);renderMovil(root);};document.querySelectorAll('.quitar-rec').forEach(b=>b.onclick=async()=>{await store.commit(s=>s.receipts.find(x=>x.id===r.id).items.splice(Number(b.dataset.i),1),`Producto retirado de ${r.id}`);renderMovil(root);});document.querySelector('#movil-cerrar-rec').onclick=async()=>{const temp=sel.value,supervisedBy=document.querySelector('#movil-rec-supervisor')?.value||'';if(!(r.items||[]).length){aviso('Agrega al menos un producto');return;}if(!temp){aviso('Selecciona ubicación temporal');return;}if(!supervisedBy){aviso('Selecciona quién revisó la recepción');return;}const now=new Date().toISOString();await store.commit(s=>{const rr=s.receipts.find(x=>x.id===r.id);rr.status='POR_UBICAR';rr.closedAt=now;rr.tempLocationId=temp;rr.supervisedBy=supervisedBy;const pal=s.pallets.find(x=>x.id===rr.palletId);pal.status='POR_UBICAR';pal.locationId=temp;for(const it of rr.items){let inv=s.inventory.find(i=>i.productCode===it.code&&i.locationId===temp&&i.palletId===rr.palletId);if(inv)inv.qty+=it.qty;else s.inventory.push({id:`INV-${Date.now()}-${it.code}`,productCode:it.code,locationId:temp,qty:it.qty,palletId:rr.palletId});}const loc=s.locations.find(l=>l.id===temp);if(loc)loc.status='OCUPADA';},`Recepción ${r.id} cerrada desde móvil en ${temp}`);renderMovil(root);};}
function cablearDespacho(root){cablearDesplegables();const t=transferenciaActiva();if(!t){document.querySelector('#movil-nueva-tr').onclick=()=>document.querySelector('#form-nueva-tr').classList.toggle('oculto');document.querySelector('#movil-crear-tr').onclick=async()=>{const idx=store.data.transfers.length+1,id=`TRF-${String(idx).padStart(6,'0')}`,dest=document.querySelector('#movil-destino').value,driver=document.querySelector('#movil-conductor').value.trim(),destinationName=dest==='TIENDA'?'Bodega tienda de ventas':'Otro destino',now=new Date().toISOString();await store.commit(s=>s.transfers.unshift({id,sourceSiteId:'REC',destinationSiteId:dest,destinationName,driver,status:'PREPARANDO',createdAt:now,items:[],supervisedBy:null,dispatchedBy:null}),`Salida ${id} creada desde móvil`);renderMovil(root);};return;}
 document.querySelector('#camara-despachar').onclick=()=>abrirCamara('movil-tr-code');document.querySelector('#movil-tr-form').onsubmit=async e=>{e.preventDefault();const code=document.querySelector('#movil-tr-code').value.replace(/\D/g,''),qty=Number(document.querySelector('#movil-tr-qty').value),avail=disponible(code);if(!producto(code)){aviso('Código no registrado');return;}if(qty>avail){aviso(`Solo hay ${avail} unidades localizadas`);return;}await store.commit(s=>{const tt=s.transfers.find(x=>x.id===t.id),it=tt.items.find(x=>x.code===code);if(it)it.qty+=qty;else tt.items.push({code,qty});},`Producto ${code} agregado a ${t.id} desde móvil`);renderMovil(root);};document.querySelectorAll('.quitar-tr').forEach(b=>b.onclick=async()=>{await store.commit(s=>s.transfers.find(x=>x.id===t.id).items.splice(Number(b.dataset.i),1),`Producto retirado de ${t.id}`);renderMovil(root);});document.querySelector('#movil-en-transito').onclick=async()=>{const supervisedBy=document.querySelector('#movil-tr-supervisor')?.value||'';if(!(t.items||[]).length){aviso('Agrega productos antes de despachar');return;}if(!supervisedBy){aviso('Selecciona quién revisó el despacho');return;}for(const it of t.items){if(it.qty>disponible(it.code)){aviso(`Existencias insuficientes para ${it.code}`);return;}}const now=new Date().toISOString();await store.commit(s=>{const tt=s.transfers.find(x=>x.id===t.id);for(const it of tt.items){let need=it.qty;for(const inv of s.inventory.filter(i=>i.productCode===it.code&&i.qty>0)){const take=Math.min(inv.qty,need);inv.qty-=take;need-=take;if(!need)break;}s.inventory=s.inventory.filter(i=>i.qty>0);}tt.status='EN_TRANSITO';tt.departedAt=now;tt.scannedBy=s.session.userId;tt.dispatchedBy=s.session.userId;tt.supervisedBy=supervisedBy;},`Transferencia ${t.id} salió EN TRÁNSITO desde móvil`);renderMovil(root);};}

export function renderMovil(root){
 const sec=seccion();
 if(sec==='buscar')root.innerHTML=buscador();else if(sec==='recibir')root.innerHTML=recibir();else if(sec==='despachar')root.innerHTML=despachar();else if(sec==='mas')root.innerHTML=mas();else root.innerHTML=inicio();
 if(sec==='buscar')cablearBuscar();else if(sec==='recibir')cablearRecibir(root);else if(sec==='despachar')cablearDespacho(root);else if(sec==='inicio')cablearInicio();else {
   cablearDesplegables();
   const instalar=document.querySelector('#movil-instalar-pwa');
   if(instalar){ instalar.hidden=estadoPWA().instalada; instalar.onclick=()=>instalarPWA(); }
 }
}
