import { store } from '../../services/store.js';
import { shell,wireShell,toast } from '../../layout/layout.js';
import { esc,badge,empty } from '../../components/ui.js';
import { inventorySiteId } from '../../services/stock.js';

function currentUser(){return store.data.users.find(u=>u.id===store.data.session.userId);}
function canAdmin(){return currentUser()?.role==='ADMINISTRADOR';}
function siteStock(siteId){return (store.data.inventory||[]).filter(i=>inventorySiteId(i)===siteId&&Number(i.qty)>0).reduce((a,b)=>a+Number(b.qty||0),0);}
function siteSku(siteId){return new Set((store.data.inventory||[]).filter(i=>inventorySiteId(i)===siteId&&Number(i.qty)>0).map(i=>i.productCode)).size;}
function siteLocations(siteId){return (store.data.locations||[]).filter(l=>l.siteId===siteId&&l.active!==false).length;}
function typeName(v){return ({BODEGA:'Bodega / centro de distribución',TIENDA:'Tienda / sucursal',BODEGA_TIENDA:'Bodega + tienda'}[v]||v||'Centro');}
function siteCard(s){return `<button class="center-card" data-site="${esc(s.id)}" type="button"><div class="center-card-head"><div><span class="eyebrow">${esc(typeName(s.type))}</span><h3>${esc(s.name)}</h3><small>${esc(s.code||s.id)}</small></div>${badge(s.active!==false?'ACTIVO':'INACTIVO',s.active!==false?'ok':'warn')}</div><div class="center-metrics"><span><b>${siteStock(s.id)}</b><small>unidades</small></span><span><b>${siteSku(s.id)}</b><small>productos</small></span><span><b>${siteLocations(s.id)}</b><small>ubicaciones</small></span></div><div class="center-card-foot">Ver ficha y organización <b>→</b></div></button>`;}
function detailHtml(site){
  const inv=(store.data.inventory||[]).filter(i=>inventorySiteId(i)===site.id&&Number(i.qty)>0);
  const rows=[...new Set(inv.map(i=>i.productCode))].map(code=>{const p=store.data.products.find(x=>x.code===code);const qty=inv.filter(i=>i.productCode===code).reduce((a,b)=>a+Number(b.qty||0),0);return `<tr class="click-row" data-product="${esc(code)}"><td><b>${esc(code)}</b></td><td>${esc(p?.name||p?.description||`Producto ${code}`)}</td><td><b>${qty}</b></td><td><button class="ghost small open-product" data-code="${esc(code)}">Ver ficha</button></td></tr>`;}).join('');
  return `<section class="panel center-detail"><div class="panel-head"><div><span class="eyebrow">FICHA DEL CENTRO</span><h2>${esc(site.name)}</h2><small>${esc(typeName(site.type))} · Código ${esc(site.code||site.id)}</small></div><div class="center-detail-actions">${canAdmin()?`<a class="secondary" href="#/estructura?site=${encodeURIComponent(site.id)}">Configurar estructura</a><button class="secondary" id="edit-center" type="button">Editar centro</button>`:''}<button class="ghost" id="close-center" type="button">Cerrar</button></div></div><div class="center-summary"><div><small>Stock</small><b>${siteStock(site.id)}</b></div><div><small>Productos distintos</small><b>${siteSku(site.id)}</b></div><div><small>Ubicaciones</small><b>${siteLocations(site.id)}</b></div><div><small>Estado</small><b>${site.active!==false?'Activo':'Inactivo'}</b></div></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>Producto</th><th>Stock en este centro</th><th></th></tr></thead><tbody>${rows||`<tr><td colspan="4">${empty('Sin stock registrado','Cuando se transfieran productos a este centro aparecerán aquí.')}</td></tr>`}</tbody></table></div></section>`;
}
function dialogHtml(){return `<dialog id="center-dialog"><form id="center-form" class="dialog-card"><div class="dialog-head"><div><span class="eyebrow">CENTRO / SUCURSAL</span><h3 id="center-dialog-title">Nuevo centro</h3></div><button type="button" id="close-center-dialog" class="ghost">×</button></div><input id="center-id" type="hidden"><label>Nombre del centro o tienda<input id="center-name" required maxlength="100" placeholder="Escribe el nombre real"></label><label>Código corto<input id="center-code" required maxlength="10" placeholder="Ej. REC"></label><label>Tipo<select id="center-type"><option value="BODEGA">Bodega / centro de distribución</option><option value="TIENDA">Tienda / sucursal</option><option value="BODEGA_TIENDA">Bodega + tienda</option></select></label><label>Notas<textarea id="center-notes" rows="2" maxlength="240" placeholder="Opcional"></textarea></label><label class="toggle-line"><input id="center-active" type="checkbox" checked> Centro activo</label><div class="warning-box">El centro tendrá stock y organización propios, pero compartirá el mismo catálogo de productos maestros.</div><div class="dialog-actions"><button type="button" id="cancel-center" class="ghost">Cancelar</button><button class="primary" type="submit">Guardar centro</button></div></form></dialog>`;}
function openDialog(site=null){const dlg=document.querySelector('#center-dialog');document.querySelector('#center-dialog-title').textContent=site?'Editar centro':'Nuevo centro';document.querySelector('#center-id').value=site?.id||'';document.querySelector('#center-name').value=site?.name||'';document.querySelector('#center-code').value=site?.code||'';document.querySelector('#center-type').value=site?.type||'TIENDA';document.querySelector('#center-notes').value=site?.notes||'';document.querySelector('#center-active').checked=site?.active!==false;dlg.showModal();}
function safeId(code){return String(code||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,12);}
export function renderCenters(root){
 const allowed=canAdmin(); const body=`<div class="page-intro"><div><span class="eyebrow">MULTICENTRO</span><h2>Centros y sucursales</h2><p>Cada centro organiza su propio stock y ubicaciones. El catálogo de productos es único para toda Serco Riego.</p></div>${allowed?'<button id="new-center" class="primary" type="button">+ Nuevo centro / tienda</button>':''}</div><div class="centers-grid">${(store.data.sites||[]).map(siteCard).join('')}</div><div id="center-detail-slot"></div>${dialogHtml()}`;
 root.innerHTML=shell('Centros y Sucursales',body,'centros');wireShell();
 document.querySelector('#new-center')?.addEventListener('click',()=>openDialog());
 document.querySelectorAll('.center-card').forEach(b=>b.addEventListener('click',()=>{const site=store.data.sites.find(s=>s.id===b.dataset.site);const slot=document.querySelector('#center-detail-slot');slot.innerHTML=detailHtml(site);slot.scrollIntoView({behavior:'smooth',block:'start'});document.querySelector('#close-center').onclick=()=>slot.innerHTML='';document.querySelector('#edit-center')?.addEventListener('click',()=>openDialog(site));document.querySelectorAll('.open-product').forEach(x=>x.onclick=e=>{e.stopPropagation();location.hash=`#/productos?code=${encodeURIComponent(x.dataset.code)}`;});}));
 const dlg=document.querySelector('#center-dialog');document.querySelector('#close-center-dialog').onclick=()=>dlg.close();document.querySelector('#cancel-center').onclick=()=>dlg.close();
 document.querySelector('#center-form').onsubmit=async e=>{e.preventDefault();const existingId=document.querySelector('#center-id').value;const code=safeId(document.querySelector('#center-code').value);const name=document.querySelector('#center-name').value.trim();if(!name||!code){toast('Nombre y código son obligatorios');return;}if(!existingId&&store.data.sites.some(s=>s.id===code||String(s.code).toUpperCase()===code)){toast('Ese código de centro ya existe');return;}await store.commit(s=>{let site=s.sites.find(x=>x.id===existingId);if(!site){site={id:code};s.sites.push(site);}site.name=name;site.code=code;site.type=document.querySelector('#center-type').value;site.notes=document.querySelector('#center-notes').value.trim();site.active=document.querySelector('#center-active').checked;},`${existingId?'Centro actualizado':'Centro creado'}: ${name}`);dlg.close();toast('Centro guardado');renderCenters(root);};
}
