import { store } from '../../services/store.js';
import { shell,wireShell,toast,notice } from '../../layout/layout.js';
import { esc,badge,empty } from '../../components/ui.js';
import { inventorySiteId,activeSiteId } from '../../services/stock.js';
import { activeCompanyId,companyName,siteCompanyId } from '../../services/company.js';
import { requireAdminSupercode } from '../../services/security.js';

function currentUser(){return store.data.users.find(u=>u.id===store.data.session.userId);}
function canAdmin(){const u=currentUser();return u?.role==='ADMIN_GLOBAL'||(u?.role==='ADMINISTRADOR'&&!(u.siteIds||[]).length);}
function siteStock(siteId){return (store.data.inventory||[]).filter(i=>inventorySiteId(i)===siteId&&Number(i.qty)>0).reduce((a,b)=>a+Number(b.qty||0),0);}
function siteSku(siteId){return new Set((store.data.inventory||[]).filter(i=>inventorySiteId(i)===siteId&&Number(i.qty)>0).map(i=>i.productCode)).size;}
function siteLocations(siteId){return (store.data.locations||[]).filter(l=>l.siteId===siteId&&l.active!==false).length;}
function typeName(v){return ({BODEGA:'Bodega / centro de distribución',TIENDA:'Tienda / sucursal',BODEGA_TIENDA:'Bodega + tienda',DEPARTAMENTO:'Departamento / área',OFICINA:'Oficina / administración',OTRO:'Otro centro'}[v]||v||'Centro');}
function siteCard(s){return `<article class="center-card-wrap">${canAdmin()?`<label class="center-select" title="Seleccionar para eliminación masiva"><input type="checkbox" class="center-select-input" value="${esc(s.id)}"><span>Seleccionar</span></label>`:''}<button class="center-card" data-site="${esc(s.id)}" type="button"><div class="center-card-head"><div><span class="eyebrow">${esc(companyName(siteCompanyId(s)))}</span><h3>${esc(s.name)}</h3><small>${esc(typeName(s.type))} · ${esc(s.code||s.id)} · Autónomo</small></div>${badge(s.active!==false?'ACTIVO':'INACTIVO',s.active!==false?'ok':'warn')}</div><div class="center-metrics"><span><b>${siteStock(s.id)}</b><small>unidades</small></span><span><b>${siteSku(s.id)}</b><small>productos</small></span><span><b>${siteLocations(s.id)}</b><small>ubicaciones</small></span></div><div class="center-card-foot">Ver ficha y organización <b>→</b></div></button></article>`;}
function detailHtml(site){
  const inv=(store.data.inventory||[]).filter(i=>inventorySiteId(i)===site.id&&Number(i.qty)>0);
  const rows=[...new Set(inv.map(i=>i.productCode))].map(code=>{const p=store.data.products.find(x=>x.code===code);const qty=inv.filter(i=>i.productCode===code).reduce((a,b)=>a+Number(b.qty||0),0);return `<tr><td><b>${esc(code)}</b></td><td>${esc(p?.name||p?.description||`Producto ${code}`)}</td><td><b>${qty}</b></td><td><button class="ghost small open-product" data-code="${esc(code)}">Ver ficha</button></td></tr>`;}).join('');
  return `<section class="panel center-detail"><div class="panel-head"><div><span class="eyebrow">${esc(companyName(siteCompanyId(site)))}</span><h2>${esc(site.name)}</h2><small>${esc(typeName(site.type))} · Código ${esc(site.code||site.id)} · Centro autónomo</small></div><div class="center-detail-actions">${canAdmin()?`<button class="secondary" id="activate-center-structure" data-site="${esc(site.id)}" type="button">Activar y configurar estructura</button><button class="secondary" id="edit-center" type="button">Editar centro</button><button class="danger-action" id="delete-center" type="button">Eliminar centro</button>`:''}<button class="ghost" id="close-center" type="button">Cerrar</button></div></div><div class="center-summary"><div><small>Stock</small><b>${siteStock(site.id)}</b></div><div><small>Productos distintos</small><b>${siteSku(site.id)}</b></div><div><small>Ubicaciones</small><b>${siteLocations(site.id)}</b></div><div><small>Estado</small><b>${site.active!==false?'Activo':'Inactivo'}</b></div></div>${site.notes?`<div class="warning-box">${esc(site.notes)}</div>`:''}<div class="table-wrap"><table><thead><tr><th>Código</th><th>Producto</th><th>Stock en este centro</th><th></th></tr></thead><tbody>${rows||`<tr><td colspan="4">${empty('Sin stock registrado','Este centro ya está creado. Cuando tenga ubicaciones o reciba inventario aparecerá aquí.')}</td></tr>`}</tbody></table></div></section>`;
}
function companyOptions(selected=''){return (store.data.companies||[]).filter(c=>c.active!==false).map(c=>`<option value="${esc(c.id)}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>`).join('');}
function dialogHtml(){return `<dialog id="center-dialog"><form id="center-form" class="dialog-card"><div class="dialog-head"><div><span class="eyebrow">CENTRO / SUCURSAL</span><h3 id="center-dialog-title">Nuevo centro</h3></div><button type="button" id="close-center-dialog" class="ghost">×</button></div><input id="center-id" type="hidden"><label>Empresa<select id="center-company" required>${companyOptions(activeCompanyId())}</select></label><label>Nombre<input id="center-name" required maxlength="100" placeholder="Ej. Sucursal Vitacura"></label><label>Código corto<input id="center-code" required maxlength="12" placeholder="Ej. VIT"></label><label>Tipo<select id="center-type"><option value="BODEGA">Bodega / centro de distribución</option><option value="TIENDA">Tienda / sucursal</option><option value="BODEGA_TIENDA">Bodega + tienda</option><option value="DEPARTAMENTO">Departamento / área</option><option value="OFICINA">Oficina / administración</option><option value="OTRO">Otro centro</option></select></label><label>Notas<textarea id="center-notes" rows="2" maxlength="240" placeholder="Opcional"></textarea></label><label class="toggle-line"><input id="center-active" type="checkbox" checked> Centro activo</label><div class="warning-box">Los centros son autónomos. No existe dependencia padre-hijo: los pedidos y traspasos se realizan entre cualquier par de centros autorizados.</div><div class="dialog-actions"><button type="button" id="cancel-center" class="ghost">Cancelar</button><button class="primary" type="submit">Guardar centro</button></div></form></dialog>
<dialog id="company-dialog"><form id="company-form" class="dialog-card"><div class="dialog-head"><div><span class="eyebrow">MULTIEMPRESA</span><h3>Nueva empresa</h3></div><button type="button" id="close-company-dialog" class="ghost">×</button></div><label>Nombre<input id="company-name" required maxlength="100" placeholder="Ej. Serco MKP"></label><label>Código<input id="company-code" required maxlength="20" placeholder="Ej. SERCO_MKP"></label><label>Notas<textarea id="company-notes" rows="2" maxlength="240"></textarea></label><div class="warning-box">Cada empresa mantiene sus centros, stock operativo, usuarios autorizados y futura conexión ERP separados.</div><div class="dialog-actions"><button type="button" id="cancel-company" class="ghost">Cancelar</button><button class="primary" type="submit">Crear empresa</button></div></form></dialog>`;}
function openDialog(site=null){const dlg=document.querySelector('#center-dialog');document.querySelector('#center-dialog-title').textContent=site?'Editar centro':'Nuevo centro';document.querySelector('#center-id').value=site?.id||'';document.querySelector('#center-name').value=site?.name||'';document.querySelector('#center-code').value=site?.code||'';document.querySelector('#center-code').disabled=Boolean(site);document.querySelector('#center-company').innerHTML=companyOptions(site?siteCompanyId(site):activeCompanyId());document.querySelector('#center-company').disabled=Boolean(site&&siteStock(site.id)>0);document.querySelector('#center-type').value=site?.type||'TIENDA';document.querySelector('#center-notes').value=site?.notes||'';document.querySelector('#center-active').checked=site?.active!==false;dlg.showModal();}
function safeId(code,max=20){return String(code||'').trim().toUpperCase().replace(/[^A-Z0-9_]/g,'_').replace(/_+/g,'_').replace(/^_|_$/g,'').slice(0,max);}
function deletionBlockers(siteId){
  const d=store.data,out=[];const stock=siteStock(siteId);if(stock>0)out.push(`${stock} unidades de stock`);
  const racks=(d.racks||[]).filter(r=>r.siteId===siteId).length;if(racks)out.push(`${racks} rack(s)`);
  const locations=(d.locations||[]).filter(l=>l.siteId===siteId).length;if(locations)out.push(`${locations} ubicación(es)`);
  const pallets=(d.pallets||[]).filter(p=>p.siteId===siteId&&p.status!=='CERRADO').length;if(pallets)out.push(`${pallets} pallet(s) activo(s)`);
  const users=(d.users||[]).filter(u=>(u.siteIds||[]).includes(siteId)).length;if(users)out.push(`${users} usuario(s) asignado(s)`);
  const transfers=(d.transfers||[]).filter(t=>[t.siteId,t.sourceSiteId,t.destinationSiteId].includes(siteId)).length;if(transfers)out.push(`${transfers} transferencia(s)`);
  const orders=(d.orders||[]).filter(o=>[o.siteId,o.sourceSiteId,o.destinationSiteId,o.requestSiteId,o.requestingSiteId].includes(siteId)).length;if(orders)out.push(`${orders} orden(es)`);
  if(siteId===activeSiteId(d))out.push('es el centro operativo activo');if((d.sites||[]).length<=1)out.push('es el único centro del WMS');return out;
}
async function deleteSites(ids,root){const unique=[...new Set(ids)].filter(Boolean),selected=unique.map(id=>store.data.sites.find(s=>s.id===id)).filter(Boolean);if(!selected.length){toast('Selecciona al menos un centro para eliminar','warning');return;}const blocked=selected.map(s=>({s,reasons:deletionBlockers(s.id)})).filter(x=>x.reasons.length);if(blocked.length){await notice('No se puede eliminar',`${blocked[0].s.name}: ${blocked[0].reasons.join(', ')}. Vacía o reasigna primero esos elementos.`,'warning');return;}const label=selected.length===1?selected[0].name:`${selected.length} centros seleccionados`;const ok=await requireAdminSupercode(`Vas a eliminar ${label}. Ingresa tu supercódigo.`);if(!ok)return;if(!confirm(`¿Confirmas eliminar ${label}?`))return;await store.commit(d=>{const set=new Set(unique);d.sites=d.sites.filter(s=>!set.has(s.id));},`${label} eliminado(s) por administrador`);renderCenters(root);await notice('Eliminación realizada',`${label} se eliminó correctamente.`,'success');}

export function renderCenters(root){
 const allowed=canAdmin(),companies=store.data.companies||[],sites=store.data.sites||[];
 const body=`<div class="page-intro"><div><span class="eyebrow">MULTIEMPRESA · MULTICENTRO</span><h2>Empresas, centros y sucursales</h2><p>Cada empresa es independiente y cada centro es autónomo. Las relaciones se realizan mediante pedidos y traspasos.</p></div>${allowed?'<div class="dialog-actions"><button id="new-company" class="secondary" type="button">+ Nueva empresa</button><button id="new-center" class="primary" type="button">+ Nuevo centro / sucursal</button></div>':''}</div><section class="panel"><div class="panel-head"><div><h3>Empresas</h3><small>${companies.length} empresa(s) configuradas</small></div></div><div class="stock-site-summary">${companies.map(c=>`<span class="${c.id===activeCompanyId()?'active':''}"><small>Empresa</small><b>${esc(c.name)}</b><strong>${sites.filter(s=>siteCompanyId(s)===c.id).length} centro(s)</strong></span>`).join('')}</div></section>${allowed?'<div class="center-bulk-bar"><div><b>Eliminación administrativa</b><small>Solo se eliminan centros vacíos y sin relaciones activas.</small></div><button id="delete-selected-centers" class="danger-action" type="button" disabled>Eliminar seleccionados</button></div>':''}<div class="centers-grid">${sites.map(siteCard).join('')||empty('No hay centros registrados','Crea el primer centro para comenzar.')}</div><div id="center-detail-slot"></div>${dialogHtml()}`;
 root.innerHTML=shell('Centros y Sucursales',body,'centros');wireShell();
 document.querySelector('#new-center')?.addEventListener('click',()=>openDialog());const companyDlg=document.querySelector('#company-dialog');document.querySelector('#new-company')?.addEventListener('click',()=>companyDlg.showModal());document.querySelector('#close-company-dialog')?.addEventListener('click',()=>companyDlg.close());document.querySelector('#cancel-company')?.addEventListener('click',()=>companyDlg.close());
 document.querySelector('#company-form')?.addEventListener('submit',async e=>{e.preventDefault();const name=document.querySelector('#company-name').value.trim(),id=safeId(document.querySelector('#company-code').value);if(!name||!id){toast('Nombre y código son obligatorios','warning');return;}if(companies.some(c=>c.id===id)){toast('Ese código de empresa ya existe','warning');return;}await store.commit(d=>d.companies.push({id,name,code:id,active:true,notes:document.querySelector('#company-notes').value.trim()}),`Empresa creada: ${name}`);companyDlg.close();renderCenters(root);await notice('Empresa creada',`${name} quedó disponible para crear sus centros.`,'success');});
 const updateBulk=()=>{const b=document.querySelector('#delete-selected-centers');if(b)b.disabled=!document.querySelectorAll('.center-select-input:checked').length;};document.querySelectorAll('.center-select-input').forEach(c=>c.addEventListener('change',updateBulk));document.querySelector('#delete-selected-centers')?.addEventListener('click',()=>deleteSites([...document.querySelectorAll('.center-select-input:checked')].map(c=>c.value),root));
 document.querySelectorAll('.center-card').forEach(b=>b.addEventListener('click',()=>{const site=store.data.sites.find(s=>s.id===b.dataset.site);if(!site)return;const slot=document.querySelector('#center-detail-slot');slot.innerHTML=detailHtml(site);slot.scrollIntoView({behavior:'smooth',block:'start'});document.querySelector('#close-center').onclick=()=>slot.innerHTML='';document.querySelector('#activate-center-structure')?.addEventListener('click',()=>{localStorage.setItem('serco_wms_active_company',siteCompanyId(site));localStorage.setItem('serco_wms_active_site',site.id);location.hash='#/estructura';location.reload();});document.querySelector('#edit-center')?.addEventListener('click',()=>openDialog(site));document.querySelector('#delete-center')?.addEventListener('click',()=>deleteSites([site.id],root));document.querySelectorAll('.open-product').forEach(x=>x.onclick=e=>{e.stopPropagation();location.hash=`#/productos?code=${encodeURIComponent(x.dataset.code)}`;});}));
 const dlg=document.querySelector('#center-dialog');document.querySelector('#close-center-dialog').onclick=()=>dlg.close();document.querySelector('#cancel-center').onclick=()=>dlg.close();document.querySelector('#center-form').onsubmit=async e=>{e.preventDefault();const existingId=document.querySelector('#center-id').value,code=safeId(document.querySelector('#center-code').value,12),name=document.querySelector('#center-name').value.trim(),companyId=document.querySelector('#center-company').value;if(!name||!code||!companyId){toast('Empresa, nombre y código son obligatorios','warning');return;}if(!existingId&&sites.some(s=>s.id===code||String(s.code||'').toUpperCase()===code)){toast('Ese código de centro ya existe','warning');return;}try{await store.commit(s=>{let site=s.sites.find(x=>x.id===existingId);if(!site){site={id:code};s.sites.push(site);}site.companyId=companyId;site.name=name;site.code=site.code||code;site.type=document.querySelector('#center-type').value;delete site.parentSiteId;site.notes=document.querySelector('#center-notes').value.trim();site.active=document.querySelector('#center-active').checked;},`${existingId?'Centro actualizado':'Centro creado'}: ${name}`);dlg.close();renderCenters(root);await notice(existingId?'Centro actualizado':'Centro creado',`${name} se guardó como centro autónomo.`,'success');}catch(err){console.error(err);await notice('No se pudo guardar',err.message||'Error al guardar el centro.','error');}};
}
