import { store } from '../../services/store.js';
import { shell,wireShell,toast } from '../../layout/layout.js';
import { esc,badge,empty } from '../../components/ui.js';
import { inventorySiteId } from '../../services/stock.js';

function currentUser(){return store.data.users.find(u=>u.id===store.data.session.userId);}
function canAdmin(){return currentUser()?.role==='ADMINISTRADOR';}
function siteStock(siteId){return (store.data.inventory||[]).filter(i=>inventorySiteId(i)===siteId&&Number(i.qty)>0).reduce((a,b)=>a+Number(b.qty||0),0);}
function siteSku(siteId){return new Set((store.data.inventory||[]).filter(i=>inventorySiteId(i)===siteId&&Number(i.qty)>0).map(i=>i.productCode)).size;}
function siteLocations(siteId){return (store.data.locations||[]).filter(l=>l.siteId===siteId&&l.active!==false).length;}
function typeName(v){return ({BODEGA:'Bodega / centro de distribución',TIENDA:'Tienda / sucursal',BODEGA_TIENDA:'Bodega + tienda',DEPARTAMENTO:'Departamento / área',OFICINA:'Oficina / administración',OTRO:'Otro centro'}[v]||v||'Centro');}
function parentName(site){const p=(store.data.sites||[]).find(x=>x.id===site.parentSiteId);return p?.name||'';}
function siteCard(s){const parent=parentName(s);return `<button class="center-card" data-site="${esc(s.id)}" type="button"><div class="center-card-head"><div><span class="eyebrow">${esc(typeName(s.type))}</span><h3>${esc(s.name)}</h3><small>${esc(s.code||s.id)}${parent?` · Depende de ${esc(parent)}`:''}</small></div>${badge(s.active!==false?'ACTIVO':'INACTIVO',s.active!==false?'ok':'warn')}</div><div class="center-metrics"><span><b>${siteStock(s.id)}</b><small>unidades</small></span><span><b>${siteSku(s.id)}</b><small>productos</small></span><span><b>${siteLocations(s.id)}</b><small>ubicaciones</small></span></div><div class="center-card-foot">Ver ficha y organización <b>→</b></div></button>`;}
function detailHtml(site){
  const inv=(store.data.inventory||[]).filter(i=>inventorySiteId(i)===site.id&&Number(i.qty)>0);
  const rows=[...new Set(inv.map(i=>i.productCode))].map(code=>{const p=store.data.products.find(x=>x.code===code);const qty=inv.filter(i=>i.productCode===code).reduce((a,b)=>a+Number(b.qty||0),0);return `<tr class="click-row" data-product="${esc(code)}"><td><b>${esc(code)}</b></td><td>${esc(p?.name||p?.description||`Producto ${code}`)}</td><td><b>${qty}</b></td><td><button class="ghost small open-product" data-code="${esc(code)}">Ver ficha</button></td></tr>`;}).join('');
  const parent=parentName(site);
  return `<section class="panel center-detail"><div class="panel-head"><div><span class="eyebrow">FICHA DEL CENTRO</span><h2>${esc(site.name)}</h2><small>${esc(typeName(site.type))} · Código ${esc(site.code||site.id)}${parent?` · Depende de ${esc(parent)}`:''}</small></div><div class="center-detail-actions">${canAdmin()?`<a class="secondary" href="#/estructura?site=${encodeURIComponent(site.id)}">Configurar estructura</a><button class="secondary" id="edit-center" type="button">Editar centro</button>`:''}<button class="ghost" id="close-center" type="button">Cerrar</button></div></div><div class="center-summary"><div><small>Stock</small><b>${siteStock(site.id)}</b></div><div><small>Productos distintos</small><b>${siteSku(site.id)}</b></div><div><small>Ubicaciones</small><b>${siteLocations(site.id)}</b></div><div><small>Estado</small><b>${site.active!==false?'Activo':'Inactivo'}</b></div></div>${site.notes?`<div class="warning-box">${esc(site.notes)}</div>`:''}<div class="table-wrap"><table><thead><tr><th>Código</th><th>Producto</th><th>Stock en este centro</th><th></th></tr></thead><tbody>${rows||`<tr><td colspan="4">${empty('Sin stock registrado','Este centro ya está creado. Cuando tenga ubicaciones o reciba inventario aparecerá aquí.')}</td></tr>`}</tbody></table></div></section>`;
}
function parentOptions(currentId=''){return `<option value="">Sin dependencia / centro principal</option>${(store.data.sites||[]).filter(s=>s.id!==currentId).map(s=>`<option value="${esc(s.id)}">${esc(s.name)} (${esc(s.code||s.id)})</option>`).join('')}`;}
function dialogHtml(){return `<dialog id="center-dialog"><form id="center-form" class="dialog-card"><div class="dialog-head"><div><span class="eyebrow">CENTRO / SUCURSAL</span><h3 id="center-dialog-title">Nuevo centro</h3></div><button type="button" id="close-center-dialog" class="ghost">×</button></div><input id="center-id" type="hidden"><label>Nombre<input id="center-name" required maxlength="100" placeholder="Ej. Sucursal Vitacura"></label><label>Código corto<input id="center-code" required maxlength="12" placeholder="Ej. VIT"></label><label>Tipo<select id="center-type"><option value="BODEGA">Bodega / centro de distribución</option><option value="TIENDA">Tienda / sucursal</option><option value="BODEGA_TIENDA">Bodega + tienda</option><option value="DEPARTAMENTO">Departamento / área</option><option value="OFICINA">Oficina / administración</option><option value="OTRO">Otro centro</option></select></label><label>Depende de<select id="center-parent"></select><small class="field-help">Opcional. Permite organizar, por ejemplo, un departamento dentro de una sucursal.</small></label><label>Notas<textarea id="center-notes" rows="2" maxlength="240" placeholder="Opcional"></textarea></label><label class="toggle-line"><input id="center-active" type="checkbox" checked> Centro activo</label><div class="warning-box">Cada centro queda identificado por un código único y puede tener stock, ubicaciones y estructura propios. Esto deja preparada la base para transferencias entre bodegas y sucursales.</div><div class="dialog-actions"><button type="button" id="cancel-center" class="ghost">Cancelar</button><button class="primary" type="submit">Guardar centro</button></div></form></dialog>`;}
function openDialog(site=null){const dlg=document.querySelector('#center-dialog');document.querySelector('#center-dialog-title').textContent=site?'Editar centro':'Nuevo centro';document.querySelector('#center-id').value=site?.id||'';document.querySelector('#center-name').value=site?.name||'';document.querySelector('#center-code').value=site?.code||'';document.querySelector('#center-code').disabled=Boolean(site);document.querySelector('#center-type').value=site?.type||'TIENDA';const parent=document.querySelector('#center-parent');parent.innerHTML=parentOptions(site?.id||'');parent.value=site?.parentSiteId||'';document.querySelector('#center-notes').value=site?.notes||'';document.querySelector('#center-active').checked=site?.active!==false;dlg.showModal();}
function safeId(code){return String(code||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,12);}
function hasParentCycle(siteId,parentId){if(!siteId||!parentId)return false;let cursor=parentId;const seen=new Set();while(cursor){if(cursor===siteId)return true;if(seen.has(cursor))return true;seen.add(cursor);cursor=(store.data.sites||[]).find(s=>s.id===cursor)?.parentSiteId||'';}return false;}
export function renderCenters(root){
 const allowed=canAdmin(); const sites=store.data.sites||[]; const body=`<div class="page-intro"><div><span class="eyebrow">MULTICENTRO</span><h2>Centros y sucursales</h2><p>Administra bodegas, tiendas, sucursales y áreas. Cada una puede tener stock y estructura propios dentro del mismo WMS.</p></div>${allowed?'<button id="new-center" class="primary" type="button">+ Nuevo centro / sucursal</button>':''}</div><div class="centers-grid">${sites.map(siteCard).join('')||empty('No hay centros registrados','Crea el primer centro para comenzar.')}</div><div id="center-detail-slot"></div>${dialogHtml()}`;
 root.innerHTML=shell('Centros y Sucursales',body,'centros');wireShell();
 document.querySelector('#new-center')?.addEventListener('click',()=>openDialog());
 document.querySelectorAll('.center-card').forEach(b=>b.addEventListener('click',()=>{const site=store.data.sites.find(s=>s.id===b.dataset.site);if(!site)return;const slot=document.querySelector('#center-detail-slot');slot.innerHTML=detailHtml(site);slot.scrollIntoView({behavior:'smooth',block:'start'});document.querySelector('#close-center').onclick=()=>slot.innerHTML='';document.querySelector('#edit-center')?.addEventListener('click',()=>openDialog(site));document.querySelectorAll('.open-product').forEach(x=>x.onclick=e=>{e.stopPropagation();location.hash=`#/productos?code=${encodeURIComponent(x.dataset.code)}`;});}));
 const dlg=document.querySelector('#center-dialog');document.querySelector('#close-center-dialog').onclick=()=>dlg.close();document.querySelector('#cancel-center').onclick=()=>dlg.close();
 document.querySelector('#center-form').onsubmit=async e=>{e.preventDefault();const existingId=document.querySelector('#center-id').value;const rawCode=document.querySelector('#center-code').value;const code=safeId(rawCode);const name=document.querySelector('#center-name').value.trim();const parentSiteId=document.querySelector('#center-parent').value||null;if(!name||!code){toast('Nombre y código son obligatorios');return;}if(!existingId&&sites.some(s=>s.id===code||String(s.code||'').toUpperCase()===code)){toast('Ese código de centro ya existe');return;}if(hasParentCycle(existingId,parentSiteId)){toast('No se puede crear una dependencia circular entre centros');return;}try{await store.commit(s=>{let site=s.sites.find(x=>x.id===existingId);if(!site){site={id:code};s.sites.push(site);}site.name=name;site.code=site.code||code;site.type=document.querySelector('#center-type').value;site.parentSiteId=parentSiteId;site.notes=document.querySelector('#center-notes').value.trim();site.active=document.querySelector('#center-active').checked;},`${existingId?'Centro actualizado':'Centro creado'}: ${name}`);dlg.close();renderCenters(root);toast(`${existingId?'Centro actualizado':'Centro creado'} correctamente`);}catch(err){console.error(err);toast(`No se pudo guardar el centro: ${err.message||'error inesperado'}`);}};
}
