import { store } from '../../services/store.js';
import { shell,wireShell,toast } from '../../layout/layout.js';
import { esc,badge } from '../../components/ui.js';
import { FORMATO_UBICACION_PREDETERMINADO, recalcularCodigosEscaneables, vistaCodigoUbicacion } from '../../services/ubicaciones.js';

function rackRows(){const d=store.data;return d.racks.map(r=>`<div class="structure-row"><div><b>${esc(r.name)}</b><small>${esc(r.sectorId==='REC-A'?'Sector amplio':'Sector nuevo')}</small></div><div>${r.modules??'—'}</div><div>${r.levels??'—'}</div><div>${d.locations.filter(l=>l.rackId===r.id&&l.active).length}</div><div>${badge(r.status.replace('_',' '),r.status==='ACTIVO'?'ok':'warn')}</div><button class="ghost edit-rack" data-id="${r.id}">Editar</button></div>`).join('')}
function previewCodigo(){const demo={siteId:'REC',rackId:'R6',module:3,level:4,id:'REC-R6-M3-N4',scanCode:''};const datos={...store.data,settings:{...(store.data.settings||{}),locationCodeFormat:document.querySelector('#location-format')?.value||FORMATO_UBICACION_PREDETERMINADO}};return vistaCodigoUbicacion(demo,datos);}

export function renderStructure(root){
  const formato=store.data.settings?.locationCodeFormat||FORMATO_UBICACION_PREDETERMINADO;
  root.innerHTML=shell('Estructura',`<div class="page-intro"><div><span class="eyebrow">ESTRUCTURA EDITABLE</span><h2>La bodega puede cambiar sin perder historia</h2><p>Crear o ampliar racks, módulos y niveles no modifica los movimientos anteriores. Las ubicaciones antiguas pueden quedar inactivas en lugar de borrarse.</p></div></div>
  <section class="panel"><div class="panel-head"><div><h3>Códigos físicos de ubicación</h3><small>El ID interno no cambia aunque modifiques el formato impreso/escaneable.</small></div></div><div class="form-grid location-code-config"><label>Formato del código<input id="location-format" value="${esc(formato)}"><small>Variables: {SEDE}, {RACK}, {MODULO}, {NIVEL}</small></label><div class="code-preview"><small>Vista previa</small><b id="location-preview">REC-R6-M3-N4</b></div></div><div class="dialog-actions"><button id="reset-location-format" class="ghost">Usar formato recomendado</button><button id="save-location-format" class="primary">Guardar formato</button></div><div class="warning-box">Cada posición conserva un ID interno estable. El código escaneable puede cambiar sin romper productos, movimientos ni historial.</div></section>
  <section class="panel"><div class="panel-head"><div><h3>Recoleta · racks</h3><small>Convención actual: REC-R(Rack)-M(Módulo)-N(Nivel)</small></div><button id="new-rack" class="primary">+ Nuevo rack</button></div><div class="structure-table"><div class="structure-row head"><div>Rack</div><div>Módulos</div><div>Niveles</div><div>Ubic.</div><div>Estado</div><div></div></div>${rackRows()}</div></section><div class="callout"><b>R6–R9: 144 posiciones configuradas actualmente</b><span>Cada rack tiene 6 módulos × 6 niveles = 36 posiciones. Si agregan repisas, módulos, niveles o racks, se actualiza desde aquí sin borrar el historial.</span></div>
  <dialog id="rack-dialog"><form method="dialog" id="rack-form"><div class="dialog-head"><h3>Configurar rack</h3><button value="cancel" class="ghost">×</button></div><input type="hidden" id="rack-id"><label>Nombre<input id="rack-name" required></label><div class="form-grid"><label>Módulos<input id="rack-modules" type="number" min="1" max="100" required></label><label>Niveles<input id="rack-levels" type="number" min="1" max="20" required></label></div><label>Uso / descripción<input id="rack-usage"></label><label>Estado<select id="rack-status"><option>ACTIVO</option><option>EN_CONSTRUCCION</option><option>INACTIVO</option></select></label><div class="warning-box">Al guardar, el sistema generará las ubicaciones faltantes. Las ubicaciones existentes no se eliminan automáticamente.</div><div class="dialog-actions"><button value="cancel" class="ghost">Cancelar</button><button value="default" id="save-rack" class="primary">Guardar y generar</button></div></form></dialog>`,'estructura');wireShell();
  const fmt=document.querySelector('#location-format'),prev=document.querySelector('#location-preview');const repintaPrev=()=>prev.textContent=previewCodigo();repintaPrev();fmt.oninput=repintaPrev;
  document.querySelector('#reset-location-format').onclick=()=>{fmt.value=FORMATO_UBICACION_PREDETERMINADO;repintaPrev();};
  document.querySelector('#save-location-format').onclick=async()=>{const value=fmt.value.trim();if(!value.includes('{RACK}')||!value.includes('{MODULO}')||!value.includes('{NIVEL}')){toast('El formato debe incluir RACK, MODULO y NIVEL');return;}let conflictos=[];await store.commit(d=>{d.settings=d.settings||{};d.settings.locationCodeFormat=value;conflictos=recalcularCodigosEscaneables(d);},'Formato de códigos físicos de ubicación actualizado');toast(conflictos.length?`Guardado con ${conflictos.length} código(s) repetido(s). Revisa el formato.`:'Formato de ubicación actualizado');renderStructure(root);};
  const dlg=document.querySelector('#rack-dialog'); const open=(r)=>{document.querySelector('#rack-id').value=r?.id||'';document.querySelector('#rack-name').value=r?.name||'';document.querySelector('#rack-modules').value=r?.modules||'';document.querySelector('#rack-levels').value=r?.levels||'';document.querySelector('#rack-usage').value=r?.usage||'';document.querySelector('#rack-status').value=r?.status||'ACTIVO';dlg.showModal();};
  document.querySelector('#new-rack').onclick=()=>open(null); document.querySelectorAll('.edit-rack').forEach(b=>b.onclick=()=>open(store.data.racks.find(r=>r.id===b.dataset.id)));
  document.querySelector('#save-rack').onclick=async(e)=>{e.preventDefault(); const oldId=document.querySelector('#rack-id').value; let id=oldId; if(!id){const nums=store.data.racks.map(r=>Number(r.id.replace('R',''))||0);id=`R${Math.max(...nums)+1}`;} const modules=Number(document.querySelector('#rack-modules').value),levels=Number(document.querySelector('#rack-levels').value); if(!modules||!levels)return; await store.commit(d=>{let r=d.racks.find(x=>x.id===id); if(!r){r={id,siteId:'REC',sectorId:'REC-B'};d.racks.push(r);} Object.assign(r,{name:document.querySelector('#rack-name').value||`Rack ${id.replace('R','')}`,modules,levels,status:document.querySelector('#rack-status').value,usage:document.querySelector('#rack-usage').value,plannedSlots:modules*levels,notes:r.notes||''}); for(let m=1;m<=modules;m++)for(let n=1;n<=levels;n++){const lid=`REC-${id}-M${m}-N${n}`;if(!d.locations.some(l=>l.id===lid))d.locations.push({id:lid,siteId:'REC',rackId:id,module:m,level:n,label:lid,status:'LIBRE',access:n===1?'DIRECTO':'YALE',kind:Number(id.replace('R',''))>=6?'PICKING_RACK':'RACK',active:true,capacity:Number(id.replace('R',''))>=6?1:null,notes:''});}recalcularCodigosEscaneables(d);},`Estructura de ${id} actualizada`);dlg.close();toast('Rack actualizado');renderStructure(root);};
}
