import { store } from '../../services/store.js';
import { shell, wireShell, toast, notice } from '../../layout/layout.js';
import { esc, empty } from '../../components/ui.js';
import { crearEscaner } from '../../services/escaner.js';
import { buscarUbicacionPorCodigo, vistaCodigoUbicacion } from '../../services/ubicaciones.js';
import { deductStock, addStock, productPositions } from '../../services/inventory-ops.js';
import { resolveProduct,productAliases } from '../../services/product-codes.js';
import { openProductEditor } from '../../services/product-editor.js';
import { activeSiteId,inventorySiteId } from '../../services/stock.js';
import { assignProductToPallet, canReceiveWholePallet, editPalletDisplayName, moveProductToPallet, moveWholePallet, palletDisplayName, registerPermanentPallet } from '../../services/pallet-ops.js';
import { palletPermissionsForUser } from '../../services/access-routing.js';

function params(){ return new URLSearchParams(location.hash.split('?')[1]||''); }
function producto(code){ return resolveProduct(code); }
function normalizar(v=''){ return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(); }
function contenidoPalet(id){ const site=activeSiteId(); return store.data.inventory.filter(i=>i.palletId===id && i.qty>0 && inventorySiteId(i)===site); }
function totalUnidades(id){ return contenidoPalet(id).reduce((a,b)=>a+b.qty,0); }
function totalSku(id){ return new Set(contenidoPalet(id).map(i=>i.productCode)).size; }
function usuario(id){ return store.data.users.find(u=>u.id===id)?.name || id || 'No registrado'; }
function recepcionPalet(id){ const site=activeSiteId(); return store.data.receipts.find(r=>r.siteId===site&&r.palletId===id); }
function ocupado(locationId){ const site=activeSiteId(); return store.data.inventory.some(i=>i.locationId===locationId && i.qty>0 && inventorySiteId(i)===site); }
function nombrePalet(p){return palletDisplayName(p);}
function categoriaPalet(p){if(p.status==='VACÍO'||totalUnidades(p.id)===0)return 'VACÍO';if(p.status==='UBICADO')return 'UBICADO';if(['POR_UBICAR','RECIBIENDO'].includes(p.status))return 'POR_UBICAR';return 'OTRO';}
function usuarioActual(){return store.data.users.find(x=>x.id===store.data.session.userId);}
function permisosPalets(){return palletPermissionsForUser(usuarioActual(),activeSiteId(store.data));}
function puedeRegistrarPalet(){return permisosPalets().register;}
function setInputModeButton(button,numeric=false){if(!button)return;button.innerHTML=`<span class="numeric-mode-icon">⌨</span><span>${numeric?'ABC':'123'}</span>`;button.title=numeric?'Usar teclado completo':'Usar teclado numérico';button.setAttribute('aria-label',button.title);button.classList.toggle('is-numeric',numeric);}
function wireInputModeToggle(button,input){if(!button||!input)return;setInputModeButton(button,input.inputMode==='numeric');button.onclick=()=>{const numeric=input.inputMode!=='numeric',value=input.value;input.blur();input.inputMode=numeric?'numeric':'text';setInputModeButton(button,numeric);input.value=value;setTimeout(()=>input.focus(),20);};}
function buscarProductosTexto(value,limit=8){const q=normalizar(value);if(!q)return[];return (store.data.products||[]).filter(p=>{const aliases=productAliases(p).join(' ');return normalizar(`${p.code||''} ${p.name||''} ${p.description||''} ${p.family||''} ${aliases}`).includes(q);}).slice(0,limit);}
function buscarPallet(value,excludeId=''){const q=normalizar(value),compact=normalizar(value).replace(/[^a-z0-9]/g,'');if(!q)return null;return (store.data.pallets||[]).find(p=>p.siteId===activeSiteId()&&p.id!==excludeId&&p.status!=='CERRADO'&&[p.id,p.physicalCode,nombrePalet(p)].some(v=>{const n=normalizar(v),c=n.replace(/[^a-z0-9]/g,'');return n===q||c===compact;}));}
function palletsDestinoOptions(excludeId=''){return (store.data.pallets||[]).filter(p=>p.siteId===activeSiteId()&&p.id!==excludeId&&p.status!=='CERRADO').sort((a,b)=>nombrePalet(a).localeCompare(nombrePalet(b),undefined,{numeric:true})).map(p=>`<option value="${esc(p.id)}">${esc(nombrePalet(p))} · ${esc(p.physicalCode||p.id)} · ${esc(p.locationId||'Sin ubicación')}</option>`).join('');}

function existentes(code, palletId){
  const map=new Map();
  const site=activeSiteId();
  store.data.inventory.filter(i=>i.productCode===code && i.qty>0 && i.palletId!==palletId && inventorySiteId(i)===site).forEach(i=>{
    const key=`${i.locationId}@@${i.palletId||''}`;
    const prev=map.get(key)||{locationId:i.locationId,palletId:i.palletId||null,qty:0};
    prev.qty+=i.qty; map.set(key,prev);
  });
  return [...map.values()];
}
function libresRapidas(limit=10){
  const site=activeSiteId();
  return store.data.locations.filter(l=>l.siteId===site && l.active && l.kind==='PICKING_RACK' && !ocupado(l.id) && l.status!=='BLOQUEADA' && l.status!=='INHABILITADA')
    .sort((a,b)=>a.id.localeCompare(b.id,undefined,{numeric:true})).slice(0,limit);
}
function recomendaciones(code,palletId){ return {ya:existentes(code,palletId),rapidas:libresRapidas(8)}; }

function opcionesDestino(code,palletId){
  const {ya,rapidas}=recomendaciones(code,palletId), vistos=new Set(), out=[];
  ya.forEach(x=>{const key=`${x.locationId}@@${x.palletId||''}`;if(!vistos.has(key)){vistos.add(key);out.push(`<option value="${esc(key)}">Reponer existente · ${x.palletId?`Palet ${esc(x.palletId)} · `:''}${esc(x.locationId)} · ${x.qty} un.</option>`);}});
  rapidas.forEach(l=>{const key=`${l.id}@@`;if(!vistos.has(key)){vistos.add(key);out.push(`<option value="${esc(key)}">Posición rápida libre · ${esc(vistaCodigoUbicacion(l,store.data))}</option>`);}});
  store.data.locations.filter(l=>l.siteId===activeSiteId() && l.active && l.kind==='RACK' && !ocupado(l.id)).slice(0,12).forEach(l=>{const key=`${l.id}@@`;if(!vistos.has(key)){vistos.add(key);out.push(`<option value="${esc(key)}">Posición libre · ${esc(vistaCodigoUbicacion(l,store.data))}</option>`);}});
  return out.join('');
}


function destinoPaletDisponible(palletId,location){
  const site=activeSiteId(),pallet=store.data.pallets.find(p=>p.id===palletId&&p.siteId===site);
  if(!location||location.siteId!==site||!location.active||location.id===pallet?.locationId||!canReceiveWholePallet(location)||['BLOQUEADA','INHABILITADA'].includes(location.status))return false;
  if(['POR_UBICAR','RECEPCION_TRANSFERENCIA'].includes(location.kind))return true;
  const otroPalet=(store.data.pallets||[]).some(p=>p.id!==palletId&&p.siteId===site&&p.locationId===location.id&&p.status!=='CERRADO');
  const otroStock=(store.data.inventory||[]).some(i=>i.locationId===location.id&&i.palletId!==palletId&&Number(i.qty)>0&&inventorySiteId(i)===site);
  return !otroPalet&&!otroStock;
}
function opcionesMoverPalet(palletId){
  const site=activeSiteId(),pallet=store.data.pallets.find(p=>p.id===palletId&&p.siteId===site);
  return store.data.locations.filter(l=>l.siteId===site&&l.id!==pallet?.locationId&&canReceiveWholePallet(l)&&!['BLOQUEADA','INHABILITADA'].includes(l.status))
    .sort((a,b)=>{const pa=['POR_UBICAR','RECEPCION_TRANSFERENCIA'].includes(a.kind)?0:1,pb=['POR_UBICAR','RECEPCION_TRANSFERENCIA'].includes(b.kind)?0:1;return pa-pb||String(a.id).localeCompare(String(b.id),undefined,{numeric:true});})
    .map(l=>`<option value="${esc(l.id)}">${['POR_UBICAR','RECEPCION_TRANSFERENCIA'].includes(l.kind)?'Zona temporal':'Posición'} · ${esc(l.label||vistaCodigoUbicacion(l,store.data))} · ${esc(l.id)}</option>`).join('');
}
function rackCode(r){return r.rackCode||(/^R\d+$/.test(r.id)?r.id:String(r.id).split('-').pop());}
function defaultLevelPositions(r,level){const rn=Number(String(rackCode(r)).replace(/\D/g,''))||0;return r.siteId==='REC'&&rn>=1&&rn<=5&&(level===2||level===3)?['A','B']:[''];}
function levelPositions(r,level,module){const moduleConfigured=r.moduleLevelPositions?.[String(module)]?.[String(level)];if(Array.isArray(moduleConfigured)&&moduleConfigured.length)return moduleConfigured;const configured=r.levelPositions?.[String(level)];return Array.isArray(configured)&&configured.length?configured:defaultLevelPositions(r,level);}
function positionId(r,module,level,position=''){const base=`${r.siteId}-${rackCode(r)}-M${module}-N${level}`;return position?`${base}-${position}`:base;}
function mapaDestinoPaletHtml(palletId){
  const site=activeSiteId(),siteData=store.data.sites.find(s=>s.id===site),racks=store.data.racks.filter(r=>r.siteId===site&&r.status!=='INACTIVO').sort((a,b)=>String(a.name||a.id).localeCompare(String(b.name||b.id),undefined,{numeric:true}));
  const rackHtml=racks.map(r=>{const mods=Array.from({length:Number(r.modules||0)},(_,i)=>i+1),levels=Array.from({length:Number(r.levels||0)},(_,i)=>Number(r.levels)-i);return `<section class="pallet-map-rack"><div class="pallet-map-rack-head"><div><b>${esc(r.name||r.id)}</b><small>${esc(r.usage||'Selecciona una posición')}</small></div></div><div class="rack-ab-grid">${mods.map(m=>`<div class="rack-module-map"><div class="rack-module-head"><b>Módulo ${m}</b></div>${levels.map(n=>`<div class="rack-level-map"><span>Nivel ${n}</span><div class="rack-position-list">${levelPositions(r,n,m).map(pos=>{const id=positionId(r,m,n,pos),loc=store.data.locations.find(l=>l.id===id),pal=(store.data.pallets||[]).find(x=>x.id!==palletId&&x.siteId===site&&x.locationId===id&&x.status!=='CERRADO'),qty=(store.data.inventory||[]).filter(i=>i.locationId===id&&i.palletId!==palletId&&Number(i.qty)>0&&inventorySiteId(i)===site).reduce((a,b)=>a+Number(b.qty||0),0),ok=destinoPaletDisponible(palletId,loc),label=pos||loc?.position||'Única',estado=!loc?'No configurada':ok?'Libre':pal?`Ocupado · ${pal.id}`:qty>0?`Ocupado · ${qty} un.`:'No disponible';return `<button type="button" class="position-chip pallet-map-position ${ok?'available':'occupied'} ${!pos?'single':''}" data-location="${esc(id)}" ${ok?'':'disabled'} title="${esc(id)}"><b>${esc(label)}</b><small>${esc(estado)}</small></button>`;}).join('')}</div></div>`).join('')}</div>`).join('')}</div></section>`;}).join('');
  return `<dialog id="whole-pallet-map" class="pallet-map-dialog"><div class="pallet-map-card"><div class="dialog-head"><div><span class="eyebrow">ELEGIR DESTINO EN MAPA</span><h3>${esc(siteData?.name||site)}</h3><small>Selecciona visualmente la posición donde irá el palet. Las posiciones ocupadas o incompatibles están bloqueadas.</small></div><button id="whole-pallet-map-close" class="ghost" type="button">×</button></div><div class="pallet-map-legend"><span><i class="free"></i> Disponible</span><span><i class="busy"></i> Ocupada / no disponible</span></div><div class="pallet-map-scroll">${rackHtml||`<div class="empty-state"><b>Sin racks configurados</b><small>Este centro todavía no tiene estructura de racks.</small></div>`}</div></div></dialog>`;
}
function mapaDestinoProductoHtml(code,palletId){
  const site=activeSiteId(),siteData=store.data.sites.find(s=>s.id===site),racks=store.data.racks.filter(r=>r.siteId===site&&r.status!=='INACTIVO').sort((a,b)=>String(a.name||a.id).localeCompare(String(b.name||b.id),undefined,{numeric:true}));
  const rackHtml=racks.map(r=>{const mods=Array.from({length:Number(r.modules||0)},(_,i)=>i+1),levels=Array.from({length:Number(r.levels||0)},(_,i)=>Number(r.levels)-i);return `<section class="pallet-map-rack"><div class="pallet-map-rack-head"><div><b>${esc(r.name||r.id)}</b><small>${esc(r.usage||'Selecciona una posición')}</small></div></div><div class="rack-ab-grid">${mods.map(m=>`<div class="rack-module-map"><div class="rack-module-head"><b>Módulo ${m}</b></div>${levels.map(n=>`<div class="rack-level-map"><span>Nivel ${n}</span><div class="rack-position-list">${levelPositions(r,n,m).map(pos=>{const id=positionId(r,m,n,pos),loc=store.data.locations.find(l=>l.id===id),dest=loc?{to:id,destPallet:null,location:loc}:{error:'Ubicación no configurada'},error=loc?validarDestino(code,palletId,dest):'No configurada',same=loc?(store.data.inventory||[]).find(i=>i.locationId===id&&i.productCode===code&&Number(i.qty)>0&&i.palletId!==palletId&&inventorySiteId(i)===site):null,ok=!!loc&&!error,label=pos||loc?.position||'Única',estado=!loc?'No configurada':ok?(same?`Reponer · ${same.qty} un.`:'Disponible'):error;return `<button type="button" class="position-chip pallet-map-position ${ok?'available':'occupied'} ${!pos?'single':''}" data-product-location="${esc(id)}" ${ok?'':'disabled'} title="${esc(id)}"><b>${esc(label)}</b><small>${esc(estado)}</small></button>`;}).join('')}</div></div>`).join('')}</div>`).join('')}</div></section>`;}).join('');
  return `<dialog id="product-location-map" class="pallet-map-dialog"><div class="pallet-map-card"><div class="dialog-head"><div><span class="eyebrow">ELEGIR DESTINO EN MAPA</span><h3>${esc(siteData?.name||site)}</h3><small>Selecciona la posición para ${esc(code)}. El sistema conserva las reglas de ocupación y del centro activo.</small></div><button id="product-location-map-close" class="ghost" type="button">×</button></div><div class="pallet-map-legend"><span><i class="free"></i> Disponible</span><span><i class="busy"></i> No disponible</span></div><div class="pallet-map-scroll">${rackHtml||`<div class="empty-state"><b>Sin racks configurados</b><small>Este centro todavía no tiene estructura de racks.</small></div>`}</div></div></dialog>`;
}
function abrirMapaDestinoProducto(code,palletId,onSelect){
  document.querySelector('#product-location-map')?.remove();
  document.body.insertAdjacentHTML('beforeend',mapaDestinoProductoHtml(code,palletId));
  const dlg=document.querySelector('#product-location-map');
  if(!dlg)return;
  const cerrar=()=>{if(dlg.open)dlg.close();dlg.remove();};
  dlg.querySelector('#product-location-map-close').onclick=cerrar;
  dlg.oncancel=e=>{e.preventDefault();cerrar();};
  dlg.querySelectorAll('[data-product-location]:not(:disabled)').forEach(btn=>btn.onclick=()=>{const loc=store.data.locations.find(l=>l.id===btn.dataset.productLocation);if(!loc)return;onSelect(loc);cerrar();});
  dlg.showModal();
}

function moverPaletCompletoPanel(p){
  return `<button id="open-whole-pallet-dialog" class="primary" type="button">Mover pallet completo</button><dialog id="whole-pallet-dialog" class="pallet-operation-dialog"><section class="pallet-whole-move pallet-operation-card"><div class="dialog-head"><div><span class="eyebrow">TRASLADO DE PALLET COMPLETO</span><h3>Mover ${esc(p.id)} con todo su contenido</h3><p>El pallet conserva todos sus productos.</p></div><button id="close-whole-pallet-dialog" class="ghost" type="button">×</button></div><div class="pallet-destination-actions"><button id="whole-pallet-scan" class="secondary pallet-action-button" type="button">▣ Escanear ubicación</button><button id="whole-pallet-map-open" class="secondary pallet-action-button" type="button">▦ Elegir en mapa</button></div><div class="pallet-selected-destination"><small>Destino seleccionado</small><b id="whole-pallet-selected-label">Todavía no has seleccionado una ubicación</b><span id="whole-pallet-selected-code"></span></div><div class="pallet-whole-move-grid"><label>Código de destino<div class="scan-line"><input id="whole-pallet-location" placeholder="Escanea o escribe ubicación" autocomplete="off"></div><small id="whole-pallet-location-status">Escanea la etiqueta física del destino.</small></label><label>O seleccionar manualmente<select id="whole-pallet-select"><option value="">Seleccionar destino…</option>${opcionesMoverPalet(p.id)}</select></label><button id="whole-pallet-confirm" class="primary" type="button">Mover pallet completo</button></div></section></dialog>${mapaDestinoPaletHtml(p.id)}`;
}

function card(p){
  return `<button class="rack-card pallet-card-click" data-pallet="${esc(p.id)}" data-status="${categoriaPalet(p)}" data-search="${esc(normalizar(`${nombrePalet(p)} ${p.id} ${p.locationId||''}`))}" type="button"><div class="rack-card-body pallet-card-body"><div class="pallet-card-head"><h3>${esc(nombrePalet(p))}</h3><span class="pallet-arrow">›</span></div><p>${esc(String(p.status||'SIN ESTADO').replaceAll('_',' '))}</p><small><b>Ubicación:</b> ${esc(p.locationId||'Sin ubicación definitiva')}</small><small><b>ID permanente:</b> ${esc(p.physicalCode||p.id)}</small><div class="pallet-stats"><span><b>${totalSku(p.id)}</b><small>productos</small></span><span><b>${totalUnidades(p.id)}</b><small>unidades</small></span></div></div></button>`;
}

function filtrosPalets(pallets){
  const count=status=>pallets.filter(p=>categoriaPalet(p)===status).length;
  return `<section class="panel pallet-filter-panel"><div><span class="eyebrow">FILTRAR PALLETS</span><h3>Encuentra rápidamente el pallet</h3></div><div class="pallet-filter-grid"><label>Buscar por nombre, ID o ubicación<div class="entrada-con-camara"><input id="pallet-list-search" placeholder="Ej. Pallet 1, PAL-0001 o REC-R1…" autocomplete="off"><button id="pallet-list-camera" class="scan-button" type="button" title="Escanear pallet o ubicación">▣</button></div></label><label>Estado<select id="pallet-status-filter"><option value="">Todos (${pallets.length})</option><option value="UBICADO">Ubicados (${count('UBICADO')})</option><option value="POR_UBICAR">Por ubicar / recibiendo (${count('POR_UBICAR')})</option><option value="VACÍO">Vacíos (${count('VACÍO')})</option><option value="OTRO">Otros estados (${count('OTRO')})</option></select></label><button id="clear-pallet-filters" class="ghost" type="button">Limpiar filtros</button></div><small id="pallet-filter-count">Mostrando ${pallets.length} de ${pallets.length} pallets</small></section>`;
}

function cargarProductoPanel(p){return `<button id="open-pallet-load-dialog" class="secondary" type="button">+ Asignar productos</button><dialog id="pallet-load-dialog" class="pallet-operation-dialog"><section class="pallet-operation-card pallet-assign-card"><div class="dialog-head"><div><span class="eyebrow">ASIGNAR PRODUCTO A PALLET</span><h3>${esc(nombrePalet(p))}</h3><p>Busca o escanea el producto real, confirma de dónde sale y asigna la cantidad. El stock total no cambia y los códigos incorporados viajarán juntos con el pallet.</p></div><button id="close-pallet-load-dialog" class="ghost" type="button">×</button></div><label>Producto<div class="entrada-con-camara"><input id="pallet-load-product" placeholder="Código, nombre o descripción" autocomplete="off" inputmode="text"><button id="pallet-load-scan" class="scan-button" type="button" title="Escanear producto">▣</button><button id="pallet-load-keyboard" class="scan-button numeric-mode-button" type="button" title="Usar teclado numérico"><span class="numeric-mode-icon">⌨</span><span>123</span></button></div></label><div id="pallet-load-search-results" class="pallet-product-search-results" hidden></div><div id="pallet-load-product-card" class="pallet-resolved-product"><small id="pallet-load-product-status">Busca un producto con stock en este centro.</small></div><div class="pallet-assign-grid"><label>Existencia de origen<select id="pallet-load-source"><option value="">Selecciona primero un producto…</option></select><small>Puede estar sin pallet o dentro de otro pallet.</small></label><label>Cantidad<input id="pallet-load-qty" type="number" min="1" step="1" value="1" inputmode="numeric"></label></div><div class="dialog-actions"><button id="cancel-pallet-load" class="ghost" type="button">Cancelar</button><button id="pallet-load-confirm" class="primary" type="button">Agregar al pallet</button></div></section></dialog>`;}

function registroPaletDialog(){return `<dialog id="register-permanent-pallet"><div class="dialog-card"><div class="dialog-head"><div><span class="eyebrow">PALLET FÍSICO PERMANENTE</span><h3>Registrar pallet</h3><small>El ID permanente no cambia; el nombre visible sí podrá corregirse con permiso.</small></div><button id="close-register-pallet" class="ghost" type="button" aria-label="Cerrar">×</button></div><label>Número o letra del pallet<div class="entrada-con-camara"><input id="permanent-pallet-id" placeholder="Ej. O, C, L, S o 0001" autocomplete="off" required><button id="scan-register-pallet" class="scan-button" type="button" title="Escanear identificador">▣</button></div><small>Se creará como ID PAL-O o PAL-0001 y nombre visible Pallet O o Pallet 0001.</small></label><div class="dialog-actions"><button id="cancel-register-pallet" class="ghost" type="button">Cancelar</button><button id="confirm-register-pallet" class="primary" type="button">Registrar pallet</button></div></div></dialog>`;}

function editarPaletDialog(p){return `<dialog id="edit-pallet-name" class="pallet-operation-dialog"><div class="dialog-card"><div class="dialog-head"><div><span class="eyebrow">INFORMACIÓN DEL PALLET</span><h3>Editar nombre visible</h3><small>El ID permanente ${esc(p.physicalCode||p.id)} no se modifica.</small></div><button id="close-edit-pallet" class="ghost" type="button">×</button></div><label>Nombre visible<input id="edit-pallet-display-name" value="${esc(nombrePalet(p))}" maxlength="60" autocomplete="off"><small>Ejemplo: Pallet 1, Pallet importación o Pallet tienda.</small></label><div class="dialog-actions"><button id="cancel-edit-pallet" class="ghost" type="button">Cancelar</button><button id="confirm-edit-pallet" class="primary" type="button">Guardar nombre</button></div></div></dialog>`;}

function modalCamara(){return `<dialog id="dialogo-camara-pal" class="dialogo-camara"><div class="camara-cabecera"><div><b id="titulo-camara-pal">Escanear código</b><small id="ayuda-camara-pal">Apunta al código de barras</small></div><button id="cerrar-camara-pal" class="ghost">×</button></div><video id="video-camara-pal" autoplay playsinline muted></video><div id="estado-camara-pal" class="estado-camara">Solicitando cámara…</div></dialog>`;}

async function abrirCamaraEn(inputId,titulo='Escanear código',ayuda='Apunta al código de barras',onDetectar=null){
  const dlg=document.querySelector('#dialogo-camara-pal'),video=document.querySelector('#video-camara-pal'),estado=document.querySelector('#estado-camara-pal');
  if(!dlg||!video)return;
  document.querySelector('#titulo-camara-pal').textContent=titulo;document.querySelector('#ayuda-camara-pal').textContent=ayuda;
  const scanner=crearEscaner();dlg.showModal();estado.textContent='Abriendo cámara…';
  const cerrar=()=>{scanner.detener();if(dlg.open)dlg.close();};
  document.querySelector('#cerrar-camara-pal').onclick=cerrar;dlg.oncancel=e=>{e.preventDefault();cerrar();};
  await scanner.iniciar(video,valor=>{const input=document.querySelector(`#${CSS.escape(inputId)}`);if(input){input.value=valor;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}cerrar();if(onDetectar)onDetectar(valor);toast(`Código detectado: ${valor}`);},msg=>estado.textContent=msg);
}

function dialogoGestionProductoPalet(){return `<dialog id="pallet-product-manager" class="pallet-operation-dialog"><section class="pallet-operation-card pallet-product-manager-card"><div class="dialog-head"><div><span class="eyebrow">PRODUCTO DENTRO DEL PALLET</span><h3 id="ppm-title">Gestionar producto</h3><small id="ppm-subtitle"></small></div><button id="ppm-close" class="ghost" type="button">×</button></div><div id="ppm-summary"></div><div class="pallet-manager-actions"><button id="ppm-change-open" class="primary" type="button">Cambiar de pallet</button><button id="ppm-location-open" class="secondary" type="button">Mover a ubicación</button><button id="ppm-product-info" class="ghost" type="button">Ver ficha y stock</button></div><div id="ppm-change-panel" class="pallet-manager-panel"><span class="eyebrow">CAMBIAR DE PALLET</span><p>Selecciona la cantidad y el pallet físico destino. Las unidades salen del pallet actual y entran al destino sin alterar el stock global.</p><label>Pallet destino<div class="entrada-con-camara"><input id="ppm-pallet-code" placeholder="Escanea o escribe ID / nombre del pallet" autocomplete="off" inputmode="text"><button id="ppm-pallet-scan" class="scan-button" type="button" title="Escanear pallet">▣</button><button id="ppm-pallet-keyboard" class="scan-button numeric-mode-button" type="button" title="Usar teclado numérico"><span class="numeric-mode-icon">⌨</span><span>123</span></button></div><small id="ppm-pallet-status">Escanea el identificador físico o selecciónalo abajo.</small></label><select id="ppm-pallet-select"><option value="">Seleccionar pallet…</option></select><label>Cantidad a cambiar<input id="ppm-qty" type="number" min="1" step="1" value="1" inputmode="numeric"></label><div class="dialog-actions"><button id="ppm-cancel-change" class="ghost" type="button">Cancelar</button><button id="ppm-confirm-change" class="primary" type="button">Confirmar cambio de pallet</button></div></div><div id="ppm-location-panel" class="pallet-manager-panel" hidden></div></section></dialog>`;}
function resumenProductoPalet(code,palletId,qty){const p=producto(code),pal=store.data.pallets.find(x=>x.id===palletId),aliases=productAliases(p).filter(x=>String(x)!==String(code)).slice(0,4);return `<div class="pallet-manager-summary"><div class="pallet-product-avatar">▦</div><div><span class="sku">${esc(code)}</span><h3>${esc(p?.name||p?.description||`Producto ${code}`)}</h3><small>${esc(p?.family||'Sin familia')}</small>${aliases.length?`<div class="pallet-alias-chips">${aliases.map(a=>`<span>${esc(a)}</span>`).join('')}</div>`:''}</div><div class="pallet-manager-qty"><b>${qty}</b><small>un. en pallet</small></div></div><div class="pallet-manager-context"><span><small>PALLET ACTUAL</small><b>${esc(nombrePalet(pal))}</b></span><span><small>ID FÍSICO</small><b>${esc(pal?.physicalCode||pal?.id||palletId)}</b></span><span><small>POSICIÓN</small><b>${esc(pal?.locationId||'Sin ubicación')}</b></span></div>`;}
function panelMoverAUbicacion(code,palletId,qty){return `<span class="eyebrow">SACAR DEL PALLET A UBICACIÓN</span><p>Usa esta opción solo cuando el producto dejará físicamente el pallet y quedará directamente en una ubicación.</p><label>Cantidad<input id="ppm-location-qty" type="number" min="1" max="${qty}" value="${qty}" inputmode="numeric"></label><div class="pallet-destination-actions compact"><button id="ppm-location-scan" class="secondary pallet-action-button" type="button">▣ Escanear ubicación</button><button id="ppm-location-map" class="secondary pallet-action-button" type="button">▦ Elegir en mapa</button></div><label>Ubicación<div class="entrada-con-camara"><input id="ppm-location-code" placeholder="Escanea o escribe ubicación" autocomplete="off"><button id="ppm-location-camera" class="scan-button" type="button">▣</button></div><small id="ppm-location-status">Escanea, elige en mapa o escribe la ubicación.</small></label><select id="ppm-location-select"><option value="">Seleccionar manualmente…</option>${opcionesDestino(code,palletId)}</select><div class="dialog-actions"><button id="ppm-location-cancel" class="ghost" type="button">Cancelar</button><button id="ppm-location-confirm" class="primary" type="button">Mover a ubicación</button></div>`;}
function detallePalet(p){
  const inv=contenidoPalet(p.id), rec=recepcionPalet(p.id);
  const permisos=permisosPalets(),operar=permisos.operate;
  const agrupado=[...new Set(inv.map(i=>i.productCode))].map(code=>({code,qty:inv.filter(i=>i.productCode===code).reduce((a,b)=>a+b.qty,0)}));
  return `<section class="panel pallet-detail-panel">
    <div class="panel-head pallet-detail-head"><div><span class="eyebrow">PALLET FÍSICO · UNIDAD COMPLETA</span><h2>${esc(nombrePalet(p))}</h2><small>${esc(String(p.status||'').replaceAll('_',' '))} · ${esc(p.locationId||'Sin ubicación')}</small></div><div class="pallet-head-actions">${permisos.edit?'<button id="open-edit-pallet" class="secondary" type="button">Editar información</button>':''}<a class="ghost" href="#/palets">Cerrar ×</a></div></div>
    ${p.sourceShipmentId&&p.status==='UBICADO'?'<div class="success-box"><b>✓ Recepción y primera ubicación completadas</b><span>El pallet sigue activo como unidad física y puede volver a moverse completo.</span></div>':''}
    <div class="pallet-meta-grid"><span><b>Nombre visible</b><small>${esc(nombrePalet(p))}</small></span><span><b>ID permanente</b><small>${esc(p.physicalCode||p.id)}</small></span><span><b>Posición del pallet</b><small>${esc(p.locationId||'Sin ubicación')}</small></span><span><b>Contenido conjunto</b><small>${agrupado.length} productos · ${totalUnidades(p.id)} unidades</small></span></div>
    ${operar?`<div class="pallet-primary-actions">${moverPaletCompletoPanel(p)}${cargarProductoPanel(p)}</div><div class="info-box"><b>Organización de pallet</b><br>Aquí puedes incorporar productos, mover el pallet completo o reubicar existencias. La preparación de pedidos se inicia exclusivamente desde Órdenes / Mis tareas.</div>`:'<div class="info-box">Modo consulta: la administración puede habilitar el permiso para cargar productos y mover pallets.</div>'}
    <div class="pallet-search-box"><label>Buscar dentro de este pallet<div class="pallet-search-input"><input id="pallet-q" placeholder="Código, descripción o palabra" autocomplete="off"><button id="pallet-camera" class="scan-button" type="button" title="Escanear producto">▣</button></div><small>Busca el producto que necesitas consultar o reubicar dentro de la bodega.</small></label></div>
    <div id="pallet-results">${listaContenido(agrupado,p.id,'')}</div>
  </section>${permisos.edit?editarPaletDialog(p):''}${operar?dialogoGestionProductoPalet():''}${modalCamara()}`;
}

function listaContenido(items,palletId,q){
  const nq=normalizar(q), filtrados=items.filter(x=>{if(!nq)return true;const p=producto(x.code);return normalizar(productAliases(p).join(' ')).includes(nq)||normalizar(p?.name).includes(nq)||normalizar(p?.family).includes(nq);});
  if(!filtrados.length)return empty('No está en este palet','Prueba otro código o descripción.');
  return `<div class="pallet-item-list">${filtrados.map(x=>itemProducto(x,palletId)).join('')}</div>`;
}

function itemProducto(x,palletId){
  const p=producto(x.code), {ya}=recomendaciones(x.code,palletId);
  return `<article class="pallet-item pallet-item-clickable" data-code="${esc(x.code)}"><button class="pallet-item-open" type="button" data-code="${esc(x.code)}"><div class="pallet-item-summary"><div><span class="sku">${esc(x.code)}</span><h3>${esc(p?.name||p?.description||`Producto ${x.code}`)}</h3><small>${esc(p?.family||'Por clasificar')}</small></div><div class="pallet-item-qty"><b>${x.qty}</b><small>en pallet</small></div></div><div class="pallet-item-foot"><span>Tocar para gestionar</span>${ya.length?`<small>También existe en ${ya.length} ubicación(es)</small>`:'<small>Sin otras ubicaciones detectadas</small>'}</div></button></article>`;
}

function resolverDestino(code,palletId,codigoManual,selectValue){
  if(codigoManual){
    const location=buscarUbicacionPorCodigo(codigoManual,store.data); if(!location)return {error:'El código de ubicación no existe'};
    if(location.siteId!==activeSiteId())return {error:'La ubicación escaneada pertenece a otro centro. Cambia primero el centro activo.'};
    const same=store.data.inventory.find(i=>i.locationId===location.id&&i.productCode===code&&i.qty>0&&i.palletId!==palletId&&inventorySiteId(i)===activeSiteId());
    return {to:location.id,destPallet:same?.palletId||null,location};
  }
  if(selectValue){const [to,destPalletRaw='']=selectValue.split('@@'),site=activeSiteId();return {to,destPallet:destPalletRaw||null,location:store.data.locations.find(l=>l.id===to&&l.siteId===site)};}
  return {error:'Escanea, escribe o selecciona una ubicación'};
}

function validarDestino(code,palletId,dest){
  if(dest.error)return dest.error;const location=dest.location;
  if(!location||!location.active)return 'La ubicación no está disponible';
  if(['BLOQUEADA','INHABILITADA'].includes(location.status))return 'La ubicación está bloqueada o inhabilitada';
  const otros=store.data.inventory.filter(i=>i.locationId===location.id&&i.qty>0&&i.productCode!==code&&i.palletId!==palletId&&inventorySiteId(i)===activeSiteId());
  if(location.kind==='PICKING_RACK'&&otros.length)return `Posición ocupada por ${otros[0].productCode}. Elige otra ubicación.`;
  return '';
}

async function moverDesdePalet({palletId,code,qty,codigoManual='',selectValue=''}){
  const site=activeSiteId(),palletBefore=store.data.pallets.find(x=>x.id===palletId&&x.siteId===site), sourceRows=store.data.inventory.filter(i=>i.palletId===palletId&&i.productCode===code&&i.qty>0&&inventorySiteId(i)===site), available=sourceRows.reduce((a,b)=>a+b.qty,0);
  if(!code||!available)return {ok:false,message:'Ese producto no está disponible en el palet'};
  if(qty<1||qty>available)return {ok:false,message:`Disponible en el palet: ${available}`};
  const dest=resolverDestino(code,palletId,codigoManual,selectValue), error=validarDestino(code,palletId,dest);if(error)return {ok:false,message:error};
  const {to,destPallet,location}=dest, now=new Date().toISOString();
  await store.commit(d=>{
    const result=deductStock(d,{code,qty,sourceKey:`${sourceRows[0].locationId}@@${palletId}`});
    if(!result.ok)throw new Error(result.message);
    const added=addStock(d,{code,qty,locationId:to,palletId:destPallet});
    d.movements.unshift({id:`MOV-${Date.now()}`,siteId:activeSiteId(d),type:'MOVIMIENTO_DESDE_PALET',productCode:code,qty,from:`${palletId} / ${palletBefore?.locationId||'POR UBICAR'}`,to:destPallet?`${destPallet} / ${to}`:to,reason:destPallet?'Consolidación / reposición desde palet':'Ubicación desde palet por doble escaneo',userId:d.session.userId,palletId,at:now,method:codigoManual?'ESCANEO_O_CODIGO':'SELECCION_MANUAL',beforeQty:available,afterQty:available-qty,destinationBeforeQty:added.beforeQty,destinationAfterQty:added.afterQty,allocations:result.allocations});
    const pal=d.pallets.find(x=>x.id===palletId), remains=d.inventory.some(i=>i.palletId===palletId&&i.qty>0);if(pal)pal.status=remains?'POR_UBICAR':'VACÍO';if(!remains){const task=(d.tasks||[]).find(t=>t.type==='UBICAR_CARGA'&&t.palletId===palletId&&t.status!=='CERRADA'),closedAt=new Date().toISOString();if(task){task.status='CERRADA';task.closedAt=closedAt;task.closedBy=d.session.userId;task.events=task.events||[];task.events.push({at:closedAt,userId:d.session.userId,message:'Todos los productos del pallet fueron ubicados'});const shipment=(d.shipments||[]).find(s=>s.id===task.shipmentId);if(shipment){shipment.status='CERRADA';shipment.closedAt=closedAt;shipment.events=shipment.events||[];shipment.events.push({at:closedAt,userId:d.session.userId,message:'Ubicación de la carga completada'});}}}
  },`${code}: ${qty} un. descontadas de ${palletId} y sumadas a ${to}`,{operations:['palletsOperate']});
  return {ok:true,message:`${code} ubicado en ${destPallet?`${destPallet} / `:''}${vistaCodigoUbicacion(location,store.data)}`,to};
}

function wireProductManager(palletId,code){
  const dlg=document.querySelector('#pallet-product-manager');if(!dlg)return;
  const rows=contenidoPalet(palletId).filter(i=>i.productCode===code),qty=rows.reduce((a,b)=>a+Number(b.qty||0),0),p=producto(code),pal=store.data.pallets.find(x=>x.id===palletId);
  if(!p||!qty){toast('Ese producto ya no está disponible en este pallet');return;}
  dlg.querySelector('#ppm-title').textContent=`${code} · ${p.name||p.description||'Producto'}`;dlg.querySelector('#ppm-subtitle').textContent=`${nombrePalet(pal)} · ${pal?.locationId||'Sin ubicación'}`;dlg.querySelector('#ppm-summary').innerHTML=resumenProductoPalet(code,palletId,qty);
  const changePanel=dlg.querySelector('#ppm-change-panel'),locationPanel=dlg.querySelector('#ppm-location-panel'),qtyInput=dlg.querySelector('#ppm-qty'),palCode=dlg.querySelector('#ppm-pallet-code'),palSelect=dlg.querySelector('#ppm-pallet-select'),palStatus=dlg.querySelector('#ppm-pallet-status');
  qtyInput.max=qty;qtyInput.value=qty;palCode.value='';palSelect.innerHTML=`<option value="">Seleccionar pallet…</option>${palletsDestinoOptions(palletId)}`;palStatus.textContent='Escanea el identificador físico o selecciónalo abajo.';palStatus.classList.remove('valid');locationPanel.hidden=true;changePanel.hidden=false;
  const close=()=>dlg.close();dlg.querySelector('#ppm-close').onclick=close;dlg.oncancel=e=>{e.preventDefault();close();};dlg.querySelector('#ppm-cancel-change').onclick=close;
  const validateTarget=()=>{const target=palCode.value?buscarPallet(palCode.value,palletId):(store.data.pallets||[]).find(x=>x.id===palSelect.value&&x.siteId===activeSiteId()&&x.status!=='CERRADO'),valid=!!(target&&target.locationId);palStatus.textContent=!palCode.value&&!palSelect.value?'Escanea el identificador físico o selecciónalo abajo.':valid?`✓ ${nombrePalet(target)} · ${target.locationId}`:'Pallet no reconocido, cerrado o de otro centro';palStatus.classList.toggle('valid',valid);return valid?target:null;};
  palCode.oninput=()=>{if(palCode.value)palSelect.value='';validateTarget();};palSelect.onchange=()=>{if(palSelect.value)palCode.value='';validateTarget();};wireInputModeToggle(dlg.querySelector('#ppm-pallet-keyboard'),palCode);dlg.querySelector('#ppm-pallet-scan').onclick=()=>abrirCamaraEn('ppm-pallet-code','Escanear pallet destino','Apunta al identificador físico del pallet',()=>validateTarget());
  dlg.querySelector('#ppm-product-info').onclick=()=>{close();openProductEditor(code,{onSaved:()=>renderPallets(document.querySelector('#app'))});};
  dlg.querySelector('#ppm-change-open').onclick=()=>{locationPanel.hidden=true;changePanel.hidden=false;};
  dlg.querySelector('#ppm-location-open').onclick=()=>{changePanel.hidden=true;locationPanel.hidden=false;locationPanel.innerHTML=panelMoverAUbicacion(code,palletId,qty);const locInput=locationPanel.querySelector('#ppm-location-code'),locSelect=locationPanel.querySelector('#ppm-location-select'),locStatus=locationPanel.querySelector('#ppm-location-status');const validateLoc=()=>{const loc=buscarUbicacionPorCodigo(locInput.value,store.data),dest=loc?{to:loc.id,destPallet:null,location:loc}:{error:'Ubicación no reconocida'},error=loc?validarDestino(code,palletId,dest):'',valid=!!loc&&!error;locStatus.textContent=!locInput.value?'Escanea, elige en mapa o escribe la ubicación.':valid?`✓ ${vistaCodigoUbicacion(loc,store.data)}`:loc?error:'Ubicación no reconocida';locStatus.classList.toggle('valid',valid);return valid?loc:null;};locInput.oninput=()=>{if(locInput.value)locSelect.value='';validateLoc();};locSelect.onchange=()=>{if(locSelect.value)locInput.value='';};locationPanel.querySelector('#ppm-location-scan').onclick=()=>locationPanel.querySelector('#ppm-location-camera').click();locationPanel.querySelector('#ppm-location-camera').onclick=()=>abrirCamaraEn('ppm-location-code','Escanear ubicación','Apunta a la etiqueta de la posición',()=>validateLoc());locationPanel.querySelector('#ppm-location-map').onclick=()=>abrirMapaDestinoProducto(code,palletId,loc=>{locInput.value=loc.id;locSelect.value='';validateLoc();});locationPanel.querySelector('#ppm-location-cancel').onclick=()=>{locationPanel.hidden=true;changePanel.hidden=false;};locationPanel.querySelector('#ppm-location-confirm').onclick=async()=>{const result=await moverDesdePalet({palletId,code,qty:Number(locationPanel.querySelector('#ppm-location-qty').value),codigoManual:locInput.value.trim(),selectValue:locSelect.value});if(!result.ok){await notice('Movimiento no realizado',result.message,'warning');return;}dlg.close();await notice('Producto movido',result.message,'success');renderPallets(document.querySelector('#app'));};};
  dlg.querySelector('#ppm-confirm-change').onclick=async()=>{const target=validateTarget(),moveQty=Number(qtyInput.value);if(!target){await notice('Falta pallet destino','Escanea o selecciona un pallet válido del centro activo.','warning');return;}if(moveQty<1||moveQty>qty){await notice('Cantidad no válida',`Dentro de ${nombrePalet(pal)} hay ${qty} unidad(es) disponibles.`,'warning');return;}let result;try{await store.commit(d=>{result=moveProductToPallet(d,{code,qty:moveQty,sourcePalletId:palletId,destinationPalletId:target.id,siteId:activeSiteId(d),userId:d.session.userId});if(!result.ok)throw new Error(result.message);},`${code}: ${moveQty} un. ${palletId} → ${target.id}`,{operations:['palletsOperate']});}catch(error){await notice('Cambio de pallet no realizado',error.message||'No fue posible mover el producto.','error');return;}dlg.close();await notice('Producto cambiado de pallet',result.message,'success');renderPallets(document.querySelector('#app'));};
  dlg.showModal();
}

function wireDetail(palletId){
  wireEditPallet(palletId);
  if(!permisosPalets().operate){const q=document.querySelector('#pallet-q'),out=document.querySelector('#pallet-results');const construir=()=>[...new Set(contenidoPalet(palletId).map(i=>i.productCode))].map(code=>({code,qty:contenidoPalet(palletId).filter(i=>i.productCode===code).reduce((a,b)=>a+b.qty,0)}));q.oninput=()=>{out.innerHTML=listaContenido(construir(),palletId,q.value);};document.querySelector('#pallet-camera').onclick=()=>abrirCamaraEn('pallet-q','Escanear producto del pallet','Apunta al código de barras de la caja');return;}
  const construirBase=()=>[...new Set(contenidoPalet(palletId).map(i=>i.productCode))].map(code=>({code,qty:contenidoPalet(palletId).filter(i=>i.productCode===code).reduce((a,b)=>a+b.qty,0)}));
  const wholeDialog=document.querySelector('#whole-pallet-dialog'),loadDialog=document.querySelector('#pallet-load-dialog');
  document.querySelector('#open-whole-pallet-dialog').onclick=()=>wholeDialog.showModal();document.querySelector('#close-whole-pallet-dialog').onclick=()=>wholeDialog.close();
  document.querySelector('#open-pallet-load-dialog').onclick=()=>{loadDialog.showModal();setTimeout(()=>document.querySelector('#pallet-load-product')?.focus(),40);};document.querySelector('#close-pallet-load-dialog').onclick=()=>loadDialog.close();if(loadDialog)loadDialog.oncancel=e=>{e.preventDefault();loadDialog.close();};
  const wholeInput=document.querySelector('#whole-pallet-location'),wholeSelect=document.querySelector('#whole-pallet-select'),wholeStatus=document.querySelector('#whole-pallet-location-status'),selectedLabel=document.querySelector('#whole-pallet-selected-label'),selectedCode=document.querySelector('#whole-pallet-selected-code'),mapDialog=document.querySelector('#whole-pallet-map');
  const showSelected=loc=>{if(!loc){selectedLabel.textContent='Todavía no has seleccionado una ubicación';selectedCode.textContent='';return;}selectedLabel.textContent=loc.label||vistaCodigoUbicacion(loc,store.data);selectedCode.textContent=loc.id;};
  document.querySelector('#whole-pallet-scan').onclick=()=>abrirCamaraEn('whole-pallet-location','Mover palet completo','Apunta a la etiqueta de la zona o posición de destino');
  document.querySelector('#whole-pallet-map-open').onclick=()=>mapDialog?.showModal();
  document.querySelector('#whole-pallet-map-close').onclick=()=>mapDialog?.close();
  if(mapDialog)mapDialog.oncancel=e=>{e.preventDefault();mapDialog.close();};
  document.querySelectorAll('.pallet-map-position[data-location]:not(:disabled)').forEach(b=>b.onclick=()=>{const loc=store.data.locations.find(l=>l.id===b.dataset.location);if(!loc)return;wholeInput.value='';wholeSelect.value=loc.id;wholeStatus.textContent=`✓ Destino elegido en mapa: ${vistaCodigoUbicacion(loc,store.data)}`;wholeStatus.classList.add('valid');showSelected(loc);mapDialog?.close();toast(`Destino seleccionado: ${loc.id}`);});
  const validateWholeDestination=()=>{const loc=buscarUbicacionPorCodigo(wholeInput.value,store.data),valid=destinoPaletDisponible(palletId,loc);wholeStatus.textContent=!wholeInput.value?'Escanea la etiqueta física del destino.':valid?`✓ Destino válido: ${vistaCodigoUbicacion(loc,store.data)}`:loc?'Esa ubicación está ocupada, no admite este palet o pertenece a otro centro':'Ubicación no reconocida';wholeStatus.classList.toggle('valid',!!valid);showSelected(valid?loc:null);};
  wholeInput.oninput=()=>{if(wholeInput.value)wholeSelect.value='';validateWholeDestination();};wholeSelect.onchange=()=>{if(wholeSelect.value){wholeInput.value='';const loc=store.data.locations.find(l=>l.id===wholeSelect.value),valid=destinoPaletDisponible(palletId,loc);wholeStatus.textContent=valid?'✓ Destino seleccionado manualmente.':'Ese destino ya no está disponible.';wholeStatus.classList.toggle('valid',!!valid);showSelected(valid?loc:null);}else showSelected(null);};
  document.querySelector('#whole-pallet-confirm').onclick=async()=>{const scanned=wholeInput.value.trim(),loc=scanned?buscarUbicacionPorCodigo(scanned,store.data):store.data.locations.find(l=>l.id===wholeSelect.value),site=activeSiteId();if(!loc){toast('Escanea, escribe o selecciona un destino');return;}let result;try{await store.commit(d=>{result=moveWholePallet(d,{palletId,siteId:site,destinationLocationId:loc.id,userId:d.session.userId});if(!result.ok)throw new Error(result.message);},`Palet ${palletId} trasladado completo a ${loc.id}`,{operations:['palletsOperate']});}catch(error){toast(error.message||'No fue posible mover el palet');return;}toast(result.message);renderPallets(document.querySelector('#app'));};
  wireLoadProduct(palletId);
  const q=document.querySelector('#pallet-q'), out=document.querySelector('#pallet-results');
  const wireItems=()=>document.querySelectorAll('.pallet-item-open').forEach(b=>b.onclick=()=>wireProductManager(palletId,b.dataset.code));
  const repintar=()=>{out.innerHTML=listaContenido(construirBase(),palletId,q.value);wireItems();};
  q.oninput=repintar;document.querySelector('#pallet-camera').onclick=()=>abrirCamaraEn('pallet-q','Escanear producto del pallet','Apunta al código de barras de la caja',valor=>{const found=resolveProduct(valor),inside=found&&construirBase().some(x=>x.code===found.code);if(inside){q.value=found.code;repintar();setTimeout(()=>wireProductManager(palletId,found.code),40);}else toast('El producto escaneado no está dentro de este pallet');});wireItems();
}

function wireEditPallet(palletId){
  const open=document.querySelector('#open-edit-pallet'),dialog=document.querySelector('#edit-pallet-name'),input=document.querySelector('#edit-pallet-display-name'),confirm=document.querySelector('#confirm-edit-pallet');if(!open||!dialog||!input||!confirm)return;
  const close=()=>{if(dialog.open)dialog.close();};open.onclick=()=>{dialog.showModal();setTimeout(()=>{input.focus();input.select();},40);};document.querySelector('#close-edit-pallet').onclick=close;document.querySelector('#cancel-edit-pallet').onclick=close;dialog.oncancel=e=>{e.preventDefault();close();};
  confirm.onclick=async()=>{if(!permisosPalets().edit){toast('No tienes permiso para editar pallets');return;}let result;try{await store.commit(d=>{result=editPalletDisplayName(d,{palletId,siteId:activeSiteId(d),displayName:input.value,userId:d.session.userId});if(!result.ok)throw new Error(result.message);},`Nombre visible del pallet ${palletId} actualizado`,{operations:['palletsEdit']});}catch(error){toast(error.message||'No fue posible actualizar el nombre');return;}close();toast(result.message);renderPallets(document.querySelector('#app'));};
}

function wireLoadProduct(palletId){
  const input=document.querySelector('#pallet-load-product'),source=document.querySelector('#pallet-load-source'),qty=document.querySelector('#pallet-load-qty'),status=document.querySelector('#pallet-load-product-status'),card=document.querySelector('#pallet-load-product-card'),results=document.querySelector('#pallet-load-search-results'),confirm=document.querySelector('#pallet-load-confirm');if(!input||!source||!qty||!confirm)return;
  let resolvedCode='';
  const selectProduct=code=>{const product=resolveProduct(code)||(store.data.products||[]).find(p=>p.code===code);if(!product)return false;resolvedCode=product.code;input.value=product.code;results.hidden=true;results.innerHTML='';const site=activeSiteId(),positions=productPositions(store.data,product.code).filter(pos=>pos.palletId!==palletId&&inventorySiteId({locationId:pos.locationId,palletId:pos.palletId})===site);source.innerHTML=positions.length?`<option value="">Seleccionar origen…</option>${positions.map(pos=>`<option value="${esc(pos.key)}" data-qty="${pos.qty}">${pos.palletId?`Pallet ${esc(pos.palletId)} · `:'Sin pallet · '}${esc(pos.locationId)} · ${pos.qty} un.</option>`).join('')}`:'<option value="">Sin existencias disponibles fuera de este pallet</option>';card.innerHTML=`<div class="pallet-resolved-product-main"><div><span class="sku">${esc(product.code)}</span><b>${esc(product.name||product.description||'Producto')}</b><small>${esc(product.family||'Sin familia')}</small></div><strong>${positions.reduce((a,b)=>a+b.qty,0)} un.<small> disponibles</small></strong></div>`;status.textContent=positions.length?'✓ Producto reconocido. Selecciona el origen real.':'Producto reconocido, pero no tiene stock disponible fuera de este pallet';status.classList.toggle('valid',!!positions.length);if(positions.length===1){source.value=positions[0].key;qty.max=positions[0].qty;qty.value=Math.min(Number(qty.value)||1,positions[0].qty);}return true;};
  const refresh=()=>{const raw=input.value.trim();if(!raw){resolvedCode='';source.innerHTML='<option value="">Selecciona primero un producto…</option>';card.innerHTML='<small id="pallet-load-product-status">Busca un producto con stock en este centro.</small>';results.hidden=true;results.innerHTML='';return;}const exact=resolveProduct(raw);if(exact){selectProduct(exact.code);return;}resolvedCode='';const matches=buscarProductosTexto(raw);results.innerHTML=matches.length?matches.map(p=>`<button type="button" class="pallet-product-search-result" data-code="${esc(p.code)}"><span><b>${esc(p.code)}</b><small>${esc(p.name||p.description||'Producto')}</small></span><em>Elegir</em></button>`).join(''):`<div class="pallet-search-no-result">Sin coincidencias</div>`;results.hidden=false;results.querySelectorAll('[data-code]').forEach(b=>b.onclick=()=>selectProduct(b.dataset.code));source.innerHTML='<option value="">Selecciona un producto de la lista…</option>';card.innerHTML='<small id="pallet-load-product-status">Selecciona la coincidencia correcta.</small>';};
  input.oninput=refresh;source.onchange=()=>{const max=Number(source.selectedOptions[0]?.dataset.qty||0);if(max){qty.max=max;qty.value=Math.min(Math.max(Number(qty.value)||1,1),max);}};wireInputModeToggle(document.querySelector('#pallet-load-keyboard'),input);document.querySelector('#pallet-load-scan').onclick=()=>abrirCamaraEn('pallet-load-product','Asignar producto a pallet','Apunta al código del producto',valor=>{const exact=resolveProduct(valor);if(exact)selectProduct(exact.code);});
  document.querySelector('#cancel-pallet-load').onclick=()=>document.querySelector('#pallet-load-dialog')?.close();
  confirm.onclick=async()=>{if(!resolvedCode){await notice('Falta seleccionar el producto','Busca, toca una coincidencia o escanea el código del producto.','warning');input.focus();return;}if(!source.value){await notice('Falta seleccionar el origen','Indica de qué ubicación o pallet salen físicamente estas unidades.','warning');source.focus();return;}let result;try{await store.commit(d=>{result=assignProductToPallet(d,{palletId,siteId:activeSiteId(d),code:resolvedCode,qty:Number(qty.value),sourceKey:source.value,userId:d.session.userId});if(!result.ok)throw new Error(result.message);},`${resolvedCode} asignado al pallet ${palletId}`,{operations:['palletsOperate']});}catch(error){await notice('No se pudo asignar el producto',error.message||'No fue posible agregar el producto al pallet.','error');return;}document.querySelector('#pallet-load-dialog')?.close();await notice('Producto asignado al pallet',result.message,'success');renderPallets(document.querySelector('#app'));};
}

function wirePlacement(palletId){
  document.querySelectorAll('.pallet-product-info').forEach(b=>b.onclick=()=>openProductEditor(b.dataset.code,{onSaved:()=>renderPallets(document.querySelector('#app'))}));
  document.querySelectorAll('.place-from-pallet').forEach(form=>{
    const code=form.dataset.code,input=form.elements.locationCode,select=form.elements.to,validation=form.querySelector('.location-validation');
    form.querySelector('.scan-location-btn').onclick=()=>abrirCamaraEn(input.id||(input.id=`loc-${code}`),'Escanear ubicación','Apunta a la etiqueta del rack / posición');
    form.querySelector('.map-location-btn').onclick=()=>abrirMapaDestinoProducto(code,palletId,loc=>{input.value=loc.id;select.value='';input.dispatchEvent(new Event('input',{bubbles:true}));toast(`Destino seleccionado: ${loc.id}`);});
    input.oninput=()=>{const loc=buscarUbicacionPorCodigo(input.value,store.data),dest=loc?{to:loc.id,destPallet:null,location:loc}:{error:'Ubicación no reconocida'},error=loc?validarDestino(code,palletId,dest):'',valid=!!loc&&!error;validation.textContent=!input.value?'Escanea, elige en mapa o escribe la ubicación.':valid?`✓ Ubicación válida: ${vistaCodigoUbicacion(loc,store.data)}`:loc?error:'Código aún no reconocido';validation.classList.toggle('valid',!!valid);};
    select.onchange=()=>{if(select.value)input.value='';};
    form.onsubmit=async e=>{e.preventDefault();const result=await moverDesdePalet({palletId,code,qty:Number(form.elements.qty.value),codigoManual:input.value.trim(),selectValue:select.value});if(!result.ok){toast(result.message);return;}toast(result.message);renderPallets(document.querySelector('#app'));};
  });
}

export function renderPallets(root){
  const d=store.data,siteId=activeSiteId(d),site=d.sites.find(s=>s.id===siteId),pallets=d.pallets.filter(x=>x.siteId===siteId),selected=params().get('id'),p=pallets.find(x=>x.id===selected),pending=pallets.filter(x=>x.status==='POR_UBICAR'||x.status==='RECIBIENDO');
  if(!permisosPalets().view){root.innerHTML=shell('Palets','<section class="panel"><div class="empty-state"><b>Acceso restringido</b><small>Solicita a administración el permiso para consultar pallets.</small></div></section>','palets');wireShell();return;}
  const register=puedeRegistrarPalet()?'<button id="open-register-pallet" class="primary" type="button">+ Registrar pallet físico</button>':'';
  const body=`<div class="page-intro"><div><span class="eyebrow">UNIDAD LOGÍSTICA · CENTRO ACTIVO</span><h2>Palets · ${esc(site?.name||siteId)}</h2><p>Cada pallet puede contener uno o varios productos y ocupa una sola posición física del rack. Al moverlo completo, todos sus códigos viajan juntos.</p></div><div>${register}<div class="pallet-summary"><b>${pending.length}</b><small>palets por organizar</small></div></div></div>${p?detallePalet(p):`${filtrosPalets(pallets)}<div id="pallet-filter-empty" hidden>${empty('Sin coincidencias','Cambia el texto o el estado seleccionado.')}</div><div id="pallet-list-grid" class="rack-grid pallet-grid">${pallets.length?pallets.map(card).join(''):empty('Sin palets en este centro','Registra el primer pallet físico permanente para comenzar.')}</div>`}${registroPaletDialog()}${p?'':modalCamara()}`;
  root.innerHTML=shell('Palets',body,'palets');wireShell();if(p)wireDetail(p.id);else{document.querySelectorAll('.pallet-card-click').forEach(b=>b.onclick=()=>location.hash=`#/palets?id=${encodeURIComponent(b.dataset.pallet)}`);wirePalletFilters(pallets.length);}wireRegisterPallet(root);
}

function wirePalletFilters(total){const input=document.querySelector('#pallet-list-search'),status=document.querySelector('#pallet-status-filter'),count=document.querySelector('#pallet-filter-count'),emptyBox=document.querySelector('#pallet-filter-empty');if(!input||!status)return;const paint=()=>{const q=normalizar(input.value),wanted=status.value;let shown=0;document.querySelectorAll('.pallet-card-click').forEach(card=>{const visible=(!q||card.dataset.search.includes(q))&&(!wanted||card.dataset.status===wanted);card.hidden=!visible;if(visible)shown++;});count.textContent=`Mostrando ${shown} de ${total} pallets`;emptyBox.hidden=shown!==0;};input.oninput=paint;status.onchange=paint;document.querySelector('#clear-pallet-filters').onclick=()=>{input.value='';status.value='';paint();input.focus();};document.querySelector('#pallet-list-camera').onclick=()=>abrirCamaraEn('pallet-list-search','Buscar pallet','Apunta al código del pallet o de su ubicación');}

function wireRegisterPallet(root){const open=document.querySelector('#open-register-pallet'),dialog=document.querySelector('#register-permanent-pallet'),confirm=document.querySelector('#confirm-register-pallet'),input=document.querySelector('#permanent-pallet-id');if(!open||!dialog||!confirm||!input)return;const close=()=>{if(dialog.open)dialog.close();};open.onclick=()=>{input.value='';dialog.showModal();setTimeout(()=>input.focus(),50);};document.querySelector('#close-register-pallet').onclick=close;document.querySelector('#cancel-register-pallet').onclick=close;dialog.oncancel=e=>{e.preventDefault();close();};document.querySelector('#scan-register-pallet').onclick=()=>abrirCamaraEn('permanent-pallet-id','Escanear pallet físico','Apunta al número, letra o código del pallet');confirm.onclick=async()=>{if(!permisosPalets().register){toast('No tienes permiso para registrar pallets');return;}let result;try{await store.commit(d=>{result=registerPermanentPallet(d,{identifier:input.value,siteId:activeSiteId(d),userId:d.session.userId});if(!result.ok)throw new Error(result.message);},`Pallet físico ${input.value} registrado`,{operations:['palletsRegister']});}catch(error){toast(error.message||'No fue posible registrar el pallet');return;}close();toast(result.message);renderPallets(root);};}
