import { store } from '../../services/store.js';
import { shell,wireShell,toast } from '../../layout/layout.js';
import { esc,badge,empty } from '../../components/ui.js';
import { activeSiteId } from '../../services/stock.js';
import { enlazarBotonEscaner } from '../../services/camara-ui.js';
import { code128Svg } from '../../services/barcode.js';
import { SHIPMENT_STATUS,acceptShipmentCustody,ensureLegacyShipment,markShipmentArrival,shipmentByCode } from '../../services/transfer-workflow.js';

function me(){return store.data.users.find(u=>u.id===store.data.session.userId);}
function manager(){return ['ADMIN_GLOBAL','ADMINISTRADOR','ENCARGADO'].includes(me()?.role);}
function siteName(id){return store.data.sites.find(s=>s.id===id)?.name||id||'—';}
function destinationName(s){return s.destinationName||siteName(s.destinationSiteId);}
function productName(code){return store.data.products.find(p=>p.code===code)?.name||code;}
function statusTone(status){return ['RECIBIDA','CERRADA'].includes(status)?'ok':['EN_TRANSITO','LLEGADA_DESTINO','RECIBIDA_DIFERENCIAS'].includes(status)?'warn':'neutral';}
function units(s){return (s.items||[]).reduce((sum,i)=>sum+Number(i.expectedQty||0),0);}
function canUse(s){const u=me();return manager()||u?.role==='TRANSPORTISTA'&&(!s.transporterUserId||s.transporterUserId===u.id);}
function transportOptions(selected=''){return (store.data.users||[]).filter(u=>u.active!==false&&u.accessStatus!=='PAUSED'&&(u.role==='TRANSPORTISTA'||(u.accessAssignments||[]).some(a=>a.role==='TRANSPORTISTA'))).map(u=>`<option value="${esc(u.id)}" ${u.id===selected?'selected':''}>${esc(u.name)}</option>`).join('');}
function shipmentCard(s){return `<article class="shipment-card"><div class="shipment-card-head"><div><span class="eyebrow">${esc(s.code)}</span><h3>${esc(siteName(s.sourceSiteId))} → ${esc(destinationName(s))}</h3><small>${s.packageCount||1} paquete(s) · ${s.items.length} producto(s) · ${units(s)} unidades</small>${s.destinationType==='EXTERNAL'?`<small>${esc(s.destinationAddress||'Sin dirección')} · Recibe: ${esc(s.destinationContact||'Sin contacto')}</small>`:''}</div>${badge(SHIPMENT_STATUS[s.status]||s.status,statusTone(s.status))}</div><div class="shipment-manifest">${s.items.map(i=>`<span><b>${esc(i.code)}</b><small>${esc(productName(i.code))}</small><strong>${i.expectedQty}</strong></span>`).join('')}</div><div class="shipment-meta"><span>Transportista: <b>${esc(store.data.users.find(u=>u.id===s.transporterUserId)?.name||s.driverName||'Por asignar')}</b></span><span>Traspaso: <b>${esc(s.transferId)}</b></span></div><div class="shipment-actions">${manager()&&s.status==='LISTA_RETIRO'?`<select class="shipment-driver" data-id="${esc(s.id)}"><option value="">Asignar transportista…</option>${transportOptions(s.transporterUserId)}</select><button class="secondary save-shipment-driver" data-id="${esc(s.id)}" type="button">Guardar asignación</button>`:''}<button class="ghost print-shipment" data-id="${esc(s.id)}" type="button">Imprimir etiqueta</button>${canUse(s)&&s.status==='LISTA_RETIRO'?`<button class="primary accept-custody" data-id="${esc(s.id)}" type="button">Aceptar custodia</button>`:''}${canUse(s)&&s.status==='EN_TRANSITO'?`<button class="primary mark-arrival" data-id="${esc(s.id)}" type="button">${s.destinationType==='EXTERNAL'?'Confirmar entrega':'Confirmar llegada'}</button>`:''}</div></article>`;}
export function shipmentLabelDocument(s){return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(s.code)}</title><style>@page{size:A4;margin:14mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;padding:18px;color:#07111f;margin:0}.label{border:3px solid #07111f;border-radius:18px;padding:24px}.label h1{margin:0 0 18px}.route{display:flex;justify-content:space-between;align-items:center;gap:18px;font-size:20px;font-weight:800}.barcode{margin:24px 0}.barcode svg{width:100%;height:135px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding-top:16px;border-top:1px solid #bbb}@media(max-width:600px){body{padding:8px}.label{padding:14px}.route{display:grid;font-size:16px}.meta{grid-template-columns:1fr}}@media print{body{padding:0}.label{break-inside:avoid}}</style></head><body><section class="label"><h1>CARGA</h1><div class="route"><span>${esc(siteName(s.sourceSiteId))}</span><span>→</span><span>${esc(destinationName(s))}</span></div><div class="barcode">${code128Svg(s.code,{height:80,moduleWidth:2})}</div><div class="meta"><span>Traspaso: <b>${esc(s.transferId)}</b></span><span>Paquetes: <b>${s.packageCount||1}</b></span><span>Transportista: <b>${esc(store.data.users.find(u=>u.id===s.transporterUserId)?.name||s.driverName||'Por asignar')}</b></span><span>Sellada: <b>${new Date(s.sealedAt||s.createdAt).toLocaleString('es-CL')}</b></span></div></section></body></html>`;}
function showShipmentLabel(s){let dlg=document.querySelector('#shipment-label-preview');if(!dlg){document.body.insertAdjacentHTML('beforeend',`<dialog id="shipment-label-preview" class="issued-document-preview"><div class="issued-preview-card"><div class="dialog-head"><div><span class="eyebrow">VISTA PREVIA</span><h3>Etiqueta de carga</h3></div><button id="close-shipment-label" class="ghost" type="button">×</button></div><iframe id="shipment-label-frame" title="Vista previa de la etiqueta"></iframe><div class="dialog-actions"><button id="cancel-shipment-label" class="ghost" type="button">Cerrar</button><button id="print-shipment-label" class="primary" type="button">Imprimir / guardar PDF</button></div></div></dialog>`);dlg=document.querySelector('#shipment-label-preview');}const frame=dlg.querySelector('#shipment-label-frame');frame.onload=()=>frame.contentWindow?.scrollTo(0,0);frame.srcdoc=shipmentLabelDocument(s);const close=()=>dlg.close();dlg.querySelector('#close-shipment-label').onclick=close;dlg.querySelector('#cancel-shipment-label').onclick=close;dlg.querySelector('#print-shipment-label').onclick=()=>frame.contentWindow?.print();dlg.showModal();}

let migrationInFlight=false;
function legacyTransfersMissing(){const shipmentTransfers=new Set((store.data.shipments||[]).map(s=>s.transferId));return (store.data.transfers||[]).filter(t=>['LISTO_RETIRO','EN_TRANSITO'].includes(t.status)&&!shipmentTransfers.has(t.id));}
async function migrateTransfers(missing){if(!missing.length)return;await store.commit(d=>{d.shipments=d.shipments||[];for(const source of missing){const t=d.transfers.find(x=>x.id===source.id);if(t&&!d.shipments.some(s=>s.transferId===t.id))ensureLegacyShipment(d,t);}},`${missing.length} transferencia(s) conectadas al control de cargas`);}

export function renderLoads(root){
 const site=activeSiteId(),u=me(),all=(store.data.shipments||[]).filter(s=>s.sourceSiteId===site||s.destinationSiteId===site||u?.role==='TRANSPORTISTA'&&(!s.transporterUserId||s.transporterUserId===u.id)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),pending=all.filter(s=>['LISTA_RETIRO','EN_TRANSITO','LLEGADA_DESTINO'].includes(s.status)),history=all.filter(s=>!pending.includes(s));
 const content=`<div class="page-intro"><div><span class="eyebrow">CARGAS Y CUSTODIA</span><h2>Lo que sale, quién lo lleva y dónde está</h2><p>Cada código representa una carga cerrada. El transportista revisa su contenido antes de aceptar la custodia.</p></div></div><section class="panel shipment-scan-panel"><div><h3>Escanear código de carga</h3><small>También puedes escribir el código impreso debajo de las barras.</small></div><div class="entrada-con-camara"><input id="load-scan-code" placeholder="Ej. CG-TRF000125-AB12" autocomplete="off"><button id="load-scan-camera" class="scan-button" type="button">▣</button></div><button id="load-scan-open" class="primary" type="button">Abrir carga</button></section><section class="panel"><div class="panel-head"><div><h3>Cargas activas</h3><small>Listas para retiro, en tránsito o recién llegadas.</small></div><span>${pending.length}</span></div><div class="shipment-grid">${pending.length?pending.map(shipmentCard).join(''):empty('Sin cargas activas','Las cargas aparecerán automáticamente al sellar un traspaso.')}</div></section><section class="panel"><div class="panel-head"><div><h3>Historial de cargas</h3></div></div><div class="shipment-grid compact">${history.length?history.slice(0,20).map(shipmentCard).join(''):empty('Sin cargas cerradas','Todavía no hay recepciones finalizadas.')}</div></section>`;
 root.innerHTML=shell('Cargas / Custodia',content,'cargas');wireShell();wireLoads(root);
 const missing=legacyTransfersMissing();if(missing.length&&!migrationInFlight){migrationInFlight=true;queueMicrotask(async()=>{try{await migrateTransfers(missing);if(location.hash.startsWith('#/cargas'))renderLoads(root);}catch(error){toast(error?.message||'No se pudieron conectar las cargas antiguas','warning');}finally{migrationInFlight=false;}});}
}

function wireLoads(root){
 const input=document.querySelector('#load-scan-code');enlazarBotonEscaner('load-scan-camera','load-scan-code',{titulo:'Escanear carga',ayuda:'Apunta a la etiqueta de la carga'});document.querySelector('#load-scan-open').onclick=()=>{const s=shipmentByCode(store.data,input.value);if(!s){toast('No existe una carga con ese código','warning');return;}document.querySelector(`.shipment-card [data-id="${CSS.escape(s.id)}"]`)?.closest('.shipment-card')?.scrollIntoView({behavior:'smooth',block:'center'});};
 document.querySelectorAll('.print-shipment').forEach(b=>b.onclick=()=>showShipmentLabel(store.data.shipments.find(s=>s.id===b.dataset.id)));
 document.querySelectorAll('.save-shipment-driver').forEach(b=>b.onclick=async()=>{const select=document.querySelector(`.shipment-driver[data-id="${CSS.escape(b.dataset.id)}"]`),user=store.data.users.find(u=>u.id===select?.value);if(!user){toast('Selecciona un transportista','warning');return;}await store.commit(d=>{const s=d.shipments.find(x=>x.id===b.dataset.id);s.transporterUserId=user.id;s.driverName=user.name;s.events.push({at:new Date().toISOString(),userId:d.session.userId,message:`Carga asignada a ${user.name}`});const t=d.transfers.find(x=>x.id===s.transferId);if(t){t.transporterUserId=user.id;t.driver=user.name;}},`Carga asignada a ${user.name}`);toast('Transportista asignado','success');renderLoads(root);});
 document.querySelectorAll('.accept-custody').forEach(b=>b.onclick=async()=>{const s=store.data.shipments.find(x=>x.id===b.dataset.id);if(!confirm(`¿Confirmas que revisaste y recibes la custodia de ${s.code}?`))return;try{await store.commit(d=>acceptShipmentCustody(d,d.shipments.find(x=>x.id===s.id),{userId:d.session.userId,driverName:me()?.name}),`Custodia de ${s.code} aceptada`);toast('Carga en tránsito','success');renderLoads(root);}catch(e){toast(e.message,'warning');}});
 document.querySelectorAll('.mark-arrival').forEach(b=>b.onclick=async()=>{const s=store.data.shipments.find(x=>x.id===b.dataset.id),external=s.destinationType==='EXTERNAL'||!s.destinationSiteId;if(!confirm(`¿Confirmar ${external?'entrega':'llegada'} de ${s.code} a ${destinationName(s)}?`))return;try{await store.commit(d=>markShipmentArrival(d,d.shipments.find(x=>x.id===s.id),{userId:d.session.userId}),`Carga ${s.code} ${external?'entregada':'llegó al destino'}`);toast(external?'Entrega externa cerrada':'Llegada registrada; el centro destino ya puede recibir','success');renderLoads(root);}catch(e){toast(e.message,'warning');}});
}
