import { store } from '../../services/store.js';
import { shell,wireShell,toast } from '../../layout/layout.js';
import { esc,badge,empty } from '../../components/ui.js';
import { activeSiteId } from '../../services/stock.js';
import { enlazarBotonEscaner } from '../../services/camara-ui.js';
import { code128Svg } from '../../services/barcode.js';
import { startSilentRefresh } from '../../services/silent-refresh.js';
import { SHIPMENT_STATUS,acceptShipmentCustody,ensureLegacyShipment,markShipmentArrival,shipmentByCode,shipmentOrder } from '../../services/transfer-workflow.js';

function me(){return store.data.users.find(u=>u.id===store.data.session.userId);}
function roleAt(user,siteId=activeSiteId()){return (user?.accessAssignments||[]).find(a=>a.siteId===siteId)?.role||user?.role;}
function manager(){return ['ADMIN_GLOBAL','ADMINISTRADOR','ENCARGADO'].includes(roleAt(me()));}
function siteName(id){return store.data.sites.find(s=>s.id===id)?.name||id||'—';}
function destinationName(s){return s.destinationName||siteName(s.destinationSiteId);}
function productName(code){return store.data.products.find(p=>p.code===code)?.name||code;}
function statusTone(status){return ['RECIBIDA','CERRADA'].includes(status)?'ok':['EN_TRANSITO','LLEGADA_DESTINO','RECIBIDA_DIFERENCIAS'].includes(status)?'warn':'neutral';}
function units(s){return (s.items||[]).reduce((sum,i)=>sum+Number(i.expectedQty||0),0);}
function isTransporter(u=me()){return roleAt(u)==='TRANSPORTISTA';}
function canAcceptCustody(s){const u=me();return isTransporter(u)&&s.transporterUserId===u?.id;}
function canConfirmExternalDelivery(s){return (s.destinationType==='EXTERNAL'||!s.destinationSiteId)&&isTransporter()&&s.transporterUserId===me()?.id&&s.status==='EN_TRANSITO';}
function transporters(){return (store.data.users||[]).filter(u=>u.active!==false&&!['PAUSED','DISABLED','DELETED'].includes(u.accessStatus)&&(u.role==='TRANSPORTISTA'||(u.accessAssignments||[]).some(a=>a.role==='TRANSPORTISTA')));}
function transportOptions(selected=''){return transporters().map(u=>`<option value="${esc(u.id)}" ${u.id===selected?'selected':''}>${esc(u.name)}</option>`).join('');}
function shipmentDocumentNumber(s){const order=shipmentOrder(store.data,s);return s.documentNumber||order?.finalDocumentNumber||order?.externalNumber||s.orderNumber||'';}
function shipmentCard(s){const driver=store.data.users.find(u=>u.id===s.transporterUserId)?.name||s.driverName||'Por asignar',documentNumber=shipmentDocumentNumber(s),hasTransporters=transporters().length>0,assigned=Boolean(s.transporterUserId);return `<article class="shipment-card shipment-card-compact" data-shipment-id="${esc(s.id)}"><div class="shipment-card-head"><div><span class="eyebrow">${esc(s.code)}</span><h3>${esc(siteName(s.sourceSiteId))} → ${esc(destinationName(s))}</h3><small>${s.packageCount||1} paquete(s) · ${s.items.length} producto(s) · ${units(s)} unidades</small>${documentNumber?`<small>Documento / orden: <b>${esc(documentNumber)}</b></small>`:''}${s.destinationType==='EXTERNAL'?`<small>${esc(s.destinationAddress||'Sin dirección')} · Recibe: ${esc(s.destinationContact||'Sin contacto')}</small>`:''}</div>${badge(SHIPMENT_STATUS[s.status]||s.status,statusTone(s.status))}</div><div class="shipment-meta"><span>Transportista: <b>${esc(driver)}</b></span><span>Traspaso: <b>${esc(s.transferId)}</b></span></div><details class="shipment-details"><summary><span>Contenido de la carga</span><strong>Mostrar</strong></summary><div class="shipment-manifest">${s.items.map(i=>`<span><b>${esc(i.code)}</b><small>${esc(productName(i.code))}</small><strong>${i.expectedQty}</strong></span>`).join('')}</div></details><div class="shipment-actions">${manager()&&s.status==='LISTA_RETIRO'&&!assigned?`<select class="shipment-driver" data-id="${esc(s.id)}" ${hasTransporters?'':'disabled'}><option value="">${hasTransporters?'Asignar transportista…':'No hay usuarios con rol Transportista'}</option>${transportOptions()}</select><button class="secondary save-shipment-driver" data-id="${esc(s.id)}" type="button" ${hasTransporters?'':'disabled'}>Guardar asignación</button>${hasTransporters?'':'<small>Crea o edita un usuario y asígnale el rol Transportista en Administración → Usuarios.</small>'}`:''}${s.status==='LISTA_RETIRO'&&assigned?`<span class="shipment-assigned-confirmation">✓ Asignada a <b>${esc(driver)}</b> · pendiente de aceptar custodia</span>`:''}<button class="ghost print-shipment" data-id="${esc(s.id)}" type="button">Imprimir etiqueta</button>${canAcceptCustody(s)&&s.status==='LISTA_RETIRO'?`<button class="primary accept-custody" data-id="${esc(s.id)}" type="button">Aceptar custodia</button>`:''}${canConfirmExternalDelivery(s)?`<button class="primary mark-arrival" data-id="${esc(s.id)}" type="button">Confirmar entrega</button>`:''}</div>${s.status==='EN_TRANSITO'&&s.destinationSiteId?`<small class="shipment-flow-note">La recepción continúa exclusivamente en ${esc(destinationName(s))} desde Recepción → Recibir traspasos.</small>`:''}</article>`;}
export function shipmentLabelDocument(s){const documentNumber=shipmentDocumentNumber(s);return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(s.code)}</title><style>@page{size:A4;margin:14mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;padding:18px;color:#07111f;margin:0}.label{border:3px solid #07111f;border-radius:18px;padding:24px}.label h1{margin:0 0 18px}.route{display:flex;justify-content:space-between;align-items:center;gap:18px;font-size:20px;font-weight:800}.reference{margin:18px 0 0;font-size:16px}.barcode{margin:18px 0}.barcode svg{width:100%;height:135px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding-top:16px;border-top:1px solid #bbb}@media(max-width:600px){body{padding:8px}.label{padding:14px}.route{display:grid;font-size:16px}.meta{grid-template-columns:1fr}}@media print{body{padding:0}.label{break-inside:avoid}}</style></head><body><section class="label"><h1>CARGA</h1><div class="route"><span>${esc(siteName(s.sourceSiteId))}</span><span>→</span><span>${esc(destinationName(s))}</span></div>${documentNumber?`<div class="reference">Documento / orden: <b>${esc(documentNumber)}</b></div>`:''}<div class="barcode">${code128Svg(documentNumber||s.code,{height:80,moduleWidth:2})}</div><div class="meta"><span>Carga: <b>${esc(s.code)}</b></span><span>Traspaso: <b>${esc(s.transferId)}</b></span><span>Paquetes: <b>${s.packageCount||1}</b></span><span>Transportista: <b>${esc(store.data.users.find(u=>u.id===s.transporterUserId)?.name||s.driverName||'Por asignar')}</b></span><span>Sellada: <b>${new Date(s.sealedAt||s.createdAt).toLocaleString('es-CL')}</b></span></div></section></body></html>`;}
function showShipmentLabel(s){let dlg=document.querySelector('#shipment-label-preview');if(!dlg){document.body.insertAdjacentHTML('beforeend',`<dialog id="shipment-label-preview" class="issued-document-preview"><div class="issued-preview-card"><div class="dialog-head"><div><span class="eyebrow">VISTA PREVIA</span><h3>Etiqueta de carga</h3></div><button id="close-shipment-label" class="ghost" type="button">×</button></div><iframe id="shipment-label-frame" title="Vista previa de la etiqueta"></iframe><div class="dialog-actions"><button id="cancel-shipment-label" class="ghost" type="button">Cerrar</button><button id="print-shipment-label" class="primary" type="button">Imprimir / guardar PDF</button></div></div></dialog>`);dlg=document.querySelector('#shipment-label-preview');}const frame=dlg.querySelector('#shipment-label-frame');frame.onload=()=>frame.contentWindow?.scrollTo(0,0);frame.srcdoc=shipmentLabelDocument(s);const close=()=>dlg.close();dlg.querySelector('#close-shipment-label').onclick=close;dlg.querySelector('#cancel-shipment-label').onclick=close;dlg.querySelector('#print-shipment-label').onclick=()=>frame.contentWindow?.print();dlg.showModal();}

let migrationInFlight=false;
function legacyTransfersMissing(){const shipmentTransfers=new Set((store.data.shipments||[]).map(s=>s.transferId));return (store.data.transfers||[]).filter(t=>['LISTO_RETIRO','EN_TRANSITO'].includes(t.status)&&!shipmentTransfers.has(t.id));}
async function migrateTransfers(missing){if(!missing.length)return;await store.commit(d=>{d.shipments=d.shipments||[];for(const source of missing){const t=d.transfers.find(x=>x.id===source.id);if(t&&!d.shipments.some(s=>s.transferId===t.id))ensureLegacyShipment(d,t);}},`${missing.length} transferencia(s) conectadas al control de cargas`);}
async function assignTransporterSafely(shipmentId,user){
 for(let attempt=0;attempt<2;attempt++){
  try{
   const current=store.data.shipments.find(s=>s.id===shipmentId);
   if(!current)throw new Error('La carga ya no existe. Actualiza la vista.');
   if(current.transporterUserId&&current.transporterUserId!==user.id)throw new Error('La carga ya fue asignada a otro transportista.');
   if(current.transporterUserId===user.id)return current;
   await store.commit(d=>{const s=d.shipments.find(x=>x.id===shipmentId);if(!s)throw new Error('La carga ya no existe. Actualiza la vista.');if(s.transporterUserId&&s.transporterUserId!==user.id)throw new Error('La carga ya fue asignada a otro transportista.');s.transporterUserId=user.id;s.driverName=user.name;s.events=s.events||[];s.events.push({at:new Date().toISOString(),userId:d.session.userId,message:`Carga asignada a ${user.name}`});const t=(d.transfers||[]).find(x=>x.id===s.transferId);if(t){t.transporterUserId=user.id;t.driver=user.name;}},`Carga asignada a ${user.name}`);
   return store.data.shipments.find(s=>s.id===shipmentId);
  }catch(error){
   if(attempt===0&&(error?.status===409||error?.code==='REVISION_CONFLICT')){await store.reload({emit:false});continue;}
   throw error;
  }
 }
}

export function renderLoads(root){
 const site=activeSiteId(),u=me(),transporter=isTransporter(u),all=(store.data.shipments||[]).filter(s=>transporter?s.transporterUserId===u?.id:s.sourceSiteId===site||s.destinationSiteId===site).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),pending=all.filter(s=>['LISTA_RETIRO','EN_TRANSITO','LLEGADA_DESTINO'].includes(s.status)),history=all.filter(s=>!pending.includes(s));
 const content=`<div class="page-intro"><div><span class="eyebrow">CARGAS Y CUSTODIA</span><h2>Lo que sale, quién lo lleva y dónde está</h2><p>${transporter?'Aquí aparecen exclusivamente las cargas asignadas a tu custodia.':'Cada código representa una carga cerrada. El transportista revisa su contenido antes de aceptar la custodia.'}</p></div></div><section class="panel shipment-scan-panel"><div><h3>Escanear código de carga</h3><small>También puedes escribir el código impreso debajo de las barras.</small></div><div class="entrada-con-camara"><input id="load-scan-code" placeholder="Ej. CG-TRF000125-AB12" autocomplete="off"><button id="load-scan-camera" class="scan-button" type="button">▣</button></div><button id="load-scan-open" class="primary" type="button">Abrir carga</button></section><details class="panel load-section-toggle" open><summary><span><b>Cargas por custodiar</b><small>Listas para retiro, en tránsito o recién llegadas.</small></span><span><strong>${pending.length}</strong><i>⌄</i></span></summary><div class="shipment-grid">${pending.length?pending.map(shipmentCard).join(''):empty('Sin cargas activas','No tienes cargas pendientes de custodia.')}</div></details><details class="panel load-section-toggle"><summary><span><b>Historial de cargas</b><small>Cargas ya finalizadas.</small></span><span><strong>${history.length}</strong><i>⌄</i></span></summary><div class="shipment-grid compact">${history.length?history.slice(0,20).map(shipmentCard).join(''):empty('Sin cargas cerradas','Todavía no hay cargas finalizadas.')}</div></details>`;
 root.innerHTML=shell('Cargas / Custodia',content,'cargas');wireShell();wireLoads(root);
 startSilentRefresh('loads','#/cargas',()=>renderLoads(root),{collections:['shipments','transfers']});
 const missing=legacyTransfersMissing();if(missing.length&&!migrationInFlight){migrationInFlight=true;queueMicrotask(async()=>{try{await migrateTransfers(missing);if(location.hash.startsWith('#/cargas'))renderLoads(root);}catch(error){toast(error?.message||'No se pudieron conectar las cargas antiguas','warning');}finally{migrationInFlight=false;}});}
}

function wireLoads(root){
 const input=document.querySelector('#load-scan-code');enlazarBotonEscaner('load-scan-camera','load-scan-code',{titulo:'Escanear carga',ayuda:'Apunta a la etiqueta de la carga'});document.querySelector('#load-scan-open').onclick=()=>{const s=shipmentByCode(store.data,input.value);if(!s){toast('No existe una carga con ese código o traspaso','warning');return;}const card=document.querySelector(`.shipment-card[data-shipment-id="${CSS.escape(s.id)}"]`);if(!card){toast('La carga existe, pero no pertenece al centro o usuario activo','warning');return;}card.classList.add('search-focus');card.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>card.classList.remove('search-focus'),3000);};
 document.querySelectorAll('.shipment-details').forEach(d=>d.addEventListener('toggle',()=>{const label=d.querySelector('summary strong');if(label)label.textContent=d.open?'Ocultar':'Mostrar';}));
 document.querySelectorAll('.print-shipment').forEach(b=>b.onclick=()=>showShipmentLabel(store.data.shipments.find(s=>s.id===b.dataset.id)));
 document.querySelectorAll('.save-shipment-driver').forEach(b=>b.onclick=async()=>{const select=document.querySelector(`.shipment-driver[data-id="${CSS.escape(b.dataset.id)}"]`),user=store.data.users.find(u=>u.id===select?.value);if(!user){toast('Selecciona un transportista','warning');return;}const original=b.textContent;b.disabled=true;b.textContent='Guardando…';try{const shipmentId=b.dataset.id;await assignTransporterSafely(shipmentId,user);await store.reload({emit:false});const saved=store.data.shipments.find(s=>s.id===shipmentId);if(saved?.transporterUserId!==user.id)throw new Error('No fue posible verificar la asignación guardada.');toast(`Carga asignada a ${user.name}`,'success');renderLoads(root);}catch(error){b.disabled=false;b.textContent=original;toast(error.message||'No fue posible guardar la asignación','warning');}});
 document.querySelectorAll('.accept-custody').forEach(b=>b.onclick=async()=>{const s=store.data.shipments.find(x=>x.id===b.dataset.id);if(!confirm(`¿Confirmas que revisaste y recibes la custodia de ${s.code}?`))return;try{const assignedName=store.data.users.find(u=>u.id===s.transporterUserId)?.name||s.driverName;await store.commit(d=>acceptShipmentCustody(d,d.shipments.find(x=>x.id===s.id),{userId:d.session.userId,driverName:assignedName}),`Custodia de ${s.code} aceptada por ${assignedName}`);toast('Carga en tránsito','success');renderLoads(root);}catch(e){toast(e.message,'warning');}});
 document.querySelectorAll('.mark-arrival').forEach(b=>b.onclick=async()=>{const s=store.data.shipments.find(x=>x.id===b.dataset.id),external=s.destinationType==='EXTERNAL'||!s.destinationSiteId;if(!confirm(`¿Confirmar ${external?'entrega':'llegada'} de ${s.code} a ${destinationName(s)}?`))return;try{await store.commit(d=>markShipmentArrival(d,d.shipments.find(x=>x.id===s.id),{userId:d.session.userId}),`Carga ${s.code} ${external?'entregada':'llegó al destino'}`);toast(external?'Entrega externa cerrada':'Llegada registrada; el centro destino ya puede recibir','success');renderLoads(root);}catch(e){toast(e.message,'warning');}});
}
