import { shell,wireShell,toast } from '../../layout/layout.js';
import { store } from '../../services/store.js';
import { activeSiteId,stockBySite } from '../../services/stock.js';
import { auth } from '../../services/auth.js';
import { esc } from '../../components/ui.js';

const clean=v=>String(v??'').trim();
const safeName=v=>clean(v||'centro').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_-]+/gi,'_');
const xml=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
function currentUser(d=store.data){return (d.users||[]).find(u=>u.id===d.session?.userId)||auth.user;}
function roleAt(user,siteId){return (user?.accessAssignments||[]).find(a=>a.siteId===siteId)?.role||user?.role;}
function canManage(user,siteId){return ['ADMIN_GLOBAL','ADMINISTRADOR','ENCARGADO'].includes(roleAt(user,siteId));}
function limits(d=store.data){d.planning=d.planning||{};d.planning.stockAlertLimits=d.planning.stockAlertLimits||{};return d.planning.stockAlertLimits;}
function limitFor(siteId,productCode,d=store.data){return Math.max(0,Number(limits(d)?.[siteId]?.[productCode]||0));}
function qtyFor(siteId,code,d=store.data){return Number(stockBySite(code,d)[siteId]||0);}
function statusFor(qty,limit){return !limit?'SIN_CONFIGURAR':qty<=0?'QUIEBRE':qty<=limit?'BAJO':'NORMAL';}
function snapshot(siteId,d=store.data){
 const site=(d.sites||[]).find(s=>s.id===siteId),rows=(d.products||[]).map(p=>{const limit=limitFor(siteId,p.code,d),qty=qtyFor(siteId,p.code,d);return {code:p.code,name:p.name||p.description||p.code,qty,limit,status:statusFor(qty,limit)};});
 const configured=rows.filter(r=>r.limit>0),alerts=configured.filter(r=>r.status==='BAJO'||r.status==='QUIEBRE');
 return {site,rows,configured,alerts,low:alerts.filter(r=>r.status==='BAJO').length,breaks:alerts.filter(r=>r.status==='QUIEBRE').length};
}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove();},1200);}
function pdfText(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'?').replace(/([\\()])/g,'\\$1');}
function makePdf(s){
 const W=595,H=842,margin=42,rowH=23;let pages=[],page=[],y=H-45;
 const cmd=(txt,x,yy,size=9,bold=false)=>page.push(`BT /F${bold?2:1} ${size} Tf ${x} ${yy} Td (${pdfText(txt)}) Tj ET`);
 const line=(x1,y1,x2,y2)=>page.push(`${x1} ${y1} m ${x2} ${y2} l S`);
 const newPage=()=>{if(page.length)pages.push(page);page=['0.08 0.20 0.23 rg','0 790 595 52 re f','0 0 0 rg'];cmd('KHAL  |  ALERTAS DE STOCK',margin,813,17,true);cmd(`${s.site?.name||s.site?.id||''}  -  ${new Date().toLocaleString('es-CL')}`,margin,793,8,false);y=758;cmd(`QUIEBRE: ${s.breaks}    POCO STOCK: ${s.low}    TOTAL ALERTAS: ${s.alerts.length}`,margin,y,11,true);y-=28;page.push('0.05 0.42 0.46 rg');page.push(`${margin} ${y-5} 511 24 re f`);page.push('1 1 1 rg');cmd('SKU',margin+8,y+3,9,true);cmd('PRODUCTO',margin+112,y+3,9,true);cmd('STOCK',margin+365,y+3,9,true);cmd('LIMITE',margin+418,y+3,9,true);cmd('ESTADO',margin+466,y+3,9,true);page.push('0 0 0 rg');y-=27;};
 newPage();
 for(const r of s.alerts){if(y<60){newPage();}cmd(r.code,margin+8,y,8,true);cmd(String(r.name).slice(0,42),margin+112,y,8,false);cmd(r.qty,margin+365,y,8,true);cmd(r.limit,margin+418,y,8,false);cmd(r.status==='QUIEBRE'?'QUIEBRE':'POCO STOCK',margin+466,y,7,true);line(margin,y-7,553,y-7);y-=rowH;}
 if(!s.alerts.length)cmd('No hay productos en quiebre o bajo el limite configurado.',margin,y,10,false);pages.push(page);
 const objects=['<< /Type /Catalog /Pages 2 0 R >>',`<< /Type /Pages /Kids [${pages.map((_,i)=>`${5+i*2} 0 R`).join(' ')}] /Count ${pages.length} >>`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'];
 pages.forEach((commands,i)=>{const stream=commands.join('\n');objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${6+i*2} 0 R >>`);objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);});
 let out='%PDF-1.4\n',offset=[0];objects.forEach((o,i)=>{offset.push(out.length);out+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=out.length;out+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objects.length;i++)out+=`${String(offset[i]).padStart(10,'0')} 00000 n \n`;out+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([out],{type:'application/pdf'});
}
async function exportExcel(s){
 if(!window.JSZip)throw new Error('Generador Excel no disponible.');const zip=new window.JSZip();
 const rows=[['KHAL  |  ALERTAS DE STOCK'],[`CENTRO: ${s.site?.name||s.site?.id||''}`],['Fecha',new Date().toLocaleString('es-CL'),'Quiebre',s.breaks,'Poco stock',s.low],[],['SKU','Producto','Stock actual','Límite de alerta','Estado'],...s.alerts.map(r=>[r.code,r.name,r.qty,r.limit,r.status==='QUIEBRE'?'QUIEBRE':'POCO STOCK'])];
 const col=i=>{let v='';for(i++;i;i=Math.floor((i-1)/26))v=String.fromCharCode(65+(i-1)%26)+v;return v;};
 const cell=(v,ri,ci)=>{const num=typeof v==='number',style=ri===0?1:ri===1?2:ri===4?3:ri>=5?(ri%2?4:5):6;return `<c r="${col(ci)}${ri+1}" s="${style}" ${num?'':'t="inlineStr"'}>${num?`<v>${v}</v>`:`<is><t>${xml(v)}</t></is>`}</c>`;};
 const last=Math.max(5,rows.length),sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="5" topLeftCell="A6" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="1" width="22" customWidth="1"/><col min="2" max="2" width="55" customWidth="1"/><col min="3" max="4" width="18" customWidth="1"/><col min="5" max="5" width="20" customWidth="1"/></cols><sheetData>${rows.map((r,ri)=>`<row r="${ri+1}" ht="${ri===0?34:ri===4?26:22}" customHeight="1">${r.map((v,ci)=>cell(v,ri,ci)).join('')}</row>`).join('')}</sheetData><mergeCells count="2"><mergeCell ref="A1:E1"/><mergeCell ref="A2:E2"/></mergeCells><autoFilter ref="A5:E${last}"/><pageSetup orientation="portrait" paperSize="9" fitToWidth="1"/></worksheet>`;
 const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="4"><font><sz val="10"/><name val="Aptos"/></font><font><b/><sz val="18"/><color rgb="FFFFFFFF"/></font><font><b/><sz val="12"/><color rgb="FF0C5962"/></font><font><b/><sz val="10"/><color rgb="FFFFFFFF"/></font></fonts><fills count="5"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF12343B"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FF0E6973"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF0F5F6"/></patternFill></fill></fills><borders count="2"><border/><border><bottom style="hair"><color rgb="FFD9E4E6"/></bottom></border></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="7"><xf/><xf fontId="1" fillId="2" applyAlignment="1"><alignment vertical="center"/></xf><xf fontId="2" fillId="4"/><xf fontId="3" fillId="3" applyAlignment="1"><alignment vertical="center"/></xf><xf fontId="0" fillId="0" borderId="1"/><xf fontId="0" fillId="4" borderId="1"/><xf fontId="0" fillId="0"/></cellXfs></styleSheet>`;
 zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');zip.folder('xl').file('workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Alertas de stock" sheetId="1" r:id="rId1"/></sheets></workbook>').file('styles.xml',styles).folder('_rels').file('workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');zip.folder('xl').folder('worksheets').file('sheet1.xml',sheet);
 download(await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`Khal_alertas_stock_${safeName(s.site?.name||s.site?.id)}.xlsx`);
}
export function stockAlertCount(siteId=activeSiteId(store.data),d=store.data){return snapshot(siteId,d).alerts.length;}
export function renderStockAlerts(root){
 const d=store.data,siteId=activeSiteId(d),user=currentUser(d),site=(d.sites||[]).find(s=>s.id===siteId),manager=canManage(user,siteId);if(!manager){location.hash='#/dashboard';return;}
 const s=snapshot(siteId,d);
 root.innerHTML=shell('Alertas de stock',`<div class="page-intro stock-alert-intro"><div><span class="eyebrow">CONTROL DE EXISTENCIAS</span><h2>Alertas de stock · ${esc(site?.name||siteId)}</h2><p>Define un límite por producto para este centro. Khal solo observa el stock existente; esta pantalla no modifica existencias.</p></div><div class="stock-alert-actions"><button id="stock-alert-excel" class="secondary">Descargar Excel</button><button id="stock-alert-pdf" class="primary">Descargar PDF</button></div></div>
 <section class="stock-alert-summary"><article><small>QUIEBRE</small><b class="danger">${s.breaks}</b><span>productos configurados en 0</span></article><article><small>POCO STOCK</small><b class="warning">${s.low}</b><span>por debajo del límite</span></article><article><small>ALERTAS ACTIVAS</small><b>${s.alerts.length}</b><span>requieren revisión</span></article></section>
 <section class="panel stock-alert-toolbar"><label>Buscar producto<input id="stock-alert-search" type="search" placeholder="SKU o descripción" autocomplete="off"></label><label>Ver<select id="stock-alert-filter"><option value="TODOS">Todos los productos</option><option value="ALERTAS">Solo alertas</option><option value="CONFIGURADOS">Solo configurados</option><option value="SIN_CONFIGURAR">Sin límite</option></select></label><div class="stock-alert-bulk"><label>Límite para seleccionados<input id="stock-alert-bulk-limit" type="number" min="0" step="1" placeholder="Ej. 100"></label><button id="stock-alert-apply" class="secondary" type="button">Aplicar a seleccionados</button></div></section>
 <div class="table-wrap stock-alert-table"><table><thead><tr><th><input id="stock-alert-all" type="checkbox" aria-label="Seleccionar visibles"></th><th>SKU</th><th>Producto</th><th>Stock actual</th><th>Límite</th><th>Estado</th><th></th></tr></thead><tbody id="stock-alert-body"></tbody></table></div>`,'alertas-stock');wireShell();
 const body=document.querySelector('#stock-alert-body'),search=document.querySelector('#stock-alert-search'),filter=document.querySelector('#stock-alert-filter');
 function visibleRows(){const q=clean(search.value).toLowerCase();return snapshot(siteId).rows.filter(r=>(!q||`${r.code} ${r.name}`.toLowerCase().includes(q))&&(filter.value==='TODOS'||filter.value==='ALERTAS'&&['BAJO','QUIEBRE'].includes(r.status)||filter.value==='CONFIGURADOS'&&r.limit>0||filter.value==='SIN_CONFIGURAR'&&!r.limit));}
 function paint(){body.innerHTML=visibleRows().map(r=>`<tr class="stock-alert-row ${r.status.toLowerCase()}"><td><input class="stock-alert-check" type="checkbox" data-code="${esc(r.code)}"></td><td><b>${esc(r.code)}</b></td><td>${esc(r.name)}</td><td class="num"><b>${r.qty}</b></td><td><input class="stock-alert-limit" data-code="${esc(r.code)}" type="number" min="0" step="1" value="${r.limit||''}" placeholder="Sin alerta"></td><td><span class="stock-alert-status ${r.status.toLowerCase()}">${r.status==='QUIEBRE'?'Quiebre':r.status==='BAJO'?'Poco stock':r.status==='NORMAL'?'Normal':'Sin configurar'}</span></td><td><button class="ghost small stock-alert-save" data-code="${esc(r.code)}">Guardar</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty-state">No hay productos para este filtro.</td></tr>';document.querySelector('#stock-alert-all').checked=false;}
 async function save(entries){if(!entries.length)return;await store.commit(st=>{st.planning=st.planning||{};st.planning.stockAlertLimits=st.planning.stockAlertLimits||{};st.planning.stockAlertLimits[siteId]=st.planning.stockAlertLimits[siteId]||{};for(const [code,value] of entries){const n=Math.max(0,Math.floor(Number(value)||0));if(n>0)st.planning.stockAlertLimits[siteId][code]=n;else delete st.planning.stockAlertLimits[siteId][code];}},`Límites de alerta de stock actualizados en ${site?.name||siteId}`);toast('Límite de stock guardado','success');renderStockAlerts(root);}
 body.onclick=e=>{const b=e.target.closest('.stock-alert-save');if(!b)return;const input=body.querySelector(`.stock-alert-limit[data-code="${CSS.escape(b.dataset.code)}"]`);save([[b.dataset.code,input?.value]]).catch(err=>toast(err.message));};
 search.oninput=paint;filter.onchange=paint;document.querySelector('#stock-alert-all').onchange=e=>document.querySelectorAll('.stock-alert-check').forEach(c=>c.checked=e.target.checked);
 document.querySelector('#stock-alert-apply').onclick=()=>{const selected=[...document.querySelectorAll('.stock-alert-check:checked')].map(c=>c.dataset.code),value=document.querySelector('#stock-alert-bulk-limit').value;if(!selected.length){toast('Selecciona al menos un producto');return;}if(value===''||Number(value)<0){toast('Indica un límite válido');return;}save(selected.map(code=>[code,value])).catch(err=>toast(err.message));};
 document.querySelector('#stock-alert-excel').onclick=()=>exportExcel(snapshot(siteId)).catch(err=>toast(err.message));document.querySelector('#stock-alert-pdf').onclick=()=>{const snap=snapshot(siteId);download(makePdf(snap),`Khal_alertas_stock_${safeName(snap.site?.name||siteId)}.pdf`);};paint();
}
