import { store } from '../../services/store.js';
import { shell,wireShell,toast } from '../../layout/layout.js';
import { esc,badge,empty } from '../../components/ui.js';
import { enlazarBotonEscaner } from '../../services/camara-ui.js';

function pname(c){return store.data.products.find(p=>p.code===c)?.name||c;}
function uname(id){return store.data.users.find(u=>u.id===id)?.name||id||'No registrado';}
function userOpts(){return store.data.users.filter(u=>u.active).map(u=>`<option value="${esc(u.id)}">${esc(u.name)}</option>`).join('');}
function available(code){return store.data.inventory.filter(i=>i.productCode===code&&i.qty>0).reduce((a,b)=>a+b.qty,0);}
function openTransfer(){return store.data.transfers.find(t=>['PREPARANDO','LISTO'].includes(t.status));}

export function renderTransfers(root){
 const d=store.data,t=openTransfer(),productOpts=d.products.map(p=>`<option value="${esc(p.code)}">${esc(p.name)}</option>`).join('');
 root.innerHTML=shell('Despacho / Tránsito',`<div class="page-intro"><div><span class="eyebrow">SALIDA CONTROLADA</span><h2>Preparar, escanear y saber qué va en camino</h2><p>Por ahora la salida nace en Recoleta. Cuando activemos la bodega de ventas, el mismo documento podrá ser recibido allí y cerrar el tránsito.</p></div>${t?'':`<button id="new-transfer" class="primary">+ Nueva salida</button>`}</div>
 ${t?`<section class="panel"><div class="panel-head"><div><span class="eyebrow">${esc(t.status)}</span><h3>${esc(t.id)} · Recoleta → ${esc(t.destinationName)}</h3><small>Conductor: ${esc(t.driver||'Por asignar')}</small></div>${badge(t.status,t.status==='LISTO'?'ok':'warn')}</div>
 <form id="add-transfer-item" class="quick-scan"><label>Código / escaneo<div class="entrada-con-camara"><input id="tr-code" list="transfer-products" required placeholder="Escanea o escribe código"><button id="camara-tr-code" class="scan-button" type="button" title="Escanear código con cámara" aria-label="Escanear código con cámara">▣</button></div><datalist id="transfer-products">${productOpts}</datalist></label><label>Cantidad<input id="tr-qty" type="number" min="1" value="1" required></label><button class="primary">Agregar</button></form>
 <div class="scan-list">${(t.items||[]).length?t.items.map((x,i)=>`<div class="scan-row"><div><b>${esc(x.code)}</b><small>${esc(pname(x.code))}</small></div><strong>${x.qty}</strong><button class="ghost tr-remove" data-i="${i}">×</button></div>`).join(''):empty('Salida vacía','Agrega los productos que retirará el conductor.')}</div>
 <div class="transfer-actions transfer-actions-grid"><label>Supervisado / revisado por<select id="tr-supervisor"><option value="">Seleccionar…</option>${userOpts()}</select></label><button id="mark-transit" class="primary">Confirmar despacho → EN TRÁNSITO</button></div></section>`:`<section class="panel">${empty('Sin salida en preparación','Crea una salida cuando la tienda o la bodega de ventas venga a retirar productos.')}</section>`}
 <section class="panel"><div class="panel-head"><div><h3>Transferencias / salidas recientes</h3><small>Fecha y responsables del despacho</small></div></div>${d.transfers.length?d.transfers.slice(0,10).map(x=>`<div class="history-row"><div class="hist-icon">⇄</div><div><b>${esc(x.id)} · ${esc(x.destinationName)}</b><small>${esc(x.status)} · ${(x.items||[]).reduce((a,b)=>a+b.qty,0)} unidades</small><small>Despachó: ${esc(uname(x.dispatchedBy||x.scannedBy))} · Supervisó: ${esc(uname(x.supervisedBy))} · Conductor: ${esc(x.driver||'No registrado')}</small></div><time>${new Date(x.departedAt||x.createdAt).toLocaleString('es-CL')}</time></div>`).join(''):empty('Sin transferencias','Las salidas registradas aparecerán aquí.')}</section>
 <dialog id="transfer-dialog"><form method="dialog"><div class="dialog-head"><h3>Nueva salida</h3><button value="cancel" class="ghost">×</button></div><label>Destino<select id="tr-dest"><option value="TIENDA">Bodega tienda de ventas</option><option value="OTRO">Otro / pendiente</option></select></label><label>Conductor / quien retira<input id="tr-driver" placeholder="Nombre"></label><div class="dialog-actions"><button value="cancel" class="ghost">Cancelar</button><button id="create-transfer" value="default" class="primary">Crear salida</button></div></form></dialog>`,'transferencias');
 wireShell();
 if(!t){
   const dlg=document.querySelector('#transfer-dialog');document.querySelector('#new-transfer').onclick=()=>dlg.showModal();
   document.querySelector('#create-transfer').onclick=async(e)=>{e.preventDefault();const idx=d.transfers.length+1,id=`TRF-${String(idx).padStart(6,'0')}`,dest=document.querySelector('#tr-dest').value,driver=document.querySelector('#tr-driver').value.trim(),destinationName=dest==='TIENDA'?'Bodega tienda de ventas':'Otro destino',now=new Date().toISOString();await store.commit(s=>s.transfers.unshift({id,sourceSiteId:'REC',destinationSiteId:dest,destinationName,driver,status:'PREPARANDO',createdAt:now,items:[],supervisedBy:null,dispatchedBy:null}),`Salida ${id} creada`);dlg.close();toast('Salida creada');renderTransfers(root);};
 }else{
   enlazarBotonEscaner('camara-tr-code','tr-code',{titulo:'Escanear producto para despacho',ayuda:'Apunta al código de barras del producto'});
   document.querySelector('#add-transfer-item').onsubmit=async(e)=>{e.preventDefault();const code=document.querySelector('#tr-code').value.trim(),qty=Number(document.querySelector('#tr-qty').value),avail=available(code);if(!store.data.products.some(p=>p.code===code)){toast('Código no registrado');return;}if(qty>avail){toast(`Solo hay ${avail} unidades localizadas`);return;}await store.commit(s=>{const tt=s.transfers.find(x=>x.id===t.id),it=tt.items.find(x=>x.code===code);if(it)it.qty+=qty;else tt.items.push({code,qty});},`Producto ${code} agregado a ${t.id}`);renderTransfers(root);};
   document.querySelectorAll('.tr-remove').forEach(b=>b.onclick=async()=>{await store.commit(s=>s.transfers.find(x=>x.id===t.id).items.splice(Number(b.dataset.i),1),`Producto retirado de ${t.id}`);renderTransfers(root);});
   document.querySelector('#mark-transit').onclick=async()=>{const supervisedBy=document.querySelector('#tr-supervisor').value;if(!(t.items||[]).length){toast('Agrega productos antes de despachar');return;}if(!supervisedBy){toast('Selecciona quién revisó el despacho');return;}for(const it of t.items){if(it.qty>available(it.code)){toast(`Existencias insuficientes para ${it.code}`);return;}}const now=new Date().toISOString();await store.commit(s=>{const tt=s.transfers.find(x=>x.id===t.id);for(const it of tt.items){let need=it.qty;for(const inv of s.inventory.filter(i=>i.productCode===it.code&&i.qty>0)){const take=Math.min(inv.qty,need);inv.qty-=take;need-=take;if(!need)break;}s.inventory=s.inventory.filter(i=>i.qty>0);}tt.status='EN_TRANSITO';tt.departedAt=now;tt.scannedBy=s.session.userId;tt.dispatchedBy=s.session.userId;tt.supervisedBy=supervisedBy;},`Transferencia ${t.id} salió EN TRÁNSITO`);toast('Salida registrada EN TRÁNSITO');renderTransfers(root);};
 }
}
