import { store } from '../../services/store.js';
import { shell,wireShell,toast } from '../../layout/layout.js';
import { esc,badge,empty } from '../../components/ui.js';
import { parseXlsx,normalizeHeader } from '../../services/xlsx-reader.js';
import { resolveProduct,productAliases } from '../../services/product-codes.js';
import { stockBySite,stockStatus,inventorySiteId } from '../../services/stock.js';
import { activeCompanyId,siteCompanyId } from '../../services/company.js';
import { enlazarBotonEscaner } from '../../services/camara-ui.js';

let preview=null;let liveTimer=null;
function me(){return store.data.users.find(u=>u.id===store.data.session.userId);}
function isManager(){return ['ADMINISTRADOR','ENCARGADO'].includes(me()?.role);}
function operators(){return (store.data.users||[]).filter(u=>u.active!==false&&['OPERADOR_BODEGA','OPERADOR_RECEPCION','ENCARGADO'].includes(u.role)&&(!(u.siteIds||[]).length||(u.siteIds||[]).some(id=>store.data.sites.find(s=>s.id===id)?.companyId===activeCompanyId())));}
function statusLabel(s){return ({RECIBIDA:'Recibida',ACEPTADA:'Aceptada',ASIGNADA:'Asignada',EN_PICKING:'En picking',PREPARADA:'Preparada',ENTREGADA_CONDUCTOR:'Entregada al conductor',CERRADA:'Cerrada'}[s]||s);}
function statusTone(s){return s==='CERRADA'||s==='ENTREGADA_CONDUCTOR'?'ok':s==='EN_PICKING'?'warn':'neutral';}
function progress(o){const total=(o.items||[]).length,done=(o.items||[]).filter(i=>Number(i.pickedQty||0)>=Number(i.qty||0)).length;return {total,done,pct:total?Math.round(done*100/total):0};}
function siteName(id){return store.data.sites.find(s=>s.id===id)?.name||id||'—';}
function userName(id){return store.data.users.find(u=>u.id===id)?.name||'Sin asignar';}
function visibleOrders(){const u=me(),company=activeCompanyId();const sameCompany=o=>siteCompanyId(store.data.sites.find(s=>s.id===o.sourceSiteId))===company;if(isManager())return (store.data.orders||[]).filter(sameCompany);return (store.data.orders||[]).filter(o=>o.assignedTo===u?.id&&sameCompany(o));}

function itemAvailability(o,it){
 const origin=stockStatus(it.productCode,o.sourceSiteId,store.data,o.id),requested=Number(it.qty||0),shortage=Math.max(0,requested-origin.available);
 const others=(store.data.sites||[]).filter(s=>s.id!==o.sourceSiteId&&siteCompanyId(s)===siteCompanyId(store.data.sites.find(x=>x.id===o.sourceSiteId))&&s.active!==false).map(s=>({site:s,...stockStatus(it.productCode,s.id,store.data)})).filter(x=>x.available>0).sort((a,b)=>b.available-a.available);
 return {origin,requested,shortage,others};
}
function availabilityHtml(o){
 const blocks=(o.items||[]).map(it=>{const a=itemAvailability(o,it),p=store.data.products.find(x=>x.code===it.productCode);return `<div class="availability-row"><div><b>${esc(it.productCode)} · ${esc(p?.name||'Producto')}</b><small>Solicitado ${a.requested} · Físico ${a.origin.physical} · Reservado por otros ${a.origin.reserved} · Disponible ${a.origin.available}</small></div><div>${a.shortage?badge(`Faltan ${a.shortage}`,'warn'):badge('Disponible','ok')}</div>${a.shortage?`<div class="availability-transfer"><select class="shortage-site" data-code="${esc(it.productCode)}"><option value="">Elegir sucursal…</option>${a.others.map(x=>`<option value="${esc(x.site.id)}">${esc(x.site.name)} · ${x.available} disp.</option>`).join('')}</select><button class="secondary request-shortage" data-code="${esc(it.productCode)}" data-qty="${a.shortage}" type="button" ${a.others.length?'':'disabled'}>Solicitar traspaso</button></div>`:''}</div>`;}).join('');
 return `<section class="order-availability"><div class="panel-head"><div><span class="eyebrow">DISPONIBILIDAD</span><h3>Stock para esta orden</h3><small>Físico, reservado, disponible y alternativas en otras sucursales.</small></div></div>${blocks}</section>`;
}
function ensureReceivingLocation(state,siteId){let loc=(state.locations||[]).find(l=>l.siteId===siteId&&l.kind==='RECEPCION_TRANSFERENCIA');if(!loc){loc={id:`${siteId}-RECEPCION-TRF`,siteId,rackId:null,module:null,level:null,label:`Recepción temporal ${siteId}`,scanCode:`${siteId}-RECEPCION-TRF`,status:'LIBRE',access:'DIRECTO',kind:'RECEPCION_TRANSFERENCIA',active:true,capacity:null,notes:'Zona temporal para traspasos internos recibidos.'};state.locations.push(loc);}return loc;}
async function requestShortage(o,code,qty,sourceSiteId){if(!sourceSiteId){toast('Selecciona la sucursal de origen','warning');return;}const available=stockStatus(code,sourceSiteId,store.data).available;if(available<1){toast('Ese centro ya no tiene stock disponible','warning');return;}const amount=Math.min(Number(qty||0),available);const id=`TRF-${Date.now()}`;await store.commit(s=>{s.transfers=s.transfers||[];s.transfers.unshift({id,type:'REPOSICION_PEDIDO',orderId:o.id,sourceSiteId,destinationSiteId:o.sourceSiteId,status:'SOLICITADA',createdAt:new Date().toISOString(),createdBy:s.session.userId,items:[{code,qty:amount}],destinationName:siteName(o.sourceSiteId)});const x=s.orders.find(q=>q.id===o.id);x.status=x.status==='PREPARADA'?'PREPARADA':'ESPERANDO_REPOSICION';x.events=x.events||[];x.events.push({at:new Date().toISOString(),userId:s.session.userId,message:`Solicitado traspaso de ${amount} un. de ${code} desde ${siteName(sourceSiteId)}`});},`Traspaso ${id} solicitado para orden ${o.externalNumber||o.id}`);toast('Traspaso solicitado');}
async function advanceTransfer(t){if(t.status==='SOLICITADA'){await store.commit(s=>{const x=s.transfers.find(z=>z.id===t.id);x.status='EN_TRANSITO';x.departedAt=new Date().toISOString();x.dispatchedBy=s.session.userId;for(const it of x.items||[]){let need=Number(it.qty);const inv=s.inventory.filter(i=>i.productCode===it.code&&Number(i.qty)>0&&inventorySiteId(i,s)===x.sourceSiteId);for(const row of inv){if(need<=0)break;const take=Math.min(Number(row.qty),need);row.qty=Number(row.qty)-take;need-=take;}if(need>0)throw new Error(`Stock insuficiente para ${it.code}`);}s.inventory=s.inventory.filter(i=>Number(i.qty)>0);},`Traspaso ${t.id} enviado`);return;}
 if(t.status==='EN_TRANSITO'){await store.commit(s=>{const x=s.transfers.find(z=>z.id===t.id),loc=ensureReceivingLocation(s,x.destinationSiteId);for(const it of x.items||[]){let row=s.inventory.find(i=>i.productCode===it.code&&i.locationId===loc.id&&!i.palletId);if(!row){row={id:`INV-TRF-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,productCode:it.code,locationId:loc.id,qty:0,palletId:null};s.inventory.push(row);}row.qty=Number(row.qty||0)+Number(it.qty||0);}x.status='RECIBIDA';x.receivedAt=new Date().toISOString();x.receivedBy=s.session.userId;const o=s.orders.find(q=>q.id===x.orderId);if(o){o.events=o.events||[];o.events.push({at:new Date().toISOString(),userId:s.session.userId,message:`Traspaso ${x.id} recibido en ${siteName(x.destinationSiteId)}`});if(o.status==='ESPERANDO_REPOSICION')o.status=o.assignedTo?'ASIGNADA':'ACEPTADA';}},`Traspaso ${t.id} recibido`);}
}
function transferHtml(o){const trs=(store.data.transfers||[]).filter(t=>t.orderId===o.id&&t.type==='REPOSICION_PEDIDO');if(!trs.length)return '';return `<section class="order-transfers"><h3>Traspasos para completar la orden</h3>${trs.map(t=>`<div class="history-row"><div class="hist-icon">⇄</div><div><b>${esc(t.id)} · ${esc(siteName(t.sourceSiteId))} → ${esc(siteName(t.destinationSiteId))}</b><small>${(t.items||[]).map(i=>`${esc(i.code)} · ${i.qty} un.`).join(' · ')}</small></div>${badge(t.status,t.status==='RECIBIDA'?'ok':t.status==='EN_TRANSITO'?'warn':'neutral')}${isManager()&&['SOLICITADA','EN_TRANSITO'].includes(t.status)?`<button class="secondary advance-transfer" data-transfer="${esc(t.id)}" type="button">${t.status==='SOLICITADA'?'Marcar en tránsito':'Recibir en bodega'}</button>`:''}</div>`).join('')}</section>`;}

function orderCard(o){const p=progress(o);return `<button class="order-card" data-order="${esc(o.id)}" type="button"><div class="order-card-top"><div><span class="eyebrow">${esc(o.externalNumber||o.id)}</span><h3>${esc(siteName(o.sourceSiteId))} → ${esc(siteName(o.requestSiteId))}</h3></div>${badge(statusLabel(o.status),statusTone(o.status))}</div><div class="order-assignee"><span>Operador</span><b>${esc(userName(o.assignedTo))}</b></div><div class="progress-line"><div><span style="width:${p.pct}%"></span></div><b>${p.done} / ${p.total}</b><small>${p.pct}%</small></div><div class="order-card-foot"><small>${new Date(o.createdAt).toLocaleString('es-CL')}</small><b>Ver operación →</b></div></button>`;}
function locationText(code,siteId){const rows=(store.data.inventory||[]).filter(i=>i.productCode===code&&Number(i.qty)>0).filter(i=>{const l=store.data.locations.find(x=>x.id===i.locationId);return (l?.siteId||'REC')===siteId;});return rows.map(i=>`${i.palletId||i.locationId} · ${Number(i.qty)} un.`).join(' · ')||'Sin stock localizado en este centro';}
function orderDetail(o){const p=progress(o);const canWork=o.assignedTo===me()?.id||isManager();const rows=(o.items||[]).map((it,idx)=>{const prod=store.data.products.find(x=>x.code===it.productCode);const done=Number(it.pickedQty||0)>=Number(it.qty);return `<div class="pick-item ${done?'done':''}"><div class="pick-status">${done?'✓':idx+1}</div><div class="pick-main"><button class="product-link" data-code="${esc(it.productCode)}" type="button"><b>${esc(it.productCode)} · ${esc(prod?.name||prod?.description||'Producto')}</b></button><small>${esc(locationText(it.productCode,o.sourceSiteId))}</small><small>Códigos válidos: ${esc(productAliases(prod).join(', '))}</small></div><div class="pick-qty"><small>Preparado</small><b>${Number(it.pickedQty||0)} / ${Number(it.qty)}</b></div></div>`;}).join('');
 const accept=isManager()&&o.status==='RECIBIDA'?`<div class="order-assign"><div><b>Orden pendiente de aceptación</b><small>Revísala antes de asignarla a un operario.</small></div><button id="accept-order" class="primary" type="button">Aceptar orden</button></div>`:'';
 const assign=isManager()&&['ACEPTADA','ASIGNADA','EN_PICKING'].includes(o.status)?`<div class="order-assign"><label>Asignar tarea<select id="order-operator"><option value="">Selecciona operario</option>${operators().map(u=>`<option value="${esc(u.id)}" ${u.id===o.assignedTo?'selected':''}>${esc(u.name)}</option>`).join('')}</select></label><button id="assign-order" class="secondary" type="button">Asignar</button></div>`:'';
 const scan=canWork&&['ASIGNADA','EN_PICKING'].includes(o.status)?`<section class="pick-scan"><div><span class="eyebrow">PICKING GUIADO</span><h3>Escanea el producto que estás preparando</h3><p>Puede ser el código principal, SKU, importación u otro código asociado.</p></div><form id="pick-form"><div class="entrada-con-camara"><input id="pick-code" autocomplete="off" placeholder="Escanea o escribe cualquier código asociado"><button id="pick-camera" class="scan-button" type="button">▣</button></div><input id="pick-qty" type="number" min="1" step="1" value="1" inputmode="numeric"><button class="primary" type="submit">Confirmar</button></form></section>`:'';
 const actions=isManager()&&o.status==='PREPARADA'?`<div class="order-final"><button id="deliver-driver" class="primary" type="button">Entregar al conductor</button><small>Este paso cierra la responsabilidad operativa de bodega.</small></div>`:'';
 return `<section class="panel order-detail" data-order-id="${esc(o.id)}"><div class="panel-head"><div><span class="eyebrow">ORDEN ${esc(o.externalNumber||o.id)}</span><h2>${esc(statusLabel(o.status))}</h2><small>${esc(siteName(o.sourceSiteId))} → ${esc(siteName(o.requestSiteId))} · Operador: ${esc(userName(o.assignedTo))}</small></div><button id="close-order" class="ghost" type="button">Cerrar</button></div><div class="order-progress-big"><div><span style="width:${p.pct}%"></span></div><b>${p.done} de ${p.total} productos · ${p.pct}%</b></div>${availabilityHtml(o)}${transferHtml(o)}${accept}${assign}${scan}<div class="pick-list">${rows||empty('Orden sin productos')}</div>${actions}<div class="order-timeline"><h3>Actividad</h3>${(o.events||[]).slice().reverse().map(e=>`<div><b>${esc(e.message)}</b><small>${esc(userName(e.userId))} · ${new Date(e.at).toLocaleString('es-CL')}</small></div>`).join('')}</div></section>`;
}
function validateOrderRows(rows){if(!rows.length)return {errors:['El Excel está vacío.'],items:[]};const headers=rows[0].map(normalizeHeader);const ci=headers.findIndex(h=>['CODIGO','SKU','CODIGO_PRODUCTO'].includes(h));const qi=headers.findIndex(h=>['CANTIDAD','CANT','QTY'].includes(h));if(ci<0||qi<0)return {errors:['El Excel debe contener las columnas CODIGO (o SKU) y CANTIDAD.'],items:[]};const errors=[];const map=new Map();rows.slice(1).forEach((r,n)=>{const raw=String(r[ci]??'').trim(),qty=Number(r[qi]);if(!raw&&!r[qi])return;const p=resolveProduct(raw);if(!p){errors.push(`Fila ${n+2}: código ${raw||'(vacío)'} no asociado a ningún producto.`);return;}if(!Number.isFinite(qty)||qty<=0){errors.push(`Fila ${n+2}: cantidad inválida para ${raw}.`);return;}const old=map.get(p.code)||{productCode:p.code,qty:0,pickedQty:0,inputCodes:[]};old.qty+=qty;old.inputCodes.push(raw);map.set(p.code,old);});return {errors,items:[...map.values()]};}
function previewHtml(){if(!preview)return '<div class="import-empty">Selecciona un Excel para validar la orden.</div>';return `${preview.errors.length?`<div class="import-errors"><b>Hay datos que debes corregir:</b>${preview.errors.map(e=>`<p>${esc(e)}</p>`).join('')}</div>`:`<div class="callout"><b>Orden lista</b><span>${preview.items.length} productos reconocidos en el catálogo maestro.</span></div>`}<div class="table-wrap"><table><thead><tr><th>Código maestro</th><th>Producto</th><th>Cantidad</th></tr></thead><tbody>${preview.items.map(i=>{const p=store.data.products.find(x=>x.code===i.productCode);return `<tr><td><b>${esc(i.productCode)}</b></td><td>${esc(p?.name||p?.description||'Producto')}</td><td>${i.qty}</td></tr>`;}).join('')}</tbody></table></div>`;}
function createDialog(){return `<dialog id="order-dialog" class="order-dialog-wide"><form id="order-form" class="dialog-card order-create-card"><div class="dialog-head"><div><span class="eyebrow">NUEVA ORDEN</span><h3>Cargar orden desde Excel</h3></div><button type="button" id="close-order-dialog" class="ghost">×</button></div><div class="form-grid"><label>Número de orden<input id="order-number" placeholder="Ej. 4500123"></label><label>Centro preparador<select id="order-source">${store.data.sites.filter(s=>s.active!==false&&siteCompanyId(s)===activeCompanyId()).map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><label>Centro solicitante / destino<select id="order-request"><option value="">Selecciona destino</option>${store.data.sites.filter(s=>s.active!==false&&siteCompanyId(s)===activeCompanyId()).map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><label>Archivo Excel<input id="order-file" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required></label></div><small>Solo necesitas CODIGO/SKU y CANTIDAD. El WMS obtiene descripción y demás datos desde el catálogo existente.</small><div id="order-preview">${previewHtml()}</div><div class="dialog-actions"><button type="button" id="cancel-order" class="ghost">Cancelar</button><button id="save-order" class="primary" type="submit" disabled>Crear orden</button></div></form></dialog>`;}
async function acceptOrder(o){await store.commit(s=>{const x=s.orders.find(q=>q.id===o.id);x.status='ACEPTADA';x.acceptedAt=new Date().toISOString();x.acceptedBy=s.session.userId;x.events=x.events||[];x.events.push({at:new Date().toISOString(),userId:s.session.userId,message:'Orden aceptada por bodega'});},`Orden ${o.externalNumber||o.id} aceptada`);}
async function assignOrder(o,userId){if(!userId){toast('Selecciona un operario');return;}await store.commit(s=>{const x=s.orders.find(q=>q.id===o.id);x.assignedTo=userId;x.status='ASIGNADA';x.assignedAt=new Date().toISOString();x.events=x.events||[];x.events.push({at:new Date().toISOString(),userId:s.session.userId,message:`Orden asignada a ${userName(userId)}`});},`Orden ${o.externalNumber||o.id} asignada`);}
async function pick(o,raw,qty){const p=resolveProduct(raw);if(!p){toast('Código no reconocido');return;}const item=o.items.find(i=>i.productCode===p.code);if(!item){toast('Ese producto no pertenece a esta orden');return;}const remaining=Number(item.qty)-Number(item.pickedQty||0);if(qty<1||qty>remaining){toast(`Cantidad pendiente: ${remaining}`);return;}const available=stockStatus(p.code,o.sourceSiteId,store.data,o.id).available;if(available<Number(item.pickedQty||0)+qty){toast(`Stock disponible para esta orden en ${siteName(o.sourceSiteId)}: ${Math.max(0,available-Number(item.pickedQty||0))}`);return;}await store.commit(s=>{const x=s.orders.find(q=>q.id===o.id);const it=x.items.find(i=>i.productCode===p.code);it.pickedQty=Number(it.pickedQty||0)+qty;it.lastScannedCode=String(raw).trim();x.status='EN_PICKING';x.pickingStartedAt=x.pickingStartedAt||new Date().toISOString();x.events=x.events||[];x.events.push({at:new Date().toISOString(),userId:s.session.userId,message:`${p.code}: ${it.pickedQty}/${it.qty} preparado`});if(x.items.every(i=>Number(i.pickedQty||0)>=Number(i.qty))){x.status='PREPARADA';x.preparedAt=new Date().toISOString();x.events.push({at:new Date().toISOString(),userId:s.session.userId,message:'Picking completado · orden preparada'});}},`Picking ${o.externalNumber||o.id}: ${p.code}`);}
async function deliver(o){const driver=prompt('Nombre del conductor que retira la mercancía:')?.trim();if(!driver)return;for(const it of o.items||[]){if(Number(it.pickedQty||0)<Number(it.qty||0))throw new Error(`La orden aún no está completa para ${it.productCode}.`);const available=stockBySite(it.productCode)[o.sourceSiteId]||0;if(available<Number(it.qty)){throw new Error(`Stock insuficiente para ${it.productCode}. Disponible: ${available}`);}}await store.commit(s=>{const x=s.orders.find(q=>q.id===o.id);for(const it of x.items){let need=Number(it.qty);const inv=s.inventory.filter(i=>i.productCode===it.productCode&&Number(i.qty)>0).filter(i=>(s.locations.find(l=>l.id===i.locationId)?.siteId||'REC')===x.sourceSiteId);for(const row of inv){if(need<=0)break;const take=Math.min(Number(row.qty),need);row.qty=Number(row.qty)-take;need-=take;}if(need>0)throw new Error(`Stock insuficiente para ${it.productCode}`);}s.inventory=s.inventory.filter(i=>Number(i.qty)>0);for(const it of x.items)it.dispatchedQty=Number(it.qty||0);x.status='ENTREGADA_CONDUCTOR';x.driverName=driver;x.deliveredAt=new Date().toISOString();x.events=x.events||[];x.events.push({at:new Date().toISOString(),userId:s.session.userId,message:`Mercancía entregada al conductor ${driver}`});},`Orden ${o.externalNumber||o.id} entregada a conductor`);toast('Orden entregada al conductor');}
function wireDetail(root,o){document.querySelectorAll('.request-shortage').forEach(b=>b.onclick=async()=>{const sel=document.querySelector(`.shortage-site[data-code="${CSS.escape(b.dataset.code)}"]`);await requestShortage(o,b.dataset.code,Number(b.dataset.qty),sel?.value);renderOrders(root,o.id);});document.querySelectorAll('.advance-transfer').forEach(b=>b.onclick=async()=>{try{const t=store.data.transfers.find(x=>x.id===b.dataset.transfer);await advanceTransfer(t);renderOrders(root,o.id);}catch(e){toast(e.message,'warning');}});document.querySelector('#accept-order')?.addEventListener('click',async()=>{await acceptOrder(o);renderOrders(root,o.id);});document.querySelector('#close-order').onclick=()=>document.querySelector('#order-detail-slot').innerHTML='';document.querySelectorAll('.product-link').forEach(b=>b.onclick=()=>location.hash=`#/productos?code=${encodeURIComponent(b.dataset.code)}`);document.querySelector('#assign-order')?.addEventListener('click',async()=>{await assignOrder(o,document.querySelector('#order-operator').value);renderOrders(root);});if(document.querySelector('#pick-form')){enlazarBotonEscaner('pick-camera','pick-code',{titulo:'Escanear producto',ayuda:'Escanea cualquiera de sus códigos asociados'});document.querySelector('#pick-form').onsubmit=async e=>{e.preventDefault();await pick(o,document.querySelector('#pick-code').value.trim(),Number(document.querySelector('#pick-qty').value||1));renderOrders(root,o.id);};}document.querySelector('#deliver-driver')?.addEventListener('click',async()=>{try{await deliver(o);renderOrders(root,o.id);}catch(e){toast(e.message);}});}
export function renderOrders(root,openId=null){if(liveTimer){clearInterval(liveTimer);liveTimer=null;}const title=isManager()?'Órdenes y Picking':'Mis tareas';const body=`<div class="page-intro"><div><span class="eyebrow">OPERACIÓN</span><h2>${esc(title)}</h2><p>${isManager()?'Recibe órdenes, asígnalas y sigue el avance del picking.':'Aquí aparecen únicamente las órdenes que te fueron asignadas.'}</p></div>${isManager()?'<button id="new-order" class="primary" type="button">+ Importar orden Excel</button>':''}</div><div class="orders-grid">${visibleOrders().length?visibleOrders().slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).map(orderCard).join(''):empty('Sin órdenes','Todavía no hay tareas para mostrar.')}</div><div id="order-detail-slot"></div>${isManager()?createDialog():''}`;root.innerHTML=shell(title,body,'ordenes');wireShell();document.querySelectorAll('.order-card').forEach(b=>b.onclick=()=>{const o=store.data.orders.find(x=>x.id===b.dataset.order);const slot=document.querySelector('#order-detail-slot');slot.innerHTML=orderDetail(o);slot.scrollIntoView({behavior:'smooth',block:'start'});wireDetail(root,o);});if(openId){const o=store.data.orders.find(x=>x.id===openId);if(o){document.querySelector('#order-detail-slot').innerHTML=orderDetail(o);wireDetail(root,o);}}
 if(isManager()){const dlg=document.querySelector('#order-dialog');dlg.addEventListener('cancel',e=>e.preventDefault());document.querySelector('#new-order').onclick=()=>{preview=null;document.querySelector('#order-preview').innerHTML=previewHtml();document.querySelector('#save-order').disabled=true;dlg.showModal();};document.querySelector('#close-order-dialog').onclick=()=>dlg.close();document.querySelector('#cancel-order').onclick=()=>dlg.close();document.querySelector('#order-file').onchange=async e=>{try{preview=validateOrderRows(await parseXlsx(e.target.files?.[0]));document.querySelector('#order-preview').innerHTML=previewHtml();document.querySelector('#save-order').disabled=preview.errors.length>0||preview.items.length===0;}catch(err){preview={errors:[err.message],items:[]};document.querySelector('#order-preview').innerHTML=previewHtml();}};document.querySelector('#order-form').onsubmit=async e=>{e.preventDefault();if(!preview||preview.errors.length)return;const source=document.querySelector('#order-source').value,request=document.querySelector('#order-request').value;if(!source||!request){toast('Selecciona centro preparador y destino');return;}const number=document.querySelector('#order-number').value.trim()||`WMS-${Date.now()}`;await store.commit(s=>{s.orders=s.orders||[];s.orders.unshift({id:`ORD-${Date.now()}`,externalNumber:number,source:'EXCEL',companyId:siteCompanyId(s.sites.find(z=>z.id===source),s),sourceSiteId:source,requestSiteId:request,status:'RECIBIDA',assignedTo:null,items:preview.items,createdAt:new Date().toISOString(),createdBy:s.session.userId,events:[{at:new Date().toISOString(),userId:s.session.userId,message:'Orden recibida desde Excel'}]});},`Orden ${number} importada`);dlg.close();toast('Orden creada');renderOrders(root);};}
 liveTimer=setInterval(async()=>{if(!location.hash.startsWith('#/ordenes')){clearInterval(liveTimer);return;}try{await store.reload();const currentId=document.querySelector('.order-detail')?.dataset.orderId||null;renderOrders(root,currentId);}catch{}},10000);
}
