import { store } from '../../services/store.js';
import { shell,wireShell,toast } from '../../layout/layout.js';
import { esc,badge,empty } from '../../components/ui.js';
import { enlazarBotonEscaner } from '../../services/camara-ui.js';
import { activeSiteId } from '../../services/stock.js';
import { resolveProduct } from '../../services/product-codes.js';
import { buscarUbicacionPorCodigo, vistaCodigoUbicacion } from '../../services/ubicaciones.js';
import { addStock,deductStock,refreshInventoryStatuses } from '../../services/inventory-ops.js';
import { palletDisplayName } from '../../services/pallet-ops.js';

function activeReceipt(){const site=activeSiteId();return store.data.receipts.find(r=>r.siteId===site&&r.status==='RECIBIENDO');}
function productName(code){return resolveProduct(code)?.name||'Producto no catalogado';}
function userName(id){return store.data.users.find(u=>u.id===id)?.name||id||'No registrado';}
function tempLocations(){const site=activeSiteId();return store.data.locations.filter(l=>l.siteId===site&&l.active&&l.kind==='POR_UBICAR');}
function tempOpts(){return tempLocations().map(l=>`<option value="${esc(l.id)}">${esc(l.label||l.id)} · ${esc(l.id)} · ${esc(l.status)}</option>`).join('');}
function tempMapHtml(){const site=activeSiteId(),siteData=store.data.sites.find(s=>s.id===site),zones=tempLocations();return `<dialog id="receipt-temp-map" class="pallet-map-dialog location-simple-dialog"><div class="pallet-map-card"><div class="dialog-head"><div><span class="eyebrow">ELEGIR UBICACIÓN TEMPORAL</span><h3>${esc(siteData?.name||site)}</h3><small>Selecciona visualmente una zona temporal del centro activo.</small></div><button id="receipt-temp-map-close" class="ghost" type="button">×</button></div><div class="location-simple-grid">${zones.length?zones.map(l=>`<button type="button" class="location-simple-card" data-temp-location="${esc(l.id)}"><span>Zona temporal</span><b>${esc(l.label||l.id)}</b><small>${esc(l.id)} · ${esc(l.status||'LIBRE')}</small></button>`).join(''):`<div class="empty-state"><b>Sin zonas temporales</b><small>Crea una zona temporal para este centro.</small></div>`}</div></div></dialog>`;}
function normalizeCode(v=''){return String(v).trim().toUpperCase().replace(/\s+/g,'-').replace(/[^A-Z0-9_-]/g,'').replace(/-+/g,'-');}
function nextTempId(data,site){const prefix=`${site}-TMP-`,nums=(data.locations||[]).map(l=>String(l.id||'')).filter(id=>id.startsWith(prefix)).map(id=>Number(id.slice(prefix.length))).filter(Number.isFinite);return `${prefix}${String(Math.max(0,...nums)+1).padStart(2,'0')}`;}
function nextPalletId(data,site){const prefix=`${site}-PAL-`,nums=(data.pallets||[]).map(p=>String(p.id||'')).filter(id=>id.startsWith(prefix)).map(id=>Number(id.slice(prefix.length))).filter(Number.isFinite);return `${prefix}${String(Math.max(0,...nums)+1).padStart(4,'0')}`;}
function userOpts(selected=''){return store.data.users.filter(u=>u.active).map(u=>`<option value="${esc(u.id)}" ${u.id===selected?'selected':''}>${esc(u.name)}</option>`).join('');}
function fecha(v){return v?new Date(v).toLocaleString('es-CL'):'—';}

function receiptPanel(r){
 const items=r.items||[];
 return `<section class="panel receipt-work"><div class="panel-head"><div><span class="eyebrow">RECEPCIÓN ABIERTA</span><h3>${esc(r.id)} · ${esc(r.palletId)}</h3><small>${esc(r.origin)} · Llegada ${new Date(r.arrivedAt).toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'})}</small></div>${badge('RECIBIENDO','warn')}</div>
 <div class="receipt-meta"><span><b>Recibe:</b> ${esc(userName(r.receivedBy))}</span><span><b>Trae:</b> ${esc(r.broughtBy||'—')}</span><span><b>Temporal:</b> ${esc(r.tempLocationId||'Por elegir')}</span></div>
 <form id="receive-item" class="quick-scan"><label>Código / escaneo<div class="entrada-con-camara"><input id="rec-code" required autofocus placeholder="Escanea o escribe código"><button id="camara-rec-code" class="scan-button" type="button" title="Escanear código con cámara" aria-label="Escanear código con cámara">▣</button></div></label><label>Cantidad<input id="rec-qty" type="number" min="1" value="1" required></label><button class="primary" type="submit">Agregar</button></form>
 <div class="scan-list">${items.length?items.map((x,i)=>`<div class="scan-row"><div><b>${esc(x.code)}</b><small>${esc(productName(x.code))}</small></div><strong>${x.qty}</strong><button class="ghost rec-remove" data-i="${i}">×</button></div>`).join(''):empty('Aún no hay productos','Escanea el primer producto y agrega la cantidad.')}</div>
 <div class="receipt-close receipt-close-grid"><div class="receipt-location-picker"><label>Ubicación temporal</label><div class="pallet-destination-actions compact"><button id="rec-temp-scan" class="secondary pallet-action-button" type="button">▣ Escanear ubicación</button><button id="rec-temp-map-open" class="secondary pallet-action-button" type="button">▦ Elegir visualmente</button></div><div class="pallet-selected-destination"><small>Ubicación seleccionada</small><b id="rec-temp-selected-label">Todavía no has seleccionado una zona</b><span id="rec-temp-selected-code"></span></div><div class="entrada-con-camara"><input id="rec-temp-code" placeholder="Escanea o escribe ubicación temporal" autocomplete="off"><button id="camara-rec-temp" class="scan-button" type="button" title="Escanear ubicación temporal">▣</button></div><small id="rec-temp-status">Escanea, elige visualmente o usa la lista manual.</small><select id="rec-temp" required><option value="">Seleccionar manualmente…</option>${tempOpts()}</select><button id="open-temp-location" class="ghost small temp-location-shortcut" type="button">+ Crear zona temporal</button></div><label>Supervisado / revisado por<select id="rec-supervisor" required><option value="">Seleccionar…</option>${userOpts()}</select></label><button id="close-receipt" class="primary">Cerrar recepción → POR UBICAR</button></div></section>${tempMapHtml()}`;
}
function receiptDetail(x){
 const items=x.items||[];
 const pending=items.map(i=>{const rows=store.data.inventory.filter(inv=>inv.productCode===i.code&&inv.palletId===x.palletId&&inv.qty>0),qty=rows.reduce((a,b)=>a+Number(b.qty||0),0);return {...i,pendingQty:qty,source:rows[0]?`${rows[0].locationId}@@${x.palletId}`:'',locationId:rows[0]?.locationId||''};}).filter(i=>i.pendingQty>0);
 return `<div class="receipt-detail-grid"><div><span>Recepción</span><b>${esc(x.id)}</b></div><div><span>Pallet temporal</span><b>${esc(x.palletId)}</b></div><div><span>Estado</span><b>${esc(x.status)}</b></div><div><span>Origen</span><b>${esc(x.origin)}</b></div><div><span>Zona temporal</span><b>${esc(x.tempLocationId||'—')}</b></div><div><span>Recibió</span><b>${esc(userName(x.receivedBy))}</b></div></div>
 ${x.note?`<div class="receipt-note"><b>Observación</b><span>${esc(x.note)}</span></div>`:''}
 <div class="receipt-items-detail"><h4>Productos pendientes de ubicar</h4>${pending.length?pending.map(i=>`<div class="receipt-organize-row"><span><b>${esc(i.code)}</b><small>${esc(productName(i.code))}</small><small>Zona temporal: ${esc(i.locationId)}</small></span><span class="receipt-qty-summary"><small>RECIBIDO</small><b>${i.qty}</b><small>PENDIENTE</small><b>${i.pendingQty}</b></span><button class="secondary organize-receipt-product" type="button" data-receipt="${esc(x.id)}" data-code="${esc(i.code)}" data-source="${esc(i.source)}">Ubicar / pasar a pallet</button></div>`).join(''):empty('Recepción organizada','No quedan productos pendientes de ubicar en esta recepción.')}</div>`;
}

function organizeReceiptHtml(receipt,code,sourceKey){
 const [sourceLocation]=sourceKey.split('@@'),available=store.data.inventory.filter(i=>i.productCode===code&&i.palletId===receipt.palletId&&i.locationId===sourceLocation&&i.qty>0).reduce((a,b)=>a+Number(b.qty||0),0),site=activeSiteId(),locations=store.data.locations.filter(l=>l.siteId===site&&l.active&&!['BLOQUEADA','INHABILITADA'].includes(l.status)&&!['POR_UBICAR','RECEPCION_TRANSFERENCIA','PALLET_STAGING'].includes(l.kind)&&l.id!==sourceLocation),pallets=store.data.pallets.filter(p=>p.siteId===site&&p.id!==receipt.palletId&&p.locationId&&p.status!=='CERRADO');
 return `<div class="dialog-head"><div><span class="eyebrow">ORGANIZAR PRODUCTO RECIBIDO</span><h3>${esc(code)} · ${esc(productName(code))}</h3><small>Origen: ${esc(receipt.palletId)} · ${esc(sourceLocation)}</small></div><button id="close-receipt-organize" class="ghost" type="button">×</button></div><div class="receipt-organize-summary"><span><small>Cantidad recibida</small><b>${(receipt.items||[]).find(i=>i.code===code)?.qty||available}</b></span><span><small>Disponible por ubicar</small><b>${available}</b></span></div><label>Cantidad a mover<input id="receipt-organize-qty" type="number" min="1" max="${available}" value="${available}" inputmode="numeric"></label><label>Tipo de destino<select id="receipt-organize-type"><option value="LOCATION">Ubicación / rack</option><option value="PALLET">Incorporar a otro pallet</option></select></label><div id="receipt-organize-location"><div class="pallet-destination-actions compact"><button id="receipt-organize-scan-location" class="secondary" type="button">▣ Escanear destino</button><button id="receipt-organize-map-toggle" class="secondary" type="button">▦ Elegir en mapa</button></div><div class="entrada-con-camara"><input id="receipt-organize-location-code" placeholder="Escanea o escribe ubicación" autocomplete="off"><button id="camera-receipt-organize-location" class="scan-button" type="button">▣</button></div><select id="receipt-organize-location-select"><option value="">Seleccionar manualmente…</option>${locations.map(l=>`<option value="${esc(l.id)}">${esc(l.label||l.id)} · ${esc(l.id)}</option>`).join('')}</select><small id="receipt-organize-location-status">Escanea, elige en mapa o selecciona una ubicación.</small><div id="receipt-organize-map" class="receipt-location-map-grid" hidden>${locations.map(l=>`<button type="button" data-receipt-location="${esc(l.id)}"><b>${esc(l.label||l.id)}</b><small>${esc(l.id)} · ${esc(l.status)}</small></button>`).join('')}</div></div><div id="receipt-organize-pallet" hidden><div class="entrada-con-camara"><input id="receipt-organize-pallet-code" placeholder="Escanea o escribe nombre / ID del pallet" autocomplete="off"><button id="camera-receipt-organize-pallet" class="scan-button" type="button">▣</button></div><select id="receipt-organize-pallet-select"><option value="">Seleccionar pallet…</option>${pallets.map(p=>`<option value="${esc(p.id)}">${esc(palletDisplayName(p))} · ${esc(p.id)} · ${esc(p.locationId)}</option>`).join('')}</select><small id="receipt-organize-pallet-status">Escanea o selecciona el pallet de destino.</small></div><div class="dialog-actions"><button id="cancel-receipt-organize" class="ghost" type="button">Cancelar</button><button id="confirm-receipt-organize" class="primary" type="button">Confirmar movimiento</button></div>`;
}

function wireReceiptDetail(receipt,root,detailDlg){
 document.querySelectorAll('.organize-receipt-product').forEach(button=>button.onclick=()=>openReceiptOrganizer(receipt,button.dataset.code,button.dataset.source,root,detailDlg));
}

function openReceiptOrganizer(receipt,code,sourceKey,root,detailDlg){
 const dialog=document.querySelector('#receipt-organize-dialog'),content=document.querySelector('#receipt-organize-content');content.innerHTML=organizeReceiptHtml(receipt,code,sourceKey);const close=()=>{if(dialog.open)dialog.close();};document.querySelector('#close-receipt-organize').onclick=close;document.querySelector('#cancel-receipt-organize').onclick=close;dialog.oncancel=e=>{e.preventDefault();close();};
 const type=document.querySelector('#receipt-organize-type'),locationPanel=document.querySelector('#receipt-organize-location'),palletPanel=document.querySelector('#receipt-organize-pallet'),locationCode=document.querySelector('#receipt-organize-location-code'),locationSelect=document.querySelector('#receipt-organize-location-select'),locationStatus=document.querySelector('#receipt-organize-location-status'),map=document.querySelector('#receipt-organize-map'),palletCode=document.querySelector('#receipt-organize-pallet-code'),palletSelect=document.querySelector('#receipt-organize-pallet-select'),palletStatus=document.querySelector('#receipt-organize-pallet-status'),site=activeSiteId();
 const validLocation=()=>{const loc=locationCode.value?buscarUbicacionPorCodigo(locationCode.value,store.data):store.data.locations.find(l=>l.id===locationSelect.value),ok=!!(loc&&loc.siteId===site&&loc.active&&!['BLOQUEADA','INHABILITADA'].includes(loc.status)&&!['POR_UBICAR','RECEPCION_TRANSFERENCIA','PALLET_STAGING'].includes(loc.kind));locationStatus.textContent=!locationCode.value&&!locationSelect.value?'Escanea, elige en mapa o selecciona una ubicación final.':ok?`✓ ${vistaCodigoUbicacion(loc,store.data)}`:'Ubicación no reconocida, temporal o no disponible';locationStatus.classList.toggle('valid',ok);return ok?loc:null;};
 const findPallet=value=>{const q=String(value||'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');return store.data.pallets.find(p=>p.siteId===site&&[p.id,p.physicalCode,palletDisplayName(p)].some(v=>String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'')===q));};
 const validPallet=()=>{const pallet=palletCode.value?findPallet(palletCode.value):store.data.pallets.find(p=>p.id===palletSelect.value&&p.siteId===site),ok=!!(pallet&&p.id!==receipt.palletId&&p.locationId&&p.status!=='CERRADO');palletStatus.textContent=!palletCode.value&&!palletSelect.value?'Escanea o selecciona el pallet de destino.':ok?`✓ ${palletDisplayName(pallet)} · ${pallet.locationId}`:'Pallet no reconocido o no disponible';palletStatus.classList.toggle('valid',ok);return ok?pallet:null;};
 type.onchange=()=>{const toPallet=type.value==='PALLET';locationPanel.hidden=toPallet;palletPanel.hidden=!toPallet;};locationCode.oninput=()=>{if(locationCode.value)locationSelect.value='';validLocation();};locationSelect.onchange=()=>{if(locationSelect.value)locationCode.value='';validLocation();};palletCode.oninput=()=>{if(palletCode.value)palletSelect.value='';validPallet();};palletSelect.onchange=()=>{if(palletSelect.value)palletCode.value='';validPallet();};document.querySelector('#receipt-organize-map-toggle').onclick=()=>{map.hidden=!map.hidden;};document.querySelectorAll('[data-receipt-location]').forEach(b=>b.onclick=()=>{locationCode.value='';locationSelect.value=b.dataset.receiptLocation;map.hidden=true;validLocation();});document.querySelector('#receipt-organize-scan-location').onclick=()=>document.querySelector('#camera-receipt-organize-location').click();enlazarBotonEscaner('camera-receipt-organize-location','receipt-organize-location-code',{titulo:'Escanear ubicación de destino',ayuda:'Apunta a la etiqueta del rack o posición',onDetectar:()=>validLocation()});enlazarBotonEscaner('camera-receipt-organize-pallet','receipt-organize-pallet-code',{titulo:'Escanear pallet de destino',ayuda:'Apunta al identificador físico del pallet',onDetectar:()=>validPallet()});
 document.querySelector('#confirm-receipt-organize').onclick=async()=>{const qty=Number(document.querySelector('#receipt-organize-qty').value),targetPallet=type.value==='PALLET'?validPallet():null,targetLocation=targetPallet?store.data.locations.find(l=>l.id===targetPallet.locationId):validLocation();if(type.value==='PALLET'&&!targetPallet){toast('Selecciona un pallet de destino válido');return;}if(!targetLocation){toast('Selecciona una ubicación de destino válida');return;}try{await store.commit(d=>{const result=deductStock(d,{code,qty,sourceKey,siteId:site});if(!result.ok)throw new Error(result.message);addStock(d,{code,qty,locationId:targetLocation.id,palletId:targetPallet?.id||null});refreshInventoryStatuses(d,site);const tp=targetPallet?d.pallets.find(p=>p.id===targetPallet.id):null,loc=d.locations.find(l=>l.id===targetLocation.id);if(tp)tp.status=['POR_UBICAR','RECEPCION_TRANSFERENCIA','PALLET_STAGING'].includes(loc?.kind)?'POR_UBICAR':'UBICADO';const rr=d.receipts.find(r=>r.id===receipt.id),remains=d.inventory.some(i=>i.palletId===receipt.palletId&&Number(i.qty)>0);if(rr&&!remains){rr.status='UBICADA';rr.organizedAt=new Date().toISOString();}d.movements.unshift({id:`MOV-REC-ORG-${Date.now()}`,siteId:site,type:targetPallet?'MOVIMIENTO_A_PALET':'UBICACION_DESDE_RECEPCION',productCode:code,qty,from:`${receipt.palletId} / ${sourceKey.split('@@')[0]}`,to:targetPallet?`${targetPallet.id} / ${targetLocation.id}`:targetLocation.id,sourcePalletId:receipt.palletId,palletId:targetPallet?.id||null,receiptId:receipt.id,reason:'Organizar recepción',userId:d.session.userId,at:new Date().toISOString(),allocations:result.allocations});},`${code}: ${qty} un. organizadas desde ${receipt.id}`);}catch(error){toast(error.message||'No fue posible completar el movimiento');return;}close();toast('Producto ubicado correctamente');const updated=store.data.receipts.find(r=>r.id===receipt.id);document.querySelector('#receipt-detail-content').innerHTML=receiptDetail(updated);wireReceiptDetail(updated,root,detailDlg);};dialog.showModal();
}

export function renderReceipts(root){
 const d=store.data,siteId=activeSiteId(d),site=d.sites.find(s=>s.id===siteId),r=activeReceipt(),closed=d.receipts.filter(x=>x.siteId===siteId&&x.status!=='RECIBIENDO').slice(0,20);
 root.innerHTML=shell('Recepción',`<div class="page-intro"><div><span class="eyebrow">RECEPCIÓN RÁPIDA · CENTRO ACTIVO</span><h2>${esc(site?.name||siteId)}</h2><p>Importación, proveedor, devolución o tienda: escanea, asigna a un pallet temporal y deja todo localizable en POR UBICAR.</p></div><div class="receipt-page-actions"><a href="#/movimientos" class="secondary">Organizar productos recibidos</a><button id="open-temp-location-page" class="ghost" type="button">+ Zona temporal</button>${r?'':`<button id="open-new-receipt" class="primary">+ Nueva recepción</button>`}</div></div>
 ${r?receiptPanel(r):`<section class="panel">${empty('Sin recepción abierta','Inicia una recepción para probar el flujo rápido.')}</section>`}
 <section class="panel"><div class="panel-head"><div><h3>Recepciones recientes para organizar</h3><small>Abre una recepción, elige el producto y ubícalo sin perder su origen.</small></div><a href="#/movimientos" class="ghost">Organizar ahora</a></div>${closed.length?closed.map(x=>`<button class="history-row receipt-clickable" data-receipt="${esc(x.id)}" type="button"><div class="hist-icon">⇩</div><div><b>${esc(x.id)} · ${esc(x.palletId)}</b><small>${esc(x.status)} · ${esc(x.origin)} · ${esc(x.tempLocationId||'')}</small><small>Recibió: ${esc(userName(x.receivedBy))} · Supervisó: ${esc(userName(x.supervisedBy))}</small></div><time>${fecha(x.closedAt||x.arrivedAt)}</time><span class="receipt-chevron">›</span></button>`).join(''):empty('Sin recepciones cerradas','Las recepciones cerradas aparecerán aquí.')}</section>
 <dialog id="receipt-detail-dialog"><div class="receipt-dialog-inner"><div class="dialog-head"><div><span class="eyebrow">DETALLE DE RECEPCIÓN</span><h3 id="receipt-detail-title">Recepción</h3></div><button id="close-receipt-detail" class="ghost">×</button></div><div id="receipt-detail-content"></div></div></dialog>
 <dialog id="receipt-organize-dialog" class="receipt-organize-dialog"><div id="receipt-organize-content" class="receipt-dialog-inner"></div></dialog>
 <dialog id="temp-location-dialog"><form id="temp-location-form"><div class="dialog-head"><div><h3>Nueva zona temporal</h3><small>Solo para el centro activo</small></div><button type="button" id="cancel-temp-location-x" class="ghost">×</button></div><label>Código de ubicación<div class="entrada-con-camara"><input id="temp-location-code" required maxlength="40"><button id="camera-temp-location-code" class="scan-button" type="button">▣</button></div></label><label>Nombre / referencia física<input id="temp-location-label" required maxlength="80" placeholder="Ej. Recepción junto a puerta 2"></label><div class="dialog-actions"><button type="button" id="cancel-temp-location" class="ghost">Cancelar</button><button class="primary" type="submit">Crear zona</button></div></form></dialog>
 <dialog id="new-receipt-dialog"><form id="new-receipt-form"><div class="dialog-head"><h3>Nueva recepción</h3><button type="button" id="cancel-new-receipt-x" class="ghost">×</button></div><label>Identificación del pallet<div class="entrada-con-camara"><input id="new-pallet-id" required maxlength="40"><button id="camera-new-pallet-id" class="scan-button" type="button">▣</button></div><small>Editable. Debe ser único en todo el WMS.</small></label><label>Origen<select id="new-origin"><option>Importación</option><option>Proveedor</option><option>Tienda / devolución</option><option>Cliente / devolución</option><option>Otro</option></select></label><label>Quién trae<input id="new-brought" placeholder="Nombre conductor / transportista"></label><label>Observación<input id="new-note" placeholder="Opcional"></label><div class="dialog-actions"><button type="button" id="cancel-new-receipt" class="ghost">Cancelar</button><button id="create-receipt" class="primary" type="submit">Crear y comenzar</button></div></form></dialog>`,'recepciones');
 wireShell();
 const tempDlg=document.querySelector('#temp-location-dialog'),openTemp=()=>{document.querySelector('#temp-location-code').value=nextTempId(store.data,siteId);document.querySelector('#temp-location-label').value='Zona temporal de recepción';tempDlg.showModal();document.querySelector('#temp-location-code').focus();};
 document.querySelector('#open-temp-location-page').onclick=openTemp;
 document.querySelector('#open-temp-location')?.addEventListener('click',openTemp);
 document.querySelector('#cancel-temp-location-x').onclick=()=>tempDlg.close();
 document.querySelector('#cancel-temp-location').onclick=()=>tempDlg.close();
 enlazarBotonEscaner('camera-temp-location-code','temp-location-code',{titulo:'Escanear código de zona temporal',ayuda:'Apunta a la etiqueta física de la zona'});
 document.querySelector('#temp-location-form').onsubmit=async e=>{e.preventDefault();const id=normalizeCode(document.querySelector('#temp-location-code').value),label=document.querySelector('#temp-location-label').value.trim();if(!id){toast('Ingresa un código válido para la zona temporal');return;}if((store.data.locations||[]).some(l=>l.id===id)){toast('Ese código de ubicación ya existe');return;}const active=activeSiteId(store.data);await store.commit(s=>{s.locations.push({id,siteId:active,rackId:null,module:null,level:null,label,scanCode:id,status:'LIBRE',access:'DIRECTO',kind:'POR_UBICAR',active:true,capacity:null,notes:'Zona temporal / transición creada para recepción de pallets.'});const rr=s.receipts.find(x=>x.siteId===active&&x.status==='RECIBIENDO');if(rr)rr.tempLocationId=id;},`Zona temporal ${id} creada en ${site?.name||siteId}`);tempDlg.close();toast('Zona temporal creada');renderReceipts(root);};
 const detailDlg=document.querySelector('#receipt-detail-dialog');
 document.querySelectorAll('.receipt-clickable').forEach(btn=>btn.onclick=()=>{const x=d.receipts.find(a=>a.id===btn.dataset.receipt&&a.siteId===siteId);if(!x)return;document.querySelector('#receipt-detail-title').textContent=`${x.id} · ${x.palletId}`;document.querySelector('#receipt-detail-content').innerHTML=receiptDetail(x);wireReceiptDetail(x,root,detailDlg);detailDlg.showModal();});
 document.querySelector('#close-receipt-detail').onclick=()=>detailDlg.close();
 if(!r){
   const dlg=document.querySelector('#new-receipt-dialog');
   document.querySelector('#open-new-receipt').onclick=()=>{document.querySelector('#new-pallet-id').value=nextPalletId(store.data,siteId);dlg.showModal();};
   document.querySelector('#cancel-new-receipt-x').onclick=()=>dlg.close();
   document.querySelector('#cancel-new-receipt').onclick=()=>dlg.close();
   enlazarBotonEscaner('camera-new-pallet-id','new-pallet-id',{titulo:'Escanear identificador del pallet',ayuda:'Apunta al código físico del pallet'});
   document.querySelector('#new-receipt-form').onsubmit=async(e)=>{
     e.preventDefault();
     const btn=document.querySelector('#create-receipt');btn.disabled=true;
     try{
       const idx=d.receipts.length+1,id=`REC-${String(idx).padStart(6,'0')}`,pid=normalizeCode(document.querySelector('#new-pallet-id').value),now=new Date().toISOString(),origin=document.querySelector('#new-origin').value,broughtBy=document.querySelector('#new-brought').value.trim(),note=document.querySelector('#new-note').value.trim();
       if(!pid){toast('Ingresa una identificación válida para el palet');btn.disabled=false;return;}const existing=(store.data.pallets||[]).find(p=>p.id===pid);if(existing){const existingSite=store.data.sites.find(s=>s.id===existing.siteId)?.name||existing.siteId;toast(`El palet ${pid} ya existe en ${existingSite}. Usa otra identificación.`);btn.disabled=false;return;}
       await store.commit(s=>{s.receipts.unshift({id,siteId:activeSiteId(s),palletId:pid,status:'RECIBIENDO',origin,broughtBy,note,arrivedAt:now,receivedBy:s.session.userId,supervisedBy:null,tempLocationId:null,items:[]});s.pallets.push({id:pid,siteId:activeSiteId(s),status:'RECIBIENDO',locationId:null,origin,createdAt:now});},`Recepción ${id} iniciada`);
       dlg.close();toast('Recepción iniciada');renderReceipts(root);
     }catch(error){console.error('Error creando recepción',error);toast('No fue posible crear la recepción');btn.disabled=false;}
   };
 }else{
   enlazarBotonEscaner('camara-rec-code','rec-code',{titulo:'Escanear producto recibido',ayuda:'Apunta al código de barras de la caja'});
   const sel=document.querySelector('#rec-temp'),tempCode=document.querySelector('#rec-temp-code'),tempStatus=document.querySelector('#rec-temp-status'),tempLabel=document.querySelector('#rec-temp-selected-label'),tempSelectedCode=document.querySelector('#rec-temp-selected-code'),tempMap=document.querySelector('#receipt-temp-map');
   const validTemp=loc=>!!(loc&&loc.siteId===activeSiteId()&&loc.active&&loc.kind==='POR_UBICAR');
   const showTemp=loc=>{tempLabel.textContent=loc?(loc.label||vistaCodigoUbicacion(loc,store.data)):'Todavía no has seleccionado una zona';tempSelectedCode.textContent=loc?loc.id:'';};
   const validateTemp=()=>{const loc=buscarUbicacionPorCodigo(tempCode.value,store.data),ok=validTemp(loc);tempStatus.textContent=!tempCode.value?'Escanea, elige visualmente o usa la lista manual.':ok?`✓ Zona válida: ${vistaCodigoUbicacion(loc,store.data)}`:loc?'La ubicación no es una zona temporal de este centro':'Ubicación no reconocida';tempStatus.classList.toggle('valid',ok);if(ok){sel.value=loc.id;showTemp(loc);}else if(tempCode.value){sel.value='';showTemp(null);}return ok?loc:null;};
   if(r.tempLocationId){sel.value=r.tempLocationId;showTemp(store.data.locations.find(l=>l.id===r.tempLocationId));}
   document.querySelector('#rec-temp-scan').onclick=()=>document.querySelector('#camara-rec-temp').click();
   enlazarBotonEscaner('camara-rec-temp','rec-temp-code',{titulo:'Escanear ubicación temporal',ayuda:'Apunta a la etiqueta física de la zona temporal',onDetectar:()=>validateTemp()});
   tempCode.oninput=()=>{if(tempCode.value)sel.value='';validateTemp();};
   sel.onchange=()=>{if(sel.value){tempCode.value='';const loc=store.data.locations.find(l=>l.id===sel.value);showTemp(validTemp(loc)?loc:null);tempStatus.textContent=validTemp(loc)?'✓ Zona seleccionada manualmente.':'Selecciona una zona temporal válida.';tempStatus.classList.toggle('valid',validTemp(loc));}else showTemp(null);};
   document.querySelector('#rec-temp-map-open').onclick=()=>tempMap?.showModal();document.querySelector('#receipt-temp-map-close')?.addEventListener('click',()=>tempMap?.close());if(tempMap)tempMap.oncancel=e=>{e.preventDefault();tempMap.close();};document.querySelectorAll('[data-temp-location]').forEach(b=>b.onclick=()=>{const loc=store.data.locations.find(l=>l.id===b.dataset.tempLocation);if(!validTemp(loc))return;sel.value=loc.id;tempCode.value='';showTemp(loc);tempStatus.textContent=`✓ Zona elegida: ${vistaCodigoUbicacion(loc,store.data)}`;tempStatus.classList.add('valid');tempMap?.close();});
   document.querySelector('#receive-item').onsubmit=async(e)=>{e.preventDefault();const raw=document.querySelector('#rec-code').value.trim(),qty=Number(document.querySelector('#rec-qty').value),p=resolveProduct(raw);if(!p){toast('Código no asociado a ningún producto');return;}if(qty<1)return;const code=p.code;await store.commit(s=>{const rr=s.receipts.find(x=>x.id===r.id),it=rr.items.find(x=>x.code===code);if(it)it.qty+=qty;else rr.items.push({code,qty,scannedCode:raw});},`Producto ${code} agregado a ${r.id}`);toast('Producto agregado');renderReceipts(root);};
   document.querySelectorAll('.rec-remove').forEach(b=>b.onclick=async()=>{await store.commit(s=>s.receipts.find(x=>x.id===r.id).items.splice(Number(b.dataset.i),1),`Producto retirado de ${r.id}`);renderReceipts(root);});
   document.querySelector('#close-receipt').onclick=async()=>{const temp=document.querySelector('#rec-temp').value,supervisedBy=document.querySelector('#rec-supervisor').value;if(!(r.items||[]).length){toast('Agrega al menos un producto');return;}if(!temp){toast('Selecciona ubicación temporal');return;}if(!supervisedBy){toast('Selecciona quién revisó la recepción');return;}const now=new Date().toISOString();await store.commit(s=>{const rr=s.receipts.find(x=>x.id===r.id);rr.status='POR_UBICAR';rr.closedAt=now;rr.tempLocationId=temp;rr.supervisedBy=supervisedBy;const pal=s.pallets.find(x=>x.id===rr.palletId);pal.status='POR_UBICAR';pal.locationId=temp;for(const it of rr.items){let inv=s.inventory.find(i=>i.productCode===it.code&&i.locationId===temp&&i.palletId===rr.palletId);if(inv){inv.qty+=it.qty;inv.siteId=rr.siteId;}else s.inventory.push({id:`INV-${Date.now()}-${it.code}`,siteId:rr.siteId,productCode:it.code,locationId:temp,qty:it.qty,palletId:rr.palletId});}const loc=s.locations.find(l=>l.id===temp);if(loc)loc.status='OCUPADA';},`Recepción ${r.id} cerrada en ${temp}`);toast('Recepción cerrada y localizada');renderReceipts(root);};
 }
}
