import { store } from '../../services/store.js';
import { auth } from '../../services/auth.js';
import { apiRequest } from '../../services/api.js';
import { shell, wireShell, toast } from '../../layout/layout.js';
import { esc, badge } from '../../components/ui.js';
import { companyName, siteCompanyId } from '../../services/company.js';
import { requireAdminSupercode } from '../../services/security.js';

const ROLES={ADMIN_GLOBAL:'Administrador general',ADMINISTRADOR:'Administrador de centro',ENCARGADO:'Encargado',OPERADOR_BODEGA:'Operador de bodega',OPERADOR_RECEPCION:'Operador de recepción',TRANSPORTISTA:'Transportista'};
const STATUS={ACTIVE:'Activo',PAUSED:'Pausado',DISABLED:'Desactivado'};
const ROLE_WEIGHT={TRANSPORTISTA:0,OPERADOR_RECEPCION:1,OPERADOR_BODEGA:2,ENCARGADO:3,ADMINISTRADOR:4};
const CODE_PERMISSION_FIELDS=[['codesConsult','Consultar producto por código'],['codesAssociate','Asociar códigos'],['productsEdit','Crear / editar producto'],['inventoryAdjust','Modificar inventario directamente'],['palletsView','Consultar pallets y contenido'],['palletsOperate','Cargar productos y mover pallets'],['palletsRegister','Registrar pallets físicos permanentes']];

function current(){return store.data.users.find(u=>u.id===store.data.session.userId)||auth.user;}
function roleName(role){return ROLES[role]||String(role||'Sin rol').replaceAll('_',' ');}
function userStatus(u){return u.accessStatus||(u.active===false?'DISABLED':'ACTIVE');}
function visibleUsers(){const cur=current();if(cur?.role==='ADMIN_GLOBAL'||(cur?.role==='ADMINISTRADOR'&&!(cur.siteIds||[]).length))return store.data.users;const allowed=new Set(cur?.siteIds||[]);return store.data.users.filter(u=>u.id===cur?.id||(u.siteIds||[]).some(id=>allowed.has(id)));}
function isLegacyGlobal(u){return u?.role==='ADMINISTRADOR'&&!(u.siteIds||[]).length&&!(u.accessAssignments||[]).length;}
function displayRole(u){return isLegacyGlobal(u)?'Administrador general':roleName(u.role);}
function assignmentSummary(u){if(u.role==='ADMIN_GLOBAL'||isLegacyGlobal(u))return 'Todas las empresas y centros';const list=(u.accessAssignments||[]).map(a=>`${store.data.sites.find(s=>s.id===a.siteId)?.name||a.siteId}: ${roleName(a.role)}`);return list.length?list.join(' · '):`${(u.siteIds||[]).length} centro(s) autorizado(s)`;}
function rows(){const cur=current();return visibleUsers().map(u=>{const status=userStatus(u),isSelf=u.id===cur?.id;return `<div class="user-admin-row ${isSelf?'current-operator-row':''}"><div class="user-avatar">${esc((u.name||'?').slice(0,2).toUpperCase())}</div><div class="user-admin-main"><b>${esc(u.name)}</b><small>@${esc(u.username||'sinusuario')} · ${esc(displayRole(u))}</small><small>${esc(assignmentSummary(u))}</small></div><div>${isSelf?badge('SESIÓN ACTUAL','ok'):badge(STATUS[status]||status,status==='ACTIVE'?'neutral':'warn')}</div><div class="user-admin-actions"><button class="ghost reset-user-password" data-id="${esc(u.id)}" type="button">Restablecer contraseña</button><button class="ghost edit-user" data-id="${esc(u.id)}" type="button">Editar / estado</button></div></div>`;}).join('');}
function roleLegend(){return `<section class="panel role-legend"><div class="panel-head"><div><span class="eyebrow">DESCRIPCIÓN DE PERMISOS</span><h3>Alcance de cada rol</h3></div></div><div class="role-legend-grid"><div><b>Operador de bodega</b><small>Picking, búsqueda, escaneo, movimientos y tareas asignadas en sus centros.</small></div><div><b>Operador de recepción</b><small>Recibe mercadería, registra cantidades y deja pallets o productos por ubicar.</small></div><div><b>Transportista</b><small>Ve sus cargas, revisa el contenido y confirma retiro o llegada sin acceso al inventario general.</small></div><div><b>Encargado</b><small>Coordina la operación de los centros asignados, revisa órdenes y supervisa operarios.</small></div><div><b>Administrador de centro</b><small>Administra usuarios y configuración únicamente en los centros autorizados.</small></div><div><b>Administrador general</b><small>Acceso completo a todas las empresas, centros, configuración y usuarios.</small></div></div><div class="permission-table-wrap"><table class="permission-table"><thead><tr><th>Permiso de códigos</th><th>Administrador</th><th>Encargado</th><th>Operador</th><th>Transportista</th></tr></thead><tbody><tr><td>Consultar producto por código</td><td>✓</td><td>✓</td><td>✓</td><td>—</td></tr><tr><td>Asociar códigos</td><td>✓</td><td>✓</td><td>—</td><td>—</td></tr><tr><td>Crear / editar producto</td><td>✓</td><td>✓</td><td>—</td><td>—</td></tr><tr><td>Modificar inventario directamente</td><td>✓</td><td>✓</td><td>—</td><td>—</td></tr></tbody></table></div><small class="field-help">El operador consulta e identifica productos, pero no cambia códigos ni cantidades. El transportista trabaja exclusivamente con sus cargas.</small></section>`;}
function defaultCodePermissions(role){const manage=['ADMINISTRADOR','ENCARGADO'].includes(role),operator=manage||['OPERADOR_BODEGA','OPERADOR_RECEPCION'].includes(role);return {codesConsult:operator,codesAssociate:manage,productsEdit:manage,inventoryAdjust:manage,palletsView:operator,palletsOperate:operator,palletsRegister:manage};}
function assignmentRows(u,allowedSites){const assignments=(u?.accessAssignments||[]).length?u.accessAssignments:(u?.siteIds||[]).map(siteId=>({siteId,role:u.role})),map=new Map(assignments.map(a=>[a.siteId,a]));return allowedSites.map(s=>{const a=map.get(s.id)||{},role=a.role||'',custom=a.customPermissions===true,permissions=custom?a.permissions||{}:defaultCodePermissions(role);return `<div class="access-assignment-row" data-site-id="${esc(s.id)}" data-company-id="${esc(siteCompanyId(s))}"><span><b>${esc(companyName(siteCompanyId(s)))}</b><small>${esc(s.name)}</small></span><select class="site-role"><option value="">Sin acceso</option>${Object.entries(ROLES).filter(([r])=>r!=='ADMIN_GLOBAL').map(([r,n])=>`<option value="${r}" ${role===r?'selected':''}>${esc(n)}</option>`).join('')}</select><label class="custom-permission-toggle"><input class="site-custom-permissions" type="checkbox" ${custom?'checked':''} ${role?'':'disabled'}> Personalizar permisos de este centro</label><div class="site-permission-options" ${custom?'':'hidden'}>${CODE_PERMISSION_FIELDS.map(([key,label])=>`<label><input type="checkbox" data-permission="${key}" ${permissions[key]===true?'checked':''}> ${label}</label>`).join('')}</div></div>`;}).join('');}
function dialogs(){return `<dialog id="user-dialog"><form id="user-form" class="dialog-card"><div class="dialog-head"><div><span class="eyebrow">USUARIO / ACCESO</span><h3 id="user-dialog-title">Nuevo usuario</h3></div><button type="button" id="close-user-dialog" class="ghost">×</button></div><input id="user-id" type="hidden"><label>Nombre completo<input id="user-name" required maxlength="80" placeholder="Nombre de la persona"></label><label>Nombre de usuario<input id="user-username" required maxlength="40" placeholder="Ej. nelson.g"></label><label>Tipo de acceso<select id="user-global-role"><option value="SCOPED">Asignar rol por centro</option><option value="ADMIN_GLOBAL">Administrador general</option></select><small class="field-help">Un usuario puede ser encargado en una bodega y operario en otra.</small></label><div id="user-assignment-wrap"><b>Rol en cada empresa / centro</b><div id="user-assignments" class="access-assignment-list"></div></div><label>Estado de acceso<select id="user-status"><option value="ACTIVE">Activo</option><option value="PAUSED">Pausado temporalmente</option><option value="DISABLED">Desactivado indefinidamente</option></select><small class="field-help">Pausado o desactivado conserva toda la trazabilidad, pero impide iniciar sesión.</small></label><div id="new-user-password-wrap"><label>Contraseña inicial<input id="user-password" type="password" minlength="8" maxlength="128" placeholder="Mínimo 8 caracteres"></label><small class="field-help">Solo se solicita al crear el usuario.</small></div><div class="warning-box">Cada acción seguirá vinculada a la identidad de esta persona, aunque su acceso se pause o desactive.</div><div class="dialog-actions"><button type="button" id="delete-user" class="danger-action" hidden>Eliminar usuario</button><span class="dialog-actions-spacer"></span><button type="button" id="cancel-user" class="ghost">Cancelar</button><button class="primary" type="submit">Guardar usuario</button></div></form></dialog><dialog id="reset-password-dialog"><form id="reset-password-form" class="dialog-card"><div class="dialog-head"><div><span class="eyebrow">SEGURIDAD</span><h3>Restablecer contraseña</h3></div><button type="button" id="close-reset-password" class="ghost">×</button></div><input id="reset-password-user-id" type="hidden"><p id="reset-password-user-label"></p><label>Nueva contraseña<input id="reset-password-new" type="password" minlength="8" maxlength="128" required></label><label>Confirmar nueva contraseña<input id="reset-password-confirm" type="password" minlength="8" maxlength="128" required></label><label>Tu contraseña administrativa<input id="reset-password-admin" type="password" required></label><div class="dialog-actions"><button type="button" id="cancel-reset-password" class="ghost">Cancelar</button><button class="primary" type="submit">Restablecer contraseña</button></div></form></dialog>`;}

export function renderUsers(root){const cur=current();if(!['ADMIN_GLOBAL','ADMINISTRADOR'].includes(cur?.role)){root.innerHTML=shell('Usuarios','<section class="panel"><h2>Acceso restringido</h2><p>Solo un administrador puede crear o modificar usuarios.</p></section>','usuarios');wireShell();return;}const body=`<div class="page-intro"><div><span class="eyebrow">CONTROL DE ACCESO</span><h2>Usuarios autorizados</h2><p>Define quién entra, su estado y el rol que tendrá en cada bodega.</p></div><button id="new-user" class="primary">+ Nuevo usuario</button></div><section class="panel operator-current"><div><span class="eyebrow">SESIÓN ACTUAL</span><h3>${esc(cur?.name||'Administrador')}</h3><small>@${esc(cur?.username||'admin')} · ${esc(displayRole(cur))}</small></div><button id="change-own-password" class="secondary" type="button">Cambiar mi contraseña</button></section>${roleLegend()}<section class="panel"><div class="panel-head"><div><h3>Personas registradas</h3><small>Los usuarios pausados o desactivados no pueden iniciar sesión.</small></div><span>${visibleUsers().length} usuarios</span></div><div class="user-admin-list">${rows()}</div></section>${dialogs()}`;root.innerHTML=shell('Usuarios',body,'usuarios');wireShell();wireUsers(root);}

function wireUsers(root){
 const dlg=document.querySelector('#user-dialog'),form=document.querySelector('#user-form'),cur=current(),globalAdmin=cur?.role==='ADMIN_GLOBAL'||(cur?.role==='ADMINISTRADOR'&&!(cur.siteIds||[]).length),allowed=new Set(cur?.siteIds||[]),allowedSites=store.data.sites.filter(s=>globalAdmin||allowed.has(s.id));
 let editingUserId=null;
 const toggleAssignments=()=>document.querySelector('#user-assignment-wrap').hidden=document.querySelector('#user-global-role').value==='ADMIN_GLOBAL';
 const wirePermissionEditors=()=>document.querySelectorAll('.access-assignment-row').forEach(row=>{const role=row.querySelector('.site-role'),custom=row.querySelector('.site-custom-permissions'),options=row.querySelector('.site-permission-options');const applyDefaults=()=>{const defaults=defaultCodePermissions(role.value);options.querySelectorAll('[data-permission]').forEach(input=>input.checked=defaults[input.dataset.permission]===true);};role.onchange=()=>{custom.disabled=!role.value;if(!role.value){custom.checked=false;options.hidden=true;}else if(!custom.checked)applyDefaults();};custom.onchange=()=>{options.hidden=!custom.checked;if(custom.checked)applyDefaults();};});
 const open=(u=null)=>{editingUserId=u?.id||null;document.querySelector('#user-dialog-title').textContent=u?'Editar usuario':'Nuevo usuario';document.querySelector('#user-id').value=editingUserId||'';document.querySelector('#user-name').value=u?.name||'';document.querySelector('#user-username').value=u?.username||'';const globalSel=document.querySelector('#user-global-role'),protectedAdmin=editingUserId==='USR-ADMIN';globalSel.querySelector('option[value="ADMIN_GLOBAL"]')?.toggleAttribute('hidden',!globalAdmin);globalSel.value=protectedAdmin||u?.role==='ADMIN_GLOBAL'||isLegacyGlobal(u)?'ADMIN_GLOBAL':'SCOPED';globalSel.disabled=protectedAdmin;document.querySelector('#user-assignments').innerHTML=assignmentRows(u,allowedSites);wirePermissionEditors();const status=document.querySelector('#user-status');status.value=protectedAdmin?'ACTIVE':userStatus(u||{active:true});status.disabled=protectedAdmin;document.querySelector('#user-password').value='';document.querySelector('#user-password').required=!u;document.querySelector('#new-user-password-wrap').hidden=!!u;document.querySelector('#delete-user').hidden=!u||u.id===cur.id||protectedAdmin;toggleAssignments();dlg.showModal();};
 document.querySelector('#user-global-role').onchange=toggleAssignments;document.querySelector('#new-user').onclick=()=>open();document.querySelector('#close-user-dialog').onclick=()=>dlg.close();document.querySelector('#cancel-user').onclick=()=>dlg.close();document.querySelectorAll('.edit-user').forEach(b=>b.onclick=()=>open(store.data.users.find(u=>u.id===b.dataset.id)));
 document.querySelector('#delete-user').onclick=async()=>{const id=document.querySelector('#user-id').value,u=store.data.users.find(x=>x.id===id);if(!id||!confirm(`¿Eliminar a ${u?.name||'este usuario'}? Solo será posible si nunca ha registrado actividad.`))return;const authorized=await requireAdminSupercode(`Vas a eliminar al usuario ${u?.name||''}. Ingresa la misma contraseña administrativa con la que iniciaste sesión.`);if(!authorized)return;try{await apiRequest(`/users/${encodeURIComponent(id)}`,{method:'DELETE'});await store.reload();dlg.close();toast('Usuario eliminado');renderUsers(root);}catch(e){toast(e.message);}};
 const resetDlg=document.querySelector('#reset-password-dialog'),resetForm=document.querySelector('#reset-password-form'),closeReset=()=>{resetForm.reset();resetDlg.close();};document.querySelector('#close-reset-password').onclick=closeReset;document.querySelector('#cancel-reset-password').onclick=closeReset;document.querySelectorAll('.reset-user-password').forEach(b=>b.onclick=()=>{const u=store.data.users.find(x=>x.id===b.dataset.id);resetForm.reset();document.querySelector('#reset-password-user-id').value=u?.id||'';document.querySelector('#reset-password-user-label').textContent=`Usuario: ${u?.name||''} (@${u?.username||''})`;resetDlg.showModal();});
 resetForm.onsubmit=async e=>{e.preventDefault();const id=document.querySelector('#reset-password-user-id').value,newPassword=document.querySelector('#reset-password-new').value,confirmPassword=document.querySelector('#reset-password-confirm').value,adminPassword=document.querySelector('#reset-password-admin').value;if(newPassword!==confirmPassword){toast('Las contraseñas no coinciden.');return;}try{await apiRequest(`/users/${encodeURIComponent(id)}/reset-password`,{method:'POST',body:JSON.stringify({newPassword,adminPassword})});closeReset();toast('Contraseña restablecida correctamente');}catch(ex){toast(ex.message);}};
 document.querySelector('#change-own-password').onclick=async()=>{const currentPassword=prompt('Contraseña actual:');if(currentPassword===null)return;const newPassword=prompt('Nueva contraseña (mínimo 8 caracteres):');if(newPassword===null)return;try{await auth.changePassword(currentPassword,newPassword);toast('Contraseña actualizada');}catch(e){toast(e.message);}};
 form.onsubmit=async e=>{e.preventDefault();const id=editingUserId,hiddenId=document.querySelector('#user-id').value;if(id&&hiddenId!==id){toast('La identidad del usuario cambió inesperadamente. Cierra y vuelve a abrir la edición.');return;}const protectedAdmin=id==='USR-ADMIN',isGlobal=protectedAdmin||document.querySelector('#user-global-role').value==='ADMIN_GLOBAL',accessAssignments=isGlobal?[]:[...document.querySelectorAll('.access-assignment-row')].map(row=>{const role=row.querySelector('.site-role').value;if(!role)return null;const customPermissions=row.querySelector('.site-custom-permissions').checked,permissions=Object.fromEntries([...row.querySelectorAll('[data-permission]')].map(input=>[input.dataset.permission,input.checked]));return {siteId:row.dataset.siteId,companyId:row.dataset.companyId,role,customPermissions,permissions:customPermissions?permissions:{}};}).filter(Boolean);if(!isGlobal&&!accessAssignments.length){toast('Asigna al menos un centro y un rol.');return;}const siteIds=[...new Set(accessAssignments.map(a=>a.siteId))],companyIds=[...new Set(accessAssignments.map(a=>a.companyId))],role=isGlobal?'ADMIN_GLOBAL':accessAssignments.reduce((best,a)=>ROLE_WEIGHT[a.role]>ROLE_WEIGHT[best]?a.role:best,accessAssignments[0].role),body={targetUserId:id||undefined,name:document.querySelector('#user-name').value.trim(),username:document.querySelector('#user-username').value.trim(),role,siteIds,companyIds,accessAssignments,accessStatus:protectedAdmin?'ACTIVE':document.querySelector('#user-status').value};if(!id)body.password=document.querySelector('#user-password').value;try{await apiRequest(id?`/users/${encodeURIComponent(id)}`:'/users',{method:id?'PUT':'POST',body:JSON.stringify(body)});await store.reload();dlg.close();toast(id?'Usuario actualizado':'Usuario creado');renderUsers(root);}catch(ex){toast(ex.message);}};
}
