import { store } from '../../services/store.js';
import { auth } from '../../services/auth.js';
import { apiRequest } from '../../services/api.js';
import { shell, wireShell, toast } from '../../layout/layout.js';
import { esc, badge } from '../../components/ui.js';
const ROLES={ADMINISTRADOR:'Administrador',ENCARGADO:'Encargado',OPERADOR_BODEGA:'Operador de bodega',OPERADOR_RECEPCION:'Operador de recepción'};
function current(){return store.data.users.find(u=>u.id===store.data.session.userId)||auth.user;}
function roleName(role){return ROLES[role]||String(role||'Sin rol').replaceAll('_',' ');}
function rows(){const cur=current();return store.data.users.map(u=>`<div class="user-admin-row ${u.id===cur?.id?'current-operator-row':''}"><div class="user-avatar">${esc((u.name||'?').slice(0,2).toUpperCase())}</div><div class="user-admin-main"><b>${esc(u.name)}</b><small>@${esc(u.username||'sinusuario')} · ${esc(roleName(u.role))} · ${u.active?'Activo':'Inactivo'}</small></div><div>${u.id===cur?.id?badge('SESIÓN ACTUAL','ok'):badge(u.active?'ACTIVO':'INACTIVO',u.active?'neutral':'warn')}</div><div class="user-admin-actions"><button class="ghost edit-user" data-id="${esc(u.id)}" type="button">Editar</button></div></div>`).join('');}
function dialog(){return `<dialog id="user-dialog"><form id="user-form" class="dialog-card"><div class="dialog-head"><div><span class="eyebrow">USUARIO / ACCESO</span><h3 id="user-dialog-title">Nuevo usuario</h3></div><button type="button" id="close-user-dialog" class="ghost">×</button></div><input id="user-id" type="hidden"><label>Nombre completo<input id="user-name" required maxlength="80" placeholder="Nombre de la persona"></label><label>Nombre de usuario<input id="user-username" required maxlength="40" placeholder="Ej. nelson.g"></label><label>Rol<select id="user-role"><option value="OPERADOR_BODEGA">Operador de bodega</option><option value="OPERADOR_RECEPCION">Operador de recepción</option><option value="ENCARGADO">Encargado</option><option value="ADMINISTRADOR">Administrador</option></select></label><label>Centros autorizados<select id="user-sites" multiple size="4"></select><small class="field-help">Puedes asignar uno o varios centros. El administrador general puede quedar sin restricción.</small></label><label>Contraseña temporal<input id="user-password" type="password" minlength="8" placeholder="Mínimo 8 caracteres"></label><small class="field-help">Al crear un usuario la contraseña es obligatoria. Al editar, déjala vacía para conservar la actual.</small><label class="toggle-line"><input id="user-active" type="checkbox" checked> Usuario activo</label><div class="warning-box">Cada persona iniciará sesión con su propio usuario. Sus movimientos, recepciones y despachos quedarán registrados con su identidad.</div><div class="dialog-actions"><button type="button" id="cancel-user" class="ghost">Cancelar</button><button class="primary" type="submit">Guardar usuario</button></div></form></dialog>`;}
export function renderUsers(root){const cur=current();if(cur?.role!=='ADMINISTRADOR'){root.innerHTML=shell('Usuarios','<section class="panel"><h2>Acceso restringido</h2><p>Solo un administrador puede crear o modificar usuarios.</p></section>','usuarios');wireShell();return;}const body=`<div class="page-intro"><div><span class="eyebrow">CONTROL DE ACCESO</span><h2>Usuarios autorizados</h2><p>Registra aquí a cada persona que utilizará el WMS. No hay operadores demo: tú decides quién entra y qué rol tiene.</p></div><button id="new-user" class="primary">+ Nuevo usuario</button></div><section class="panel operator-current"><div><span class="eyebrow">SESIÓN ACTUAL</span><h3>${esc(cur?.name||'Administrador')}</h3><small>@${esc(cur?.username||'admin')} · ${esc(roleName(cur?.role))}</small></div><button id="change-own-password" class="secondary" type="button">Cambiar mi contraseña</button></section><section class="panel"><div class="panel-head"><div><h3>Personas registradas</h3><small>Solo usuarios activos pueden iniciar sesión y aparecen en listas de responsables.</small></div><span>${store.data.users.length} usuarios</span></div><div class="user-admin-list">${rows()}</div></section>${dialog()}`;root.innerHTML=shell('Usuarios',body,'usuarios');wireShell();wireUsers(root);}
function wireUsers(root){const dlg=document.querySelector('#user-dialog'),form=document.querySelector('#user-form');const open=(u=null)=>{document.querySelector('#user-dialog-title').textContent=u?'Editar usuario':'Nuevo usuario';document.querySelector('#user-id').value=u?.id||'';document.querySelector('#user-name').value=u?.name||'';document.querySelector('#user-username').value=u?.username||'';document.querySelector('#user-role').value=u?.role||'OPERADOR_BODEGA';const sites=document.querySelector('#user-sites');sites.innerHTML=store.data.sites.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');[...sites.options].forEach(o=>o.selected=(u?.siteIds||[]).includes(o.value));document.querySelector('#user-password').value='';document.querySelector('#user-password').required=!u;document.querySelector('#user-active').checked=u?.active!==false;dlg.showModal();};const close=()=>dlg.close();document.querySelector('#new-user').onclick=()=>open();document.querySelector('#close-user-dialog').onclick=close;document.querySelector('#cancel-user').onclick=close;document.querySelectorAll('.edit-user').forEach(b=>b.onclick=()=>open(store.data.users.find(u=>u.id===b.dataset.id)));
 document.querySelector('#change-own-password').onclick=async()=>{const currentPassword=prompt('Contraseña actual:');if(currentPassword===null)return;const newPassword=prompt('Nueva contraseña (mínimo 8 caracteres):');if(newPassword===null)return;try{await auth.changePassword(currentPassword,newPassword);toast('Contraseña actualizada');}catch(e){toast(e.message);}};
 form.onsubmit=async e=>{e.preventDefault();const id=document.querySelector('#user-id').value,body={name:document.querySelector('#user-name').value.trim(),username:document.querySelector('#user-username').value.trim(),role:document.querySelector('#user-role').value,siteIds:[...document.querySelector('#user-sites').selectedOptions].map(o=>o.value),password:document.querySelector('#user-password').value,active:document.querySelector('#user-active').checked};try{await apiRequest(id?`/users/${encodeURIComponent(id)}`:'/users',{method:id?'PUT':'POST',body:JSON.stringify(body)});await store.reload();close();toast(id?'Usuario actualizado':'Usuario creado');renderUsers(root);}catch(ex){toast(ex.message);}};}
