import { auth } from '../../services/auth.js';

export function renderLogin(root,onSuccess){
 root.innerHTML=`<main class="login-page"><section class="login-card"><div class="login-brand"><div class="brand-mark">S</div><div><b>SercoRiego Lite WMS</b><small>Control de bodega</small></div></div><div><span class="eyebrow">ACCESO SEGURO</span><h1>Iniciar sesión</h1><p>Ingresa con el usuario y contraseña asignados por el administrador.</p></div><form id="login-form"><label>Usuario<input id="login-user" autocomplete="username" required autofocus></label><label>Contraseña<input id="login-password" type="password" autocomplete="current-password" required></label><div id="login-error" class="login-error" hidden></div><button class="primary login-submit" type="submit">Entrar al WMS</button></form><button id="admin-recovery-open" class="ghost" type="button">Recuperar acceso administrador</button><small class="login-help">Los usuarios se crean desde el módulo Usuarios. Las contraseñas se guardan protegidas y pueden restablecerse de forma segura.</small></section><dialog id="admin-recovery-dialog"><form id="admin-recovery-form" class="dialog-card"><div class="dialog-head"><div><span class="eyebrow">RECUPERACIÓN SEGURA</span><h3>Recuperar administrador</h3></div><button type="button" id="admin-recovery-close" class="ghost">×</button></div><p>Usa la clave de recuperación configurada en Render. Esta operación no toca inventario ni otros usuarios.</p><label>Clave de recuperación<input id="admin-recovery-key" type="password" autocomplete="off" required></label><label>Nueva contraseña<input id="admin-recovery-password" type="password" minlength="8" maxlength="128" autocomplete="new-password" required></label><label>Confirmar nueva contraseña<input id="admin-recovery-confirm" type="password" minlength="8" maxlength="128" autocomplete="new-password" required></label><div id="admin-recovery-error" class="login-error" hidden></div><div class="dialog-actions"><button type="button" id="admin-recovery-cancel" class="ghost">Cancelar</button><button class="primary" type="submit">Restablecer administrador</button></div></form></dialog></main>`;
 const form=document.querySelector('#login-form'),error=document.querySelector('#login-error');
 form.onsubmit=async e=>{e.preventDefault();error.hidden=true;const btn=form.querySelector('button[type=submit]');btn.disabled=true;try{await auth.login(document.querySelector('#login-user').value,document.querySelector('#login-password').value);await onSuccess();}catch(ex){error.textContent=ex.message;error.hidden=false;}finally{btn.disabled=false;}};
 const dlg=document.querySelector('#admin-recovery-dialog');
 document.querySelector('#admin-recovery-open').onclick=()=>dlg.showModal();
 document.querySelector('#admin-recovery-close').onclick=()=>dlg.close();
 document.querySelector('#admin-recovery-cancel').onclick=()=>dlg.close();
 const rf=document.querySelector('#admin-recovery-form'),re=document.querySelector('#admin-recovery-error');
 rf.onsubmit=async e=>{e.preventDefault();re.hidden=true;const p=document.querySelector('#admin-recovery-password').value,c=document.querySelector('#admin-recovery-confirm').value;if(p!==c){re.textContent='Las contraseñas no coinciden.';re.hidden=false;return;}const btn=rf.querySelector('button[type=submit]');btn.disabled=true;try{await auth.recoverAdmin(document.querySelector('#admin-recovery-key').value,p);dlg.close();document.querySelector('#login-user').value='admin';document.querySelector('#login-password').value='';error.textContent='Contraseña administrativa restablecida. Ya puedes iniciar sesión.';error.hidden=false;rf.reset();}catch(ex){re.textContent=ex.message;re.hidden=false;}finally{btn.disabled=false;}};
}
